import type { Lecture } from '../../lib/types';
import { ACTION_POTENTIAL } from '../../lib/figures';

export const actionPotentialGenesis: Lecture = {
  id: 'action-potential-genesis',
  title: 'Genesis of the Neuron Action Potential',
  system: 'physiology',
  source: 'L4 — Genesis of the Action Potential',
  updated: '2026-07-02',
  tags: [
    { kind: 'system', label: 'Physiology' },
    { kind: 'lecture', label: 'L4 Action Potential' },
    { kind: 'mechanism', label: 'Na⁺/K⁺ channel dance' },
    { kind: 'exam', label: 'AP phases · threshold' },
  ],

  highYield: [
    '**An action potential (AP) is a rapid, all-or-none reversal of membrane potential** that carries the nerve impulse. It arises from the sequential opening of **voltage-gated Na⁺ then K⁺ channels**.',
    '**Channel types set the stage.** **Non-gated (leak) channels** (mostly K⁺) set the resting potential. **Gated channels** open in response to a stimulus: **voltage-gated** (electrical — drive the AP), **ligand-gated** (chemical — synapses), and **mechanically-gated** (force/pressure — sensory).',
    '**AP phases.** (1) **Depolarisation:** a stimulus reaching **threshold (~−55 mV)** opens **voltage-gated Na⁺ channels → Na⁺ rushes in** → the inside becomes positive (~+30 mV), a regenerative positive-feedback upstroke. (2) **Repolarisation:** Na⁺ channels **inactivate** and **voltage-gated K⁺ channels open → K⁺ leaves** → potential falls. (3) **Hyperpolarisation (undershoot):** K⁺ channels close slowly, briefly overshooting past rest.',
    '**All-or-none:** a stimulus at or above threshold triggers a **full-amplitude** AP; a sub-threshold stimulus triggers **none**. AP size is fixed — stimulus strength is coded by **frequency**, not amplitude.',
    '**The Na⁺/K⁺-ATPase restores the gradients afterward** (it does not itself generate the AP — the ion movements do). A single AP moves very few ions, so many APs can fire before the pump is needed to "top up."',
  ],

  mechanism: {
    title: 'Threshold → Na⁺ in → K⁺ out',
    steps: [
      { id: 's1', label: 'Leak K⁺ channels set RMP; stimulus depolarises to threshold', emphasis: 'key' },
      { id: 's2', label: 'Threshold (~−55) opens voltage-gated Na⁺ → Na⁺ IN (depolarise)', emphasis: 'key' },
      { id: 's3', label: 'Na⁺ channels inactivate; voltage-gated K⁺ open → K⁺ OUT (repolarise)', emphasis: 'key' },
      { id: 's4', label: 'K⁺ overshoot → hyperpolarisation, then back to RMP' },
      { id: 's5', label: 'All-or-none; Na⁺/K⁺-ATPase restores gradients later' },
    ],
  },

  examFindings: [
    { sign: 'Rapid depolarisation to ~+30 mV', mechanism: 'Voltage-gated Na⁺ channels open → Na⁺ influx', significance: 'key' },
    { sign: 'Repolarisation back toward rest', mechanism: 'Na⁺ inactivation + voltage-gated K⁺ efflux', significance: 'key' },
    { sign: 'Brief undershoot below RMP', mechanism: 'Slow K⁺ channel closure (hyperpolarisation)', significance: 'supportive' },
    { sign: 'Sub-threshold stimulus produces no AP', mechanism: 'All-or-none threshold not reached', significance: 'key' },
    { sign: 'Stronger stimulus → higher AP frequency (same amplitude)', mechanism: 'Intensity coded by frequency', significance: 'supportive' },
  ],

  investigations: [
    { clue: 'Channel responsible for the depolarising upstroke', meaning: 'Voltage-gated Na⁺ channel' },
    { clue: 'Channel responsible for repolarisation', meaning: 'Voltage-gated K⁺ channel' },
    { clue: 'Membrane potential at which an AP is triggered', meaning: 'Threshold (~−55 mV)' },
    { clue: 'How stimulus strength is encoded', meaning: 'AP frequency (not amplitude)' },
  ],

  treatment: [
    { logic: 'Why it matters', detail: 'AP physiology underlies local anaesthetics (block Na⁺ channels), anticonvulsants, and channelopathies. Propagation and refractoriness: [[action-potential-propagation-refractory]]; the resting baseline it starts from: [[resting-membrane-potential-nernst]].' },
  ],

  mnemonics: [
    { hook: 'Up = Na⁺ in (depolarise); Down = K⁺ out (repolarise)', expansion: ['Threshold −55, peak +30'] },
    { hook: 'All-or-none: strength coded by FREQUENCY, not size', expansion: ['Fixed AP amplitude'] },
  ],

  traps: [
    {
      questionCategory: 'Role of the Na⁺/K⁺-ATPase in the AP',
      wrongInstinct: 'The Na⁺/K⁺-ATPase directly produces the action potential',
      rightAnswer: 'The AP is generated by ION FLOW through voltage-gated Na⁺ and K⁺ channels; the Na⁺/K⁺-ATPase only restores the gradients afterward',
      why: 'The pump maintains the gradients over time but is not the fast event; the up/down strokes are passive ion movements through gated channels.',
    },
  ],

  quiz: [
    {
      id: 'q1',
      stem: 'The rapid depolarising (upstroke) phase of the neuronal action potential is caused by:',
      options: [
        { id: 'a', text: 'K⁺ efflux through voltage-gated K⁺ channels' },
        { id: 'b', text: 'Na⁺ influx through voltage-gated Na⁺ channels' },
        { id: 'c', text: 'Cl⁻ influx' },
        { id: 'd', text: 'The Na⁺/K⁺-ATPase pumping ions' },
      ],
      answerId: 'b',
      explanation: 'Reaching threshold opens voltage-gated Na⁺ channels; Na⁺ rushes in, reversing the potential toward +30 mV. Repolarisation is due to Na⁺ inactivation plus K⁺ efflux.',
      tests: 'exam',
    },
    {
      id: 'q2',
      stem: 'The "all-or-none" property of the action potential means that:',
      options: [
        { id: 'a', text: 'AP amplitude increases with stronger stimuli' },
        { id: 'b', text: 'A stimulus at or above threshold produces a full-amplitude AP, and stimulus strength is coded by frequency' },
        { id: 'c', text: 'APs can summate in amplitude' },
        { id: 'd', text: 'Sub-threshold stimuli produce small APs' },
      ],
      answerId: 'b',
      explanation: 'Once threshold is reached, the AP fires at full, fixed amplitude regardless of stimulus strength; a stronger stimulus increases AP frequency, not size. Sub-threshold stimuli produce no AP.',
      tests: 'mechanism',
    },
  ],

  figures: [
    { title: 'The action potential', svg: ACTION_POTENTIAL, caption: 'Threshold → Na⁺ influx (depolarise) → Na⁺ inactivate + K⁺ efflux (repolarise) → hyperpolarisation. All-or-none; refractory periods.' },
  ],
};

export default actionPotentialGenesis;
