import type { Lecture } from '../../lib/types';
import { ANTIBODY_STRUCTURE } from '../../lib/figures';

export const antibodyStructure: Lecture = {
  id: 'antibody-structure',
  title: 'Immunoglobulin Structure & Diversity',
  system: 'immune',
  source: 'L3 — Immunoglobulins',
  updated: '2026-07-01',
  tags: [
    { kind: 'system', label: 'Immunology' },
    { kind: 'lecture', label: 'L3 Immunoglobulins' },
    { kind: 'mechanism', label: 'Fab/Fc · V(D)J' },
    { kind: 'exam', label: 'Domains & fragments' },
  ],

  highYield: [
    '**Basic unit = 2 identical heavy + 2 identical light chains** in a Y shape, held by disulfide bonds. Each chain has a **variable (V) region** and **constant (C) region**. The flexible **hinge** allows the two arms to move.',
    '**Fab vs Fc.** Each **Fab** ("fragment antigen-binding") arm = one light chain + part of a heavy chain → contains the **antigen-binding site** (2 per antibody). The **Fc** ("fragment crystallisable") = paired heavy-chain constant regions → the **effector end** (binds complement C1q, Fc receptors, determines isotype, mediates placental transfer). Papain cuts into 2 Fab + Fc; pepsin gives F(ab\')₂.',
    '**Where specificity lives.** The **variable region** — especially the **hypervariable regions / complementarity-determining regions (CDRs)** — forms the antigen-binding pocket and determines **specificity**. The **constant region (Fc)** determines the **biological function/class**.',
    '**Three levels of variation.** **Isotype** = the class (IgG/A/M/E/D), set by the **heavy-chain constant region** (γ/α/μ/ε/δ). **Allotype** = allelic differences within a species. **Idiotype** = the unique **variable/antigen-binding region** of one clone.',
    '**Antibody diversity is generated by V(D)J recombination** (random rejoining of Variable, Diversity, Joining gene segments) plus junctional diversity and, later, **somatic hypermutation** in germinal centres — creating billions of specificities from a limited genome. **Monoclonal** antibodies come from one clone (one specificity); **polyclonal** from many.',
  ],

  mechanism: {
    title: 'Two ends: bind (Fab) + act (Fc)',
    steps: [
      { id: 's1', label: '2 heavy + 2 light chains; variable + constant regions', emphasis: 'key' },
      { id: 's2', label: 'Fab = antigen binding (V region + CDRs); Fc = effector', emphasis: 'key' },
      { id: 's3', label: 'Hypervariable CDRs → specificity' },
      { id: 's4', label: 'Isotype (class) vs allotype (allele) vs idiotype (unique V)' },
      { id: 's5', label: 'Diversity: V(D)J recombination + somatic hypermutation', emphasis: 'key' },
    ],
  },

  examFindings: [
    { sign: 'Antigen-binding site location', mechanism: 'Fab, formed by variable regions of heavy + light chains (CDRs)', significance: 'key' },
    { sign: 'Complement/Fc-receptor binding', mechanism: 'Fc (heavy-chain constant region) determines effector function', significance: 'key' },
    { sign: 'Class determined by heavy-chain constant region', mechanism: 'Isotype (γ/α/μ/ε/δ = IgG/A/M/E/D)', significance: 'supportive' },
    { sign: 'Billions of antibody specificities from limited genes', mechanism: 'V(D)J recombination + junctional diversity + SHM', significance: 'key' },
  ],

  investigations: [
    { clue: 'Fragment that still binds antigen after papain digestion', meaning: 'Fab (2 produced) — Fc is the third fragment' },
    { clue: 'Region determining whether an antibody activates complement', meaning: 'Fc / constant region (isotype)' },
    { clue: 'The unique variable region of a single B-cell clone', meaning: 'Idiotype' },
    { clue: 'Process creating antigen-receptor diversity in the marrow', meaning: 'V(D)J recombination' },
  ],

  treatment: [
    { logic: 'Why it matters', detail: 'Therapeutic monoclonal antibodies exploit Fab specificity + engineered Fc effector functions; Fc mediates placental IgG transfer (neonatal immunity, Rh disease). Diversity generation links to [[b-cell-development-tolerance]]. Class properties: [[antibody-classes-functions]].' },
  ],

  mnemonics: [
    { hook: 'Fab = "Fragment antigen binding" (variable); Fc = "Fragment constant/effector"', expansion: ['2 Fab arms, 1 Fc stem'] },
    { hook: 'Isotype=class, Allotype=Allele, Idiotype=Individual variable region', expansion: ['Heavy C region sets isotype'] },
  ],

  traps: [
    {
      questionCategory: 'What determines antibody class?',
      wrongInstinct: 'The light chain (kappa/lambda) determines the antibody class',
      rightAnswer: 'The HEAVY-chain constant region (γ/α/μ/ε/δ) determines the isotype/class; light chains are only κ or λ',
      why: 'Class = heavy-chain constant region. The variable region sets specificity; light-chain type does not define IgG vs IgA etc.',
    },
  ],

  quiz: [
    {
      id: 'q1',
      stem: 'The antigen-binding specificity of an antibody is determined primarily by the:',
      options: [
        { id: 'a', text: 'Fc region' },
        { id: 'b', text: 'Hinge region' },
        { id: 'c', text: 'Hypervariable (CDR) loops of the variable regions' },
        { id: 'd', text: 'Heavy-chain constant region' },
      ],
      answerId: 'c',
      explanation: 'The complementarity-determining regions (CDRs/hypervariable regions) of the heavy and light variable domains form the antigen-binding pocket. The Fc/constant region governs effector function.',
      tests: 'exam',
    },
    {
      id: 'q2',
      stem: 'Which region of the immunoglobulin molecule determines its isotype (class) and effector functions such as complement activation?',
      options: [
        { id: 'a', text: 'The variable region of the light chain' },
        { id: 'b', text: 'The Fc (heavy-chain constant region)' },
        { id: 'c', text: 'The CDR3 loop' },
        { id: 'd', text: 'The hinge region' },
      ],
      answerId: 'b',
      explanation: 'The Fc — formed by the heavy-chain constant region — defines the isotype (γ/α/μ/ε/δ) and mediates effector functions (complement, Fc-receptor binding, placental transfer).',
      tests: 'mechanism',
    },
  ],

  figures: [
    { title: 'Antibody structure', svg: ANTIBODY_STRUCTURE, caption: 'Heavy + light chains; Fab (variable, antigen-binding) vs Fc (constant, effector); hinge; isotype/allotype/idiotype.' },
  ],
};

export default antibodyStructure;
