import type { Lecture } from '../../lib/types';

export const cellInjuryFreeRadicals: Lecture = {
  id: 'cell-injury-free-radicals',
  title: 'Cell Injury & Free Radicals',
  system: 'physiology',
  source: 'L11 — Cellular Aging & Cell Death',
  updated: '2026-07-02',
  tags: [
    { kind: 'system', label: 'Physiology' },
    { kind: 'lecture', label: 'L11 Aging & Cell Death' },
    { kind: 'mechanism', label: 'Reversible vs irreversible' },
    { kind: 'exam', label: 'Free radical injury' },
  ],

  highYield: [
    'Cell injury exists on a spectrum from REVERSIBLE to IRREVERSIBLE, and the point of no return is the transition to cell death (necrosis/apoptosis — [[apoptosis-necrosis]]). Common causes: hypoxia/ischaemia (the commonest), toxins, infection, physical/chemical agents, immune reactions, genetic and nutritional factors.',
    '**REVERSIBLE injury features CELLULAR SWELLING (from failure of the ATP-dependent Na⁺/K⁺ pump → Na⁺ and water enter) and fatty change; the mitochondria and membranes are stressed but intact.** Hallmarks of the switch to IRREVERSIBLE injury are **severe membrane damage, massive Ca²⁺ influx, and mitochondrial dysfunction** — after which the cell cannot recover.',
    '**Hypoxia/ischaemia injures cells by depleting ATP: the Na⁺/K⁺ pump fails (swelling), anaerobic glycolysis lowers pH, ribosomes detach (↓protein synthesis), and rising cytosolic Ca²⁺ activates destructive enzymes** (phospholipases, proteases, endonucleases). Restoring blood flow can paradoxically add **reperfusion injury** via a burst of free radicals.',
    '**FREE RADICALS (reactive oxygen species — superoxide, hydrogen peroxide, hydroxyl radical) have unpaired electrons and damage cells by LIPID PEROXIDATION of membranes, protein oxidation and DNA damage.** They are generated by normal metabolism, reperfusion, radiation, toxins and inflammation, and are countered by ANTIOXIDANT defences: enzymes (superoxide dismutase, catalase, glutathione peroxidase) and vitamins (C, E).',
    'Free-radical injury and accumulated damage are central to the theories of CELLULAR AGEING ([[cellular-aging-theories]]) as well as to acute injury, ischaemia-reperfusion, and toxin/drug damage (e.g. paracetamol, carbon tetrachloride). The unifying theme: injury is reversible until membranes/mitochondria/Ca²⁺ homeostasis fail — and oxidative stress is a common final pathway.',
  ],

  mechanism: {
    title: 'Reversible (swelling) → irreversible (membrane/Ca²⁺/mito failure); free-radical oxidative damage',
    steps: [
      { id: 's1', label: 'Injury spectrum: reversible → irreversible → cell death', emphasis: 'key' },
      { id: 's2', label: 'Reversible: cellular SWELLING (pump failure), fatty change', emphasis: 'key' },
      { id: 's3', label: 'Irreversible: membrane damage + massive Ca²⁺ influx + mitochondrial failure', emphasis: 'danger' },
      { id: 's4', label: 'Ischaemia depletes ATP → pump fails, ↓pH, ↑Ca²⁺; reperfusion → radicals' },
      { id: 's5', label: 'Free radicals (ROS): lipid peroxidation/DNA damage; antioxidants (SOD, catalase, vit C/E)', emphasis: 'key' },
    ],
  },

  examFindings: [
    { sign: 'Cellular swelling as an early injury change', mechanism: 'ATP depletion → Na⁺/K⁺ pump failure (reversible)', significance: 'key' },
    { sign: 'Massive Ca²⁺ influx with membrane rupture', mechanism: 'Irreversible injury (point of no return)', significance: 'key' },
    { sign: 'Worsened damage after restoring blood flow', mechanism: 'Reperfusion injury (free-radical burst)', significance: 'key' },
    { sign: 'Membrane lipid peroxidation and DNA damage', mechanism: 'Reactive oxygen species (free radicals)', significance: 'key' },
    { sign: 'Protection by superoxide dismutase or vitamins C/E', mechanism: 'Antioxidant defence against radicals', significance: 'supportive' },
  ],

  investigations: [
    { clue: 'The earliest, reversible morphological change of cell injury', meaning: 'Cellular swelling (from Na⁺/K⁺ pump failure)' },
    { clue: 'The changes marking irreversible injury', meaning: 'Severe membrane damage, massive Ca²⁺ influx, mitochondrial failure' },
    { clue: 'The main way free radicals damage membranes', meaning: 'Lipid peroxidation' },
    { clue: 'The enzymatic antioxidant defences', meaning: 'Superoxide dismutase, catalase, glutathione peroxidase' },
  ],

  treatment: [
    { logic: 'Why it matters', detail: 'The reversible/irreversible threshold decides whether a cell (or organ) can be salvaged — the basis of treating ischaemia (e.g. reperfusion, while managing reperfusion injury). Terminal injury proceeds to the necrosis/apoptosis of [[apoptosis-necrosis]], and cumulative oxidative damage underlies the [[cellular-aging-theories]]. Ischaemic injury connects to the hypoxia-prone renal medulla and to ATN elsewhere in the curriculum.' },
  ],

  mnemonics: [
    { hook: 'Reversible → irreversible: "Swelling (pump fails) → Membrane/Ca²⁺/Mito failure (point of no return)"', expansion: ['Reversible: swelling, fatty change', 'Irreversible: Ca²⁺ flood, membrane rupture'] },
    { hook: 'Free radicals damage "Lipids, Proteins, DNA"; antioxidants = SOD, catalase, vit C/E', expansion: ['Lipid peroxidation of membranes', 'Reperfusion = radical burst'] },
  ],

  traps: [
    {
      questionCategory: 'The point of irreversibility in cell injury',
      wrongInstinct: 'Cellular swelling means the cell is already dead',
      rightAnswer: 'Cellular SWELLING is a REVERSIBLE change (from ATP-dependent pump failure); the cell only becomes irreversibly injured once there is severe MEMBRANE damage, massive CALCIUM influx and MITOCHONDRIAL failure — that is the point of no return',
      why: 'Distinguishing reversible swelling from irreversible membrane/mitochondrial collapse determines whether restoring oxygen/ATP can still save the cell — the rationale for prompt reperfusion in ischaemia.',
    },
  ],

  quiz: [
    {
      id: 'q1',
      stem: 'The earliest, reversible morphological manifestation of acute cell injury (e.g. from hypoxia) is:',
      options: [
        { id: 'a', text: 'Nuclear fragmentation' },
        { id: 'b', text: 'Cellular swelling due to failure of the ATP-dependent Na⁺/K⁺ pump' },
        { id: 'c', text: 'Massive calcium influx with membrane rupture' },
        { id: 'd', text: 'Apoptotic body formation' },
      ],
      answerId: 'b',
      explanation: 'ATP depletion in hypoxia disables the Na⁺/K⁺-ATPase, so sodium and water enter the cell, causing cellular swelling — the earliest reversible change. Membrane rupture and massive calcium influx mark irreversible injury.',
      tests: 'exam',
    },
    {
      id: 'q2',
      stem: 'Free radicals (reactive oxygen species) injure cells principally by:',
      options: [
        { id: 'a', text: 'Increasing ATP production' },
        { id: 'b', text: 'Lipid peroxidation of membranes, protein oxidation and DNA damage' },
        { id: 'c', text: 'Activating the Na⁺/K⁺ pump' },
        { id: 'd', text: 'Stabilising mitochondria' },
      ],
      answerId: 'b',
      explanation: 'Reactive oxygen species have unpaired electrons that damage cells through lipid peroxidation of membranes, oxidation of proteins and DNA damage; antioxidant enzymes (superoxide dismutase, catalase) and vitamins C and E defend against them.',
      tests: 'mechanism',
    },
  ],

  figures: [],
};

export default cellInjuryFreeRadicals;
