import type { Lecture } from '../../lib/types';

export const complementFunctionsRegulation: Lecture = {
  id: 'complement-functions-regulation',
  title: 'Complement: Functions, Regulation & Deficiencies',
  system: 'immune',
  source: 'L4 — Complement System',
  updated: '2026-07-01',
  tags: [
    { kind: 'system', label: 'Immunology' },
    { kind: 'lecture', label: 'L4 Complement' },
    { kind: 'mechanism', label: 'Effectors & control' },
    { kind: 'exam', label: 'Deficiency patterns' },
  ],

  highYield: [
    '**Three main effector functions.** **Opsonisation** — **C3b** coats microbes; phagocyte **CR1** binds it → enhanced phagocytosis. **Inflammation** — **C3a and C5a are anaphylatoxins** (mast-cell degranulation, vasodilation); **C5a is also a potent chemoattractant** for neutrophils. **Lysis** — **MAC (C5b–C9)** punches pores in the membrane (especially important against **Neisseria**).',
    '**Complement must be tightly regulated** to spare host cells. Key regulators: **C1 inhibitor (C1-INH)** (controls the classical/contact system), **decay-accelerating factor (DAF/CD55)** and **CD59** (block MAC assembly on self cells), and factor H/I (alternative pathway).',
    '**Deficiency of early components (C1, C2, C4)** → impaired clearance of immune complexes → **immune-complex disease / SLE-like** presentations, plus pyogenic infections. C2 deficiency is the most common.',
    '**C3 deficiency** (the hub) → **severe, recurrent pyogenic infections** and immune-complex disease — the most serious, since all pathways depend on C3.',
    '**Terminal / regulator defects.** **C5–C9 (MAC) deficiency → recurrent Neisseria** infections (meningococcus). **C1-inhibitor deficiency → hereditary angioedema** (unopposed bradykinin → recurrent non-pruritic swelling). **DAF/CD59 loss → paroxysmal nocturnal haemoglobinuria** (complement-mediated RBC lysis).',
  ],

  mechanism: {
    title: 'Opsonise, inflame, lyse — under strict control',
    steps: [
      { id: 's1', label: 'C3b → opsonisation (CR1 phagocytosis)', emphasis: 'key' },
      { id: 's2', label: 'C3a/C5a → anaphylatoxins (inflammation); C5a chemotaxis', emphasis: 'key' },
      { id: 's3', label: 'MAC (C5b-9) → lysis (esp. Neisseria)' },
      { id: 's4', label: 'Regulators: C1-INH, DAF/CD55, CD59 protect self', emphasis: 'key' },
      { id: 's5', label: 'Deficiency patterns localise the defect', emphasis: 'danger' },
    ],
  },

  examFindings: [
    { sign: 'Recurrent Neisseria (meningococcal) infections', mechanism: 'Terminal complement (C5–C9 / MAC) deficiency', significance: 'key' },
    { sign: 'SLE-like immune-complex disease + pyogenic infections', mechanism: 'Early classical component deficiency (C1/C2/C4)', significance: 'key' },
    { sign: 'Recurrent non-pruritic angioedema (no urticaria)', mechanism: 'C1-inhibitor deficiency (hereditary angioedema, ↑bradykinin)', significance: 'key' },
    { sign: 'Complement-mediated intravascular haemolysis', mechanism: 'PNH — loss of DAF/CD59 (GPI anchor defect)', significance: 'supportive' },
    { sign: 'Severe recurrent pyogenic infection', mechanism: 'C3 deficiency (central hub)', significance: 'key' },
  ],

  investigations: [
    { clue: 'A patient with recurrent meningococcal meningitis', meaning: 'Screen terminal complement (CH50 low, C5–C9)' },
    { clue: 'Non-allergic recurrent facial/laryngeal swelling', meaning: 'C1-inhibitor deficiency (hereditary angioedema)' },
    { clue: 'Neutrophil chemoattractant generated by complement', meaning: 'C5a' },
    { clue: 'Complement fragment that opsonises for phagocytosis', meaning: 'C3b (via CR1)' },
  ],

  treatment: [
    { logic: 'Why it matters', detail: 'Terminal-complement deficiency mandates meningococcal vaccination; eculizumab (anti-C5) treats PNH/aHUS; C1-INH concentrate treats hereditary angioedema. Deficiency patterns are high-yield in [[primary-immunodeficiency-antibody-t]] logic. Pathways: [[complement-pathways]].' },
  ],

  mnemonics: [
    { hook: 'Terminal (C5-9) deficiency = Neisseria; Early (C1-4) = lupus/immune complex; C1-INH = angioedema', expansion: ['C3 = severe pyogenic'] },
    { hook: 'C3b = opsonin (Binds phagocyte); C3a/C5a = anaphylatoxins; C5a = chemotaxis', expansion: ['MAC = C5b-9 lysis'] },
  ],

  traps: [
    {
      questionCategory: 'Recurrent Neisseria — which deficiency?',
      wrongInstinct: 'Recurrent Neisseria infection indicates an antibody (B-cell) deficiency',
      rightAnswer: 'Recurrent Neisseria points to TERMINAL COMPLEMENT (C5–C9/MAC) deficiency — MAC lysis is essential against Neisseria',
      why: 'Neisseria are uniquely susceptible to MAC-mediated lysis; recurrent neisserial disease is the classic clue to terminal complement deficiency.',
    },
  ],

  quiz: [
    {
      id: 'q1',
      stem: 'A young adult presents with a second episode of meningococcal meningitis. Which immune defect is most likely?',
      options: [
        { id: 'a', text: 'Early complement (C1–C4) deficiency' },
        { id: 'b', text: 'Terminal complement (C5–C9/MAC) deficiency' },
        { id: 'c', text: 'IgA deficiency' },
        { id: 'd', text: 'Chronic granulomatous disease' },
      ],
      answerId: 'b',
      explanation: 'Recurrent Neisseria infection is the hallmark of terminal complement (MAC, C5–C9) deficiency, because MAC-mediated lysis is the key defence against Neisseria.',
      tests: 'exam',
    },
    {
      id: 'q2',
      stem: 'Hereditary angioedema, presenting as recurrent non-pruritic swelling without urticaria, is caused by deficiency of:',
      options: [
        { id: 'a', text: 'C3' },
        { id: 'b', text: 'C1 inhibitor' },
        { id: 'c', text: 'DAF (CD55)' },
        { id: 'd', text: 'Mannose-binding lectin' },
      ],
      answerId: 'b',
      explanation: 'C1-inhibitor deficiency leads to unregulated activation of the classical/contact pathways with excess bradykinin, causing recurrent angioedema. DAF/CD59 loss causes PNH.',
      tests: 'mechanism',
    },
  ],

  figures: [],
};

export default complementFunctionsRegulation;
