import type { Lecture } from '../../lib/types';

export const ghpSmoothMuscleRegulation: Lecture = {
  id: 'ghp-smooth-muscle-regulation',
  title: 'Regulation of Smooth Muscle: Nerves, Hormones & Local Factors',
  system: 'physiology',
  source: 'Ch 8 — Contraction and Excitation of Smooth Muscle',
  updated: '2026-09-09',
  tags: [
    { kind: 'system', label: 'Physiology' },
    { kind: 'lecture', label: 'Ch 8 Smooth Muscle' },
    { kind: 'mechanism', label: 'Slow waves → spike potentials' },
    { kind: 'exam', label: 'Extracellular Ca²⁺ · hormonal control' },
  ],

  highYield: [
    '**There is no motor end plate.** Autonomic axons run across the muscle in **diffuse junctions**: terminal branches carry **varicosities** — beads packed with vesicles — that spill **ACh or noradrenaline** into the interstitium anywhere from **20 nm to 20 000 nm** away. Transmission is therefore **slow, broad and shared**, one axon influencing many fibres, and the same transmitter is **excitatory in one organ and inhibitory in another** — the response is set by the **receptor on the target**, never by the transmitter itself.',
    '**The resting potential is only −50 to −60 mV** — less negative and far less stable than skeletal muscle, so it sits close to threshold and small influences can fire it. In unitary smooth muscle the action potential is a **Ca²⁺ spike carried through L-type channels rather than a fast Na⁺ spike**, so the upstroke is slow — and the charge carrier is itself the contractile trigger. **Plateau potentials** lasting up to **1000 ms** (ureter, uterus, some vessels) drive prolonged contraction.',
    '**Slow waves are NOT action potentials.** They are rhythmic **5–15 mV oscillations of the resting potential**, generated by **interstitial cells of Cajal** — the basic electrical rhythm. A slow wave alone contracts nothing; only when its crest is driven **above threshold (about −40 mV)** do **spike potentials ride on top**, and contraction follows. Slow-wave frequency therefore sets the **maximum possible** contraction rate: stomach ~**3/min**, duodenum ~**12/min**, ileum ~**8–9/min**.',
    '**Activator Ca²⁺ comes mostly from OUTSIDE the cell.** The smooth muscle SR is sparse, so Ca²⁺ enters through **voltage-gated and ligand-gated sarcolemmal channels** (with an SR and caveolar contribution released by **IP₃**). Two consequences follow: contraction is **slow to start** (Ca²⁺ must diffuse inward) and **slow to end** (removal by slow pumps and Na⁺/Ca²⁺ exchange) — and smooth muscle, unlike skeletal, is **exquisitely sensitive to extracellular Ca²⁺ and to Ca²⁺-channel blockers**.',
    '**Stretch is itself a stimulus.** Stretch opens mechanosensitive channels → depolarisation → spike potentials → contraction. This is the **myogenic response** of arterioles (autoregulation) and the reason a gut bolus provokes contraction behind it. Sustained stretch, by contrast, triggers stress-relaxation and the organ accommodates.',
    '**Hormones and local tissue factors can contract or relax smooth muscle with NO action potential at all.** Receptor occupancy may open or close channels, or act purely through second messengers: **IP₃ → SR Ca²⁺ release** (contraction) or **cAMP/cGMP → MLCK restraint and Ca²⁺ removal** (relaxation). Constrictors: **noradrenaline, angiotensin II, vasopressin, endothelin, oxytocin (uterus), histamine and serotonin** — tissue-dependent. Dilators: **endothelial nitric oxide**, adenosine, and the local metabolic signature of a working tissue — **low O₂, high CO₂, H⁺, K⁺, lactate, hyperosmolality** — which needs neither nerves nor spikes.',
  ],

  mechanism: {
    title: 'Slow wave → threshold → Ca²⁺ spike → contraction; hormones bypass all of it',
    steps: [
      { id: 's1', label: 'Varicosities release ACh or noradrenaline into a diffuse junction', emphasis: 'key' },
      { id: 's2', label: 'Interstitial cells of Cajal set a slow-wave rhythm (no contraction alone)', emphasis: 'key' },
      { id: 's3', label: 'Crest driven above threshold → Ca²⁺ spike potentials fire', emphasis: 'key' },
      { id: 's4', label: 'Ca²⁺ enters mainly from the ECF through L-type channels', emphasis: 'key' },
      { id: 's5', label: 'Ca²⁺-calmodulin-MLCK → contraction; slow removal → slow relaxation' },
      { id: 's6', label: 'Hormones and local factors act via IP₃ or cAMP with no action potential', emphasis: 'key' },
    ],
  },

  examFindings: [
    { sign: 'Gastric contractions never exceed about three per minute', mechanism: 'The slow-wave basic electrical rhythm caps the possible contraction rate', significance: 'key' },
    { sign: 'Nifedipine relaxes vascular and uterine muscle but does not weaken skeletal muscle', mechanism: 'Smooth muscle activator Ca²⁺ enters from the ECF; skeletal Ca²⁺ is all from SR', significance: 'key' },
    { sign: 'A distended segment of gut contracts behind the bolus', mechanism: 'Stretch depolarises the membrane and triggers spike potentials (myogenic)', significance: 'key' },
    { sign: 'Vessels in exercising muscle dilate even with the sympathetic nerves cut', mechanism: 'Local metabolites (low O2, adenosine, H+, K+) relax the muscle directly', significance: 'key' },
    { sign: 'ACh contracts gut smooth muscle but relaxes some vascular beds', mechanism: 'The receptor on the target cell decides the sign of the response', significance: 'supportive' },
  ],

  investigations: [
    { clue: 'Pacemaker cell generating gastrointestinal slow waves', meaning: 'Interstitial cell of Cajal' },
    { clue: 'Swelling along an autonomic axon that releases transmitter without an end plate', meaning: 'Varicosity of a diffuse junction' },
    { clue: 'Ion carrying the upstroke of the smooth muscle action potential', meaning: 'Calcium, through L-type channels' },
    { clue: 'Second messenger releasing SR Ca²⁺ with no change in membrane potential', meaning: 'IP₃ (inositol trisphosphate)' },
    { clue: 'Endothelial mediator relaxing vascular smooth muscle through cGMP', meaning: 'Nitric oxide' },
  ],

  treatment: [
    { logic: 'Why it matters', detail: 'This is the pharmacological heart of the chapter. **Ca²⁺-channel blockers** work on smooth and cardiac muscle yet spare skeletal muscle, precisely because skeletal activator Ca²⁺ never crosses the sarcolemma ([[ghp-excitation-contraction-coupling-skeletal]]). **Nitrates and sildenafil** exploit the nitric oxide–cGMP route; **beta-2 agonists** relax airway and uterine muscle through cAMP. Slow waves explain gastric and intestinal rhythmicity: [[gi-smooth-muscle-electrical-activity]]. The contractile machinery being driven: [[ghp-smooth-muscle-contraction]].' },
    { logic: 'Why the resting potential behaves so differently', detail: 'A resting potential of only −50 to −60 mV sits near threshold, so stretch, a hormone, or a slow-wave crest can fire spikes without any nerve traffic — the basis of visceral autorhythmicity and arteriolar autoregulation. Ionic determinants of the baseline: [[ghp-resting-membrane-potential]]. Compare the pacemaker logic of cardiac tissue: [[cardiac-action-potential]].' },
  ],

  mnemonics: [
    { hook: 'Slow waves set the RHYTHM; spikes set the FORCE', expansion: ['A slow wave by itself contracts nothing', 'Only crests that reach threshold generate spikes, and only spikes contract'] },
    { hook: 'Smooth muscle calcium is mostly OUTSIDE; skeletal calcium is all INSIDE', expansion: ['That is why calcium channel blockers relax vessels and gut but not the biceps', 'It is also why smooth muscle starts and stops so slowly'] },
  ],

  traps: [
    {
      questionCategory: 'What a slow wave actually does',
      wrongInstinct: 'Each slow wave is an action potential, and every slow wave produces a contraction',
      rightAnswer: 'Slow waves are subthreshold oscillations of the resting potential; contraction needs spike potentials riding on a crest that reaches threshold',
      why: 'The slow wave sets only the maximum possible rate — neural and hormonal input decide which crests actually spike.',
    },
    {
      questionCategory: 'Source of activator Ca²⁺ across the three muscle types',
      wrongInstinct: 'Blocking L-type Ca²⁺ channels should weaken skeletal, cardiac and smooth muscle alike',
      rightAnswer: 'It weakens smooth and cardiac muscle but leaves skeletal muscle essentially untouched',
      why: 'Skeletal muscle uses its L-type channel (the DHPR) only as a voltage sensor and draws all its Ca²⁺ from the SR, so nothing needs to flow through it.',
    },
  ],

  quiz: [
    {
      id: 'q1',
      stem: 'Intracellular recording from intestinal smooth muscle shows regular oscillations of membrane potential between −60 and −50 mV at 12 per minute, with no contraction. After ACh is added, bursts of spikes appear on the peaks and the segment contracts 12 times per minute. The oscillations are:',
      options: [
        { id: 'a', text: 'Action potentials that were simply too small to be detected' },
        { id: 'b', text: 'Slow waves from interstitial cells of Cajal, which contract nothing until their crests reach threshold' },
        { id: 'c', text: 'End-plate potentials generated at diffuse junctions' },
        { id: 'd', text: 'Latch bridge cycling in the longitudinal muscle layer' },
      ],
      answerId: 'b',
      explanation: 'Slow waves are rhythmic subthreshold oscillations of the resting potential set by interstitial cells of Cajal; on their own they never open enough Ca²⁺ channels to contract the muscle. ACh depolarises the baseline so the crests cross threshold, spikes fire, and contraction now appears at the unchanged slow-wave frequency — the rhythm was always there, only the force is new.',
      tests: 'mechanism',
    },
    {
      id: 'q2',
      stem: 'Verapamil markedly reduces arteriolar smooth muscle tone but has essentially no effect on the strength of skeletal muscle contraction. The explanation is:',
      options: [
        { id: 'a', text: 'Skeletal muscle expresses no L-type Ca²⁺ channels' },
        { id: 'b', text: 'The skeletal L-type channel acts only as a voltage sensor, and all activator Ca²⁺ comes from the SR' },
        { id: 'c', text: 'Skeletal muscle uses calmodulin rather than troponin to trigger contraction' },
        { id: 'd', text: 'Verapamil cannot cross the skeletal muscle sarcolemma' },
      ],
      answerId: 'b',
      explanation: 'Skeletal muscle does express the L-type channel — it is the DHPR — but uses it mechanically as a voltage sensor, with no Ca²⁺ needing to flow through it. Smooth muscle depends on Ca²⁺ entering from the extracellular fluid, so blocking entry removes tone. Option c reverses the two systems: it is smooth muscle that uses calmodulin.',
      tests: 'treatment',
    },
    {
      id: 'q3',
      stem: 'Vasopressin constricts a vascular smooth muscle strip whose membrane potential is held constant under voltage clamp, with no action potentials occurring. The most likely mechanism is:',
      options: [
        { id: 'a', text: 'Opening of voltage-gated Na⁺ channels' },
        { id: 'b', text: 'Receptor-driven IP₃ production releasing Ca²⁺ from the sarcoplasmic reticulum' },
        { id: 'c', text: 'A rise in cAMP that activates myosin light chain kinase' },
        { id: 'd', text: 'Direct binding of vasopressin to troponin C' },
      ],
      answerId: 'b',
      explanation: 'Hormonal control of smooth muscle needs no change in membrane potential at all: receptor occupancy generates IP₃, which releases stored Ca²⁺ and activates the calmodulin-MLCK pathway. Voltage-gated channels are irrelevant under clamp, cAMP characteristically causes relaxation in smooth muscle rather than contraction, and smooth muscle contains no troponin.',
      tests: 'mechanism',
    },
  ],
};

export default ghpSmoothMuscleRegulation;
