import type { Lecture } from '../../lib/types';

export const ghpDietaryBalancesEnergyRequirement: Lecture = {
  id: 'ghp-dietary-balances-energy-requirement',
  title: 'Dietary Balances & Energy Requirements',
  system: 'gi',
  source: 'Ch 71 — Dietary Balances; Feeding, Obesity & Starvation; Vitamins & Minerals',
  updated: '2026-09-14',
  tags: [
    { kind: 'system', label: 'GI' },
    { kind: 'lecture', label: 'Ch 71 Dietary Balances' },
    { kind: 'mechanism', label: 'Intake minus expenditure equals change in stores' },
    { kind: 'exam', label: '4/9/4 and 7 kcal/g · SDA highest for protein · 6.25 g protein per g N' },
  ],

  highYield: [
    '**Energy balance is an equation before it is a lifestyle, and the arithmetic is the whole argument.** Intake minus expenditure equals the change in stores, and because **adipose tissue banks roughly 7700 kcal per kilogram**, the daily error term is trivially small beside the daily turnover. Take a sedentary adult expending **2000 kcal/day** who runs a **1% surplus — 20 kcal, half a biscuit**: that is 7300 kcal a year and close to **1 kg of fat**, and a decade of it is a 10 kg weight gain that no single meal can be blamed for. The point examiners are after is that **weight drift is generated by errors far below the resolution of anything a patient can measure or report**, which is why food diaries mislead and why the balance has to be held automatically rather than deliberately.',
    '**Physiological fuel values are not what the calorimeter measures, and the gap between them is the exam point.** Burn the macronutrients to completion in a bomb and you recover about **4.1 kcal/g for carbohydrate, 9.3 for fat and 5.65 for protein**. The body books **4, 9 and 4** — the **Atwater values** — plus about **7 kcal/g for alcohol**. Two deductions explain the difference. **Absorption is incomplete** (roughly 98% of carbohydrate, 95% of fat, 92% of protein), and, decisively for protein, **its nitrogen is never oxidised at all**: the amino groups leave the body as **urea**, and urea is itself combustible, so that chemical energy is carried out in the urine. Protein therefore loses about a fifth of its calorimetric value before malabsorption is even counted.',
    '**Eating costs energy, and it costs most for protein — specific dynamic action is a real line in the budget, not a rounding error.** Total daily expenditure divides into **basal metabolic rate (about 60–70%)**, **physical activity (20–30%)** and the **thermic effect of food (around 10% of what is eaten)**. That last term is strongly macronutrient-specific: **protein 20–30%**, **carbohydrate 5–10%**, **fat 0–3%**. The reason is processing cost. **Deamination, urea synthesis and gluconeogenesis** are metabolically expensive, whereas dietary fat can be shunted into adipose stores almost structurally unchanged. Two isocaloric diets are therefore not metabolically isocaloric, and a high-protein diet quietly returns a slice of its own calories as heat.',
    '**The protein requirement is set by an obligatory loss you cannot switch off.** Put a healthy adult on a completely protein-free diet and **20–30 g of body protein is still degraded every day** and its nitrogen excreted — the obligatory loss, the floor beneath everything else. Because dietary protein is used imperfectly, the requirement sits above that floor at **0.8 g/kg/day**, rising steeply in sepsis, burns, trauma and convalescence. The bookkeeping is **nitrogen balance**: protein is about **16% nitrogen**, so **1 g of urinary nitrogen represents 6.25 g of protein**. Intake above output means anabolism; **output above intake is the earliest objective laboratory sign that a patient is being underfed**, and it appears long before any anthropometric measure moves.',
    '**Quality beats quantity — a protein is worth only as much as its scarcest essential amino acid.** Nine amino acids cannot be synthesised at all (ten in growing children, where arginine becomes conditionally essential), and the body cannot store a surplus of any of them to cover a later shortfall. Egg and milk protein supply all of them in near-ideal proportion and so have a high **biological value**; maize is limiting in **lysine and tryptophan** and wheat in **lysine**, so a diet adequate in total protein grams can still be functionally deficient. The complementary idea is **protein sparing**: about **100–150 g of carbohydrate a day** suppresses gluconeogenesis from muscle and abolishes ketosis, so **giving enough energy is itself a protein-conserving intervention**. Feed the calories and you preserve the protein — see [[nutrition-energy-protein-malnutrition]].',
    '**"Calories in, calories out" is true as thermodynamics and incomplete as physiology, because each side of the equation moves the other.** The first law is not in dispute — energy is conserved, and there is no metabolic loophole that makes a surplus disappear. What is wrong is treating the two terms as independent quantities a patient simply chooses. **Underfeed, and expenditure falls further than the loss of tissue predicts** (adaptive thermogenesis, less spontaneous movement, reduced thyroid hormone conversion) while **orexigenic drive climbs**; overfeed, and part of the surplus is dissipated instead of stored. The equation has **negative feedback wired into both of its terms**, which is why the arithmetic reliably predicts the *direction* of change and never the magnitude of it in a real person. The controller doing that wiring is [[ghp-hypothalamic-feeding-regulation]].',
  ],

  mechanism: {
    title: 'Gross energy → digestible → physiological fuel value → BMR + activity + SDA → balance → change in stores',
    steps: [
      { id: 's1', label: 'Food carries gross energy: 4.1, 9.3 and 5.65 kcal/g for carbohydrate, fat and protein by calorimeter', emphasis: 'normal' },
      { id: 's2', label: 'Subtract what is never absorbed — about 2% of carbohydrate, 5% of fat, 8% of protein', emphasis: 'normal' },
      { id: 's3', label: 'Subtract the energy that leaves as urea: protein falls to about 4 kcal/g, giving Atwater 4/9/4 and 7 for alcohol', emphasis: 'key' },
      { id: 's4', label: 'Expenditure is BMR (60–70%) plus activity (20–30%) plus specific dynamic action (about 10%, highest for protein)', emphasis: 'key' },
      { id: 's5', label: 'Intake minus expenditure is stored, at roughly 7700 kcal per kilogram of adipose tissue', emphasis: 'key' },
      { id: 's6', label: 'Both terms are themselves regulated, so a deficit is met partly by falling expenditure rather than by tissue loss alone', emphasis: 'key' },
    ],
  },

  examFindings: [
    { sign: 'A patient gaining 1–2 kg a year whose food diary reports an intake exactly matching measured expenditure', mechanism: 'The responsible surplus is 20–40 kcal/day, below the resolution of any self-report — the diary is not evidence of balance', significance: 'key' },
    { sign: 'Urinary nitrogen of 16 g/day in a septic patient receiving 60 g of protein', mechanism: 'Output of 100 g protein-equivalent against 60 g in: negative nitrogen balance, the earliest objective marker of underfeeding', significance: 'key' },
    { sign: 'Measured resting expenditure 15% below the value predicted from body size after a 12 kg intentional weight loss', mechanism: 'Adaptive thermogenesis — expenditure falls further than the loss of lean mass accounts for, defending the earlier weight', significance: 'key' },
    { sign: 'A child on a maize-based diet with adequate total calories and adequate protein grams who still fails to grow', mechanism: 'Maize is limiting in lysine and tryptophan, and the whole protein is usable only up to its scarcest essential amino acid', significance: 'key' },
    { sign: 'Metabolic rate rising about 25% for hours after a protein meal but barely at all after an equicaloric fat meal', mechanism: 'Specific dynamic action — deamination, urea synthesis and gluconeogenesis are costly, while fat storage is nearly free', significance: 'supportive' },
    { sign: 'Progressive weight loss and micronutrient deficiency in an alcohol-dependent patient whose calorie count looks adequate', mechanism: 'Alcohol delivers about 7 kcal/g but no protein, vitamins or minerals, and displaces nutrient-bearing food from the diet', significance: 'supportive' },
  ],

  investigations: [
    { clue: 'Physiological fuel values in kcal per gram for carbohydrate, fat, protein and alcohol', meaning: '4, 9, 4 and about 7 — the Atwater values, already net of malabsorption and of urea loss' },
    { clue: 'Why the calorimeter credits protein with 5.65 kcal/g but the body with only about 4', meaning: 'Amino nitrogen is excreted as combustible urea rather than oxidised, and roughly 8% of protein is never absorbed' },
    { clue: 'Grams of dietary protein represented by 1 g of urinary nitrogen', meaning: '6.25 g — protein is about 16% nitrogen, the basis of every nitrogen balance calculation' },
    { clue: 'Protein still degraded each day on a completely protein-free diet', meaning: 'The obligatory loss, 20–30 g/day — the floor beneath the 0.8 g/kg/day requirement' },
    { clue: 'Macronutrient with the highest thermic effect, and its approximate size', meaning: 'Protein, at 20–30% of the calories ingested; fat is under 3%, so identical calories are not identical energy' },
    { clue: 'Energy equivalent of one kilogram of adipose tissue', meaning: 'About 7700 kcal — the number behind the 500 kcal/day rule, which holds only at the start' },
  ],

  treatment: [
    { logic: 'Why it matters', detail: 'Every nutritional prescription is this one equation solved for a different unknown. **Estimate expenditure, then decide which side you are moving.** In the critically ill you are covering an obligatory loss that has risen, so the target is **protein first (1.2–2.0 g/kg/day) with enough non-protein calories to stop that protein being burned as fuel** — protein given without energy is simply an expensive gluconeogenic substrate. In deliberate weight loss the deficit is real but **the arithmetic decays**: the patient gets smaller, BMR falls, the cost of moving falls, and adaptive thermogenesis subtracts more on top, so the predicted line and the actual curve separate within weeks. And whenever intake and weight change appear to contradict each other, **the error is almost always in the intake estimate, not in the first law**. Putting numbers on any of this: [[nutritional-assessment-support]].' },
    { logic: 'Where it is examined', detail: 'Three stems recur. **A nitrogen balance calculation** — convert protein to nitrogen by dividing by 6.25, compare with measured urinary nitrogen plus about 2–4 g of insensible and non-urea losses, and say whether the patient is anabolic or catabolic. **Why protein and fat with identical calorie counts are not metabolically equivalent** — specific dynamic action of 20–30% versus under 3%, and the answer must name the post-absorptive processing cost rather than the work of digestion. And **the arithmetic of slow weight gain**, where the correct answer is always a surplus in the tens of kcal per day rather than the hundreds. The same equation run backwards, to exhaustion, is [[ghp-starvation-vitamin-mineral-deficiency]].' },
  ],

  mnemonics: [
    {
      hook: 'Atwater 4-9-4, alcohol 7 — and protein alone pays a urea tax',
      expansion: [
        'Calorimeter values: 4.1 carbohydrate, 9.3 fat, 5.65 protein',
        'Subtract what is not absorbed: roughly 2%, 5% and 8%',
        'Subtract the nitrogen leaving as urea — only protein pays this second charge',
        'What survives is 4, 9, 4, and about 7 kcal/g for alcohol',
      ],
    },
    {
      hook: 'Nitrogen times 6.25 — nitrogen is the currency of protein bookkeeping',
      expansion: [
        'Protein is about 16% nitrogen, and 100 divided by 16 is 6.25',
        '1 g of urinary nitrogen equals 6.25 g of protein catabolised',
        'Intake above output is anabolism; output above intake means the patient is underfed',
        'The floor is the obligatory loss: 20–30 g/day even on no protein at all',
      ],
    },
  ],

  traps: [
    {
      questionCategory: 'What a 500 kcal daily deficit actually predicts',
      wrongInstinct: 'A steady half-kilogram a week indefinitely, because a kilogram of fat is about 7700 kcal',
      rightAnswer: 'Loss at roughly that rate at first, then deceleration to a plateau as expenditure falls with the patient',
      why: 'The deficit shrinks as the body does — less mass to maintain, less work to move it, and adaptive thermogenesis subtracting more again on top.',
    },
    {
      questionCategory: 'Why protein has the highest thermic effect',
      wrongInstinct: 'Protein is the hardest macronutrient to digest, so more energy is spent breaking it down in the gut',
      rightAnswer: 'The cost is post-absorptive — deamination, urea synthesis and gluconeogenesis in the liver',
      why: 'Specific dynamic action is metabolic processing, not luminal work; fat needs the most elaborate digestion of all and has almost no thermic effect.',
    },
  ],

  quiz: [
    {
      id: 'q1',
      stem: 'A 70 kg man three days after major surgery receives 50 g of protein daily. His 24-hour urinary nitrogen is 14 g, and insensible plus non-urea losses are estimated at 2 g. His nitrogen balance is best described as:',
      options: [
        { id: 'a', text: 'Positive by about 8 g of nitrogen a day, indicating an anabolic response to surgery' },
        { id: 'b', text: 'Negative by about 8 g of nitrogen a day, equivalent to roughly 50 g of body protein lost daily' },
        { id: 'c', text: 'In balance, since 50 g of protein is close to the 0.8 g/kg/day requirement' },
        { id: 'd', text: 'Negative by about 6 g of protein a day, within the obligatory loss and therefore not significant' },
      ],
      answerId: 'b',
      explanation: 'Nitrogen in is 50 divided by 6.25, which is 8 g. Nitrogen out is 14 plus 2, which is 16 g. The balance is minus 8 g of nitrogen, and multiplying back by 6.25 gives about 50 g of body protein catabolised each day. The 0.8 g/kg/day figure is a requirement for a healthy adult at rest and is irrelevant to a catabolic post-surgical patient, whose obligatory loss has risen well above baseline. Negative balance here is the earliest objective evidence of underfeeding, appearing well before weight or anthropometry change.',
      tests: 'investigation',
    },
    {
      id: 'q2',
      stem: 'Two volunteers are given 500 kcal supplements of identical calorie content, one as pure protein and one as pure fat. Compared with the fat supplement, the protein supplement will:',
      options: [
        { id: 'a', text: 'Deliver more usable energy, because protein has the higher gross calorimetric value per gram' },
        { id: 'b', text: 'Deliver less usable energy, because 20–30% is dissipated as heat in deamination, urea synthesis and gluconeogenesis' },
        { id: 'c', text: 'Deliver the same usable energy, since the first law of thermodynamics forbids any difference' },
        { id: 'd', text: 'Deliver less usable energy, because protein digestion in the lumen is mechanically more demanding' },
      ],
      answerId: 'b',
      explanation: 'Specific dynamic action is 20–30% for protein and under 3% for fat, so a fifth to a third of the protein calories leave as heat and never reach the stores. The first law is not violated: the energy is accounted for, simply as heat rather than as tissue. Option a inverts the calorimetry, since protein has the lower gross value of the two. Option d names the wrong mechanism, and it is the mechanism that is being tested — the cost is post-absorptive hepatic processing, not work done in the gut, which is exactly why fat, despite needing emulsification, micelles and chylomicron packaging, has almost no thermic effect at all.',
      tests: 'mechanism',
    },
    {
      id: 'q3',
      stem: 'A sedentary 45-year-old has gained 9 kg over the past 12 years with no change in habits he can identify. Assuming the gain is adipose tissue at about 7700 kcal/kg, the average daily energy surplus responsible is closest to:',
      options: [
        { id: 'a', text: 'About 15 kcal a day' },
        { id: 'b', text: 'About 150 kcal a day' },
        { id: 'c', text: 'About 500 kcal a day' },
        { id: 'd', text: 'About 1000 kcal a day' },
      ],
      answerId: 'a',
      explanation: 'Nine kilograms at 7700 kcal is about 69 000 kcal, spread over roughly 4380 days, which is close to 16 kcal a day — under 1% of a typical intake and far smaller than the error in any dietary history. This is the central arithmetic of the chapter: chronic weight change is produced by imbalances too small to perceive, report or measure, which is why the body cannot rely on conscious accounting and why intact hypothalamic regulation normally holds weight stable for decades without any attention at all.',
      tests: 'exam',
    },
  ],
};

export default ghpDietaryBalancesEnergyRequirement;
