import type { Lecture } from '../../lib/types';

export const ghpThyroidSynthesisStorageRelease: Lecture = {
  "id": "ghp-thyroid-synthesis-storage-release",
  "title": "Thyroid Hormone Synthesis, Storage & Release",
  "system": "endocrine",
  "source": "Ch 77 — Thyroid Metabolic Hormones",
  "updated": "2026-09-15",
  "tags": [
    {
      "kind": "system",
      "label": "Endocrine"
    },
    {
      "kind": "lecture",
      "label": "Ch 77 Thyroid Metabolic Hormones"
    },
    {
      "kind": "mechanism",
      "label": "An extracellular hormone depot explains every lag in thyroid disease"
    },
    {
      "kind": "exam",
      "label": "Wolff-Chaikoff and Jod-Basedow are the same load in different glands"
    }
  ],
  "highYield": [
    "**The thyroid is the only endocrine gland that stores its finished hormone extracellularly, and it stores two to three months of supply.** Follicular cells secrete thyroglobulin into a sealed colloid lumen and iodinate it there, so the product sits outside the cells as a large protein depot rather than in secretory granules waiting at the membrane. Three clinical facts fall straight out of that single architectural choice. **Hypothyroidism after gland destruction declares itself slowly**, because the depot must be drained before deficiency can show. **Starting or changing levothyroxine takes about six weeks to reach a new steady state** — five half-lives of a hormone whose plasma half-life is about seven days — so rechecking TSH at two weeks measures nothing but impatience. And **a destructive thyroiditis produces a transient thyrotoxic phase** as ruptured follicles spill preformed hormone: the gland is not making more, it is leaking what it made months ago. The axis patterns those phases generate are set out in [[hen1-hpt-axis-thyroid-patterns]].",
    "**Four steps in a fixed order, and every relevant drug and antibody maps onto exactly one of them.** **Trapping** — the basolateral sodium-iodide symporter carries two sodium ions with each iodide against a thirty- to forty-fold gradient, paid for indirectly by Na⁺-K⁺-ATPase; perchlorate and thiocyanate compete here, and pertechnetate is trapped but never organified, which is why a technetium scan images trapping alone. **Organification and coupling** — apical thyroid peroxidase, using hydrogen peroxide generated by DUOX2, oxidises iodide, iodinates tyrosyl residues on thyroglobulin to MIT and DIT, then couples DIT with DIT to make T4 and MIT with DIT to make T3, all while the residues remain tethered to the protein; thionamides inhibit this enzyme and anti-TPO antibodies flag the autoimmune gland. **Storage** as colloid. **Release** — TSH drives endocytosis of colloid and lysosomal proteolysis of thyroglobulin, and pharmacological iodide and lithium block this final step. That last contrast is worth holding: **agents that block release work within hours, agents that block synthesis must wait for the store to empty over weeks**. Leftover MIT and DIT are stripped by iodotyrosine deiodinase and the iodine is recycled internally.",
    "**T4 is a prohormone; T3 is the hormone; and the peripheral tissue, not the thyroid, decides how much hormone there is.** About **93% of thyroidal output is T4 and only 7% T3**, yet T3 binds the nuclear receptor with roughly ten times the affinity and carries almost all of the biological signal — and **some 80% of circulating T3 is generated outside the gland** by outer-ring deiodination through types 1 and 2. The identical molecule can instead be inactivated by inner-ring deiodination through type 3 to **reverse T3**, which is biologically silent. That switch is the whole point. Acute illness, starvation, trauma and major surgery push the balance towards type 3 and towards **low T3, raised reverse T3, a normal or low-normal TSH and a normal-to-low T4** — the **sick euthyroid pattern**. This is an energy-sparing adaptation of an intact axis, not thyroid disease, and the correct response is to defer testing until recovery rather than to prescribe hormone. Propylthiouracil alone among the thionamides also inhibits type 1 deiodination, which is precisely why it is preferred in thyroid storm. Transport and receptor mechanics are in [[hen1-thyroid-transport-conversion-action]].",
    "**The same iodine load causes hypothyroidism in one patient and thyrotoxicosis in another — the gland decides, not the dose.** A sudden high intracellular iodide concentration inhibits organification by thyroid peroxidase and shuts synthesis down: the **Wolff-Chaikoff effect**. In a healthy gland this is a self-limited safety brake, because within ten to fourteen days the follicular cell down-regulates its symporter, intracellular iodide falls and synthesis resumes — the **escape**. A gland that cannot escape stays shut down, so **an autoimmune-damaged, previously irradiated, or fetal and neonatal thyroid becomes hypothyroid instead**, which is the mechanism of amiodarone-induced hypothyroidism and of the neonatal risk from iodinated antiseptics and contrast. The mirror image is the **Jod-Basedow effect**: tissue that has escaped TSH control — a toxic adenoma, an autonomous multinodular goitre, latent Graves disease — is restrained only by substrate, so a large iodine load lets it synthesise without limit and the patient turns thyrotoxic. **One question resolves the pair: is this gland regulated and damaged, or is it autonomous?**",
    "**Binding proteins move total hormone without moving free hormone, and the patient is euthyroid throughout.** More than **99.5% of circulating T4 is protein-bound**, chiefly to thyroxine-binding globulin with transthyretin and albumin taking the remainder, leaving a free fraction near **0.03%** that alone reaches tissues and alone is sensed by the pituitary. Anything that raises TBG — **pregnancy, oestrogen therapy, the combined oral contraceptive** — raises **total T4** while free T4 and TSH return to normal after a brief transient adjustment. Anything that lowers TBG — **nephrotic syndrome, severe hepatic disease, androgens, high-dose glucocorticoid** — drops total T4 by the same bloodless route. Hence the rule: **measure free T4 alongside TSH and never chase a total T4**. Pregnancy then adds two effects that are genuinely real rather than analytical — **hCG weakly cross-stimulates the TSH receptor**, dipping TSH in the first trimester, and thyroxine requirement truly rises by **30 to 50%**, so a treated woman needs her dose raised as soon as the pregnancy is confirmed rather than at the first antenatal clinic.",
    "**Radioiodine uptake is a functional assay of this pathway, and it is the one test that separates making hormone from leaking it.** Because trapping is the first step and is TSH-driven, **uptake is high whenever the gland is actively synthesising** — diffusely in Graves disease, focally in a toxic adenoma with the surrounding tissue suppressed. **Uptake is near zero in a thyrotoxic patient who is not synthesising at all**: a destructive thyroiditis emptying its colloid depot, or ingested exogenous hormone. The distinction rewrites management, because a thionamide targets an enzyme that in thyroiditis is not working anyway, so it is useless there and the answer is a beta blocker plus time. The same logic reads congenital disease: an absent or ectopic gland traps nothing, whereas **dyshormonogenesis traps avidly and builds a goitre**, since the block lies downstream at peroxidase or at pendrin — the latter giving Pendred syndrome with sensorineural deafness. The serum marker follows the same architecture, since **thyroglobulin is high when hormone is leaking from a gland and undetectably low in factitious thyrotoxicosis**."
  ],
  "mechanism": {
    "title": "Trap iodide → organify and couple on thyroglobulin → store in colloid → proteolyse and release → deiodinate peripherally → feed back on TSH",
    "steps": [
      {
        "id": "s1",
        "label": "Sodium-iodide symporter traps iodide at the basolateral membrane, 30-40 fold against gradient, energised by Na⁺-K⁺-ATPase",
        "detail": "The step blocked by perchlorate and thiocyanate, and the step imaged by a radioiodine or pertechnetate scan",
        "emphasis": "key"
      },
      {
        "id": "s2",
        "label": "Thyroid peroxidase with DUOX2 peroxide oxidises iodide and organifies tyrosyls on thyroglobulin to MIT and DIT, then couples them to T4 and T3",
        "detail": "The target of thionamides and of anti-TPO antibodies; also the step inhibited acutely by a large iodide load",
        "emphasis": "key"
      },
      {
        "id": "s3",
        "label": "Iodinated thyroglobulin is stored extracellularly in colloid — a two to three month reserve held outside the cell",
        "emphasis": "key"
      },
      {
        "id": "s4",
        "label": "TSH triggers colloid endocytosis and lysosomal proteolysis, freeing T4 and T3; MIT and DIT are deiodinated and their iodine recycled",
        "detail": "The release step blocked within hours by pharmacological iodide and by lithium",
        "emphasis": "normal"
      },
      {
        "id": "s5",
        "label": "Peripheral deiodinases set the active signal — types 1 and 2 activate T4 to T3, type 3 diverts it to inert reverse T3",
        "emphasis": "key"
      },
      {
        "id": "s6",
        "label": "Free T3 and T4 feed back on pituitary thyrotrophs and hypothalamus, holding free hormone and not total hormone constant",
        "emphasis": "normal"
      }
    ],
    "branches": [
      {
        "fromId": "s3",
        "title": "Destructive thyroiditis — the store leaks",
        "steps": [
          {
            "id": "b1",
            "label": "Inflammation ruptures follicles and preformed hormone floods the circulation",
            "emphasis": "normal"
          },
          {
            "id": "b2",
            "label": "Thyrotoxic phase of 2 to 8 weeks with suppressed TSH but near-zero radioiodine uptake",
            "emphasis": "key"
          },
          {
            "id": "b3",
            "label": "Depot exhausted and follicles still damaged — a hypothyroid phase follows, usually recovering over months",
            "emphasis": "normal"
          },
          {
            "id": "b4",
            "label": "Treating the thyrotoxic phase with a thionamide is futile and can deepen the hypothyroid phase",
            "emphasis": "danger"
          }
        ]
      }
    ]
  },
  "examFindings": [
    {
      "sign": "A thyrotoxic patient with a tender gland, a raised ESR and a radioiodine uptake of under 3%",
      "mechanism": "Subacute thyroiditis is releasing stored hormone from ruptured follicles rather than synthesising it, so trapping is not merely normal but suppressed by the high circulating hormone",
      "significance": "key"
    },
    {
      "sign": "TSH still suppressed six weeks after starting a thionamide, while free T4 has fallen appropriately",
      "mechanism": "Thyrotroph recovery lags the fall in hormone by weeks to months, so TSH is the wrong variable to titrate against early — free T4 is",
      "significance": "key"
    },
    {
      "sign": "A patient on long-term amiodarone who becomes hypothyroid, in a region of iodine sufficiency and with positive anti-TPO antibodies",
      "mechanism": "Each 200 mg tablet delivers a vast iodine load; a gland with underlying autoimmune damage cannot execute the Wolff-Chaikoff escape and so stays organification-blocked",
      "significance": "key"
    },
    {
      "sign": "An elderly patient with a longstanding multinodular goitre who becomes thyrotoxic within weeks of iodinated CT contrast",
      "mechanism": "Jod-Basedow — autonomous nodular tissue is not restrained by TSH, so its only limit was iodide supply and the contrast removed it",
      "significance": "key"
    },
    {
      "sign": "A pregnant woman with a total T4 well above the non-pregnant range, a normal free T4 and no clinical features of thyrotoxicosis",
      "mechanism": "Oestrogen-driven sialylation slows TBG clearance and roughly doubles the carrier pool; total hormone rises to fill it while the free fraction, which is what the pituitary senses, is held constant",
      "significance": "key"
    },
    {
      "sign": "A patient in intensive care with T3 low, reverse T3 raised, T4 low-normal and TSH 0.4 mU/L",
      "mechanism": "Illness shifts deiodination from activating type 1 and 2 pathways towards inactivating type 3 — an adaptive reduction in tissue thyroid signalling, with an intact axis underneath",
      "significance": "supportive"
    }
  ],
  "investigations": [
    {
      "clue": "Why the thyroid alone among endocrine glands can be destroyed months before deficiency appears",
      "meaning": "It is the only gland storing hormone extracellularly, holding two to three months of supply as iodinated thyroglobulin in colloid"
    },
    {
      "clue": "Why TSH should not be rechecked until about six weeks after a levothyroxine dose change",
      "meaning": "Plasma half-life of T4 is about seven days, so five half-lives to a new steady state, with thyrotroph set-point recovery slower still"
    },
    {
      "clue": "The step blocked by perchlorate, and the step blocked by methimazole",
      "meaning": "Perchlorate competes at the sodium-iodide symporter and blocks trapping; methimazole inhibits thyroid peroxidase and blocks organification and coupling"
    },
    {
      "clue": "Why pharmacological iodide relieves thyroid storm within hours while a thionamide takes weeks",
      "meaning": "Iodide blocks proteolytic release of stored hormone immediately, whereas a thionamide only stops new synthesis and must wait for the colloid depot to drain"
    },
    {
      "clue": "Thyrotoxicosis with a near-zero radioiodine uptake — the two diagnoses and how to split them",
      "meaning": "Destructive thyroiditis versus exogenous hormone; serum thyroglobulin is raised in the first because the gland is leaking, and suppressed in factitious thyrotoxicosis because the gland is idle"
    },
    {
      "clue": "Why propylthiouracil rather than methimazole in thyroid storm",
      "meaning": "It adds inhibition of type 1 deiodinase, cutting peripheral conversion of T4 to active T3 on top of blocking synthesis"
    }
  ],
  "treatment": [
    {
      "logic": "Why it matters",
      "detail": "One structural fact carries this module: **the thyroid stores months of hormone outside its cells, so every thyroid process is separated from its biochemistry by a lag**. That is why deficiency creeps up, why dose changes are judged at six weeks and not at two, why a destructive thyroiditis passes through thyrotoxicosis on its way to hypothyroidism, and why blocking release and blocking synthesis are two different therapeutic speeds. The step-by-step synthetic chemistry, at the level the endocrine block examines it, is in [[hen1-thyroid-hormone-synthesis]]."
    },
    {
      "logic": "Where it is examined",
      "detail": "Four stems recur. **Wolff-Chaikoff versus Jod-Basedow** given the same iodine load, resolved by asking whether the gland is regulated and damaged or autonomous. **Sick euthyroid syndrome** presented as though it were central hypothyroidism, where the right move is to defer testing rather than treat. **A raised total T4 in pregnancy or on the oral contraceptive**, where the patient is euthyroid and the free hormone is untouched. And **thyrotoxicosis with low uptake**, where a thionamide is the seductive wrong answer. What the released hormone actually does to the body is taken up in [[ghp-thyroid-metabolic-actions]]."
    }
  ],
  "mnemonics": [
    {
      "hook": "Trap, Tack, Tuck, Take-out — then the tissue converts",
      "expansion": [
        "Trap: sodium-iodide symporter, blocked by perchlorate and thiocyanate",
        "Tack: thyroid peroxidase organifies tyrosyls to MIT and DIT, blocked by thionamides, targeted by anti-TPO",
        "Tuck: stored in colloid as thyroglobulin, two to three months of supply",
        "Take-out: TSH-driven endocytosis and proteolysis, blocked in hours by iodide and lithium",
        "Then deiodinases decide — outer ring to active T3, inner ring to inert reverse T3"
      ]
    },
    {
      "hook": "Damaged gland goes DOWN with iodine, autonomous gland goes UP",
      "expansion": [
        "Wolff-Chaikoff: iodide load blocks organification in every gland",
        "A healthy gland escapes in 10-14 days by down-regulating the symporter",
        "A damaged, irradiated, fetal or neonatal gland cannot escape and becomes hypothyroid",
        "Jod-Basedow: autonomous nodule ignores TSH, is limited only by iodide, and becomes thyrotoxic"
      ]
    }
  ],
  "traps": [
    {
      "questionCategory": "Thyrotoxicosis when the radioiodine uptake is near zero",
      "wrongInstinct": "Start a thionamide, because the patient is thyrotoxic and thionamides treat thyrotoxicosis",
      "rightAnswer": "Recognise a destructive thyroiditis leaking preformed hormone and treat symptomatically with a beta blocker while the depot empties",
      "why": "A thionamide inhibits peroxidase-driven synthesis, and in thyroiditis synthesis has already stopped — which is exactly why the uptake is zero."
    },
    {
      "questionCategory": "Abnormal thyroid function tests in the critically ill",
      "wrongInstinct": "A low T3 with a low-normal TSH means central hypothyroidism and warrants liothyronine or thyroxine",
      "rightAnswer": "Sick euthyroid syndrome — deiodination has shifted from activating to inactivating pathways, and the axis is intact",
      "why": "Reverse T3 is raised rather than low, which no form of true hypothyroidism produces, and replacement in this setting has never shown benefit."
    }
  ],
  "quiz": [
    {
      "id": "q1",
      "stem": "A 34-year-old woman develops palpitations and heat intolerance three weeks after a viral illness. Free T4 is elevated, TSH is suppressed, the gland is tender, and 24-hour radioiodine uptake is 1%. Which statement best explains the biochemical picture?",
      "options": [
        {
          "id": "a",
          "text": "Autoantibodies are stimulating the TSH receptor, driving trapping and synthesis"
        },
        {
          "id": "b",
          "text": "Inflammation has ruptured follicles, releasing hormone already stored in colloid, so release of stored hormone, rather than increased synthesis, dominates the thyrotoxicosis"
        },
        {
          "id": "c",
          "text": "Peripheral conversion of T4 to T3 has increased, raising free hormone without a thyroid source"
        },
        {
          "id": "d",
          "text": "A large iodine load has provoked unrestrained synthesis by autonomous nodular tissue"
        }
      ],
      "answerId": "b",
      "explanation": "The thyroid is unique in holding two to three months of finished hormone extracellularly in colloid. A destructive thyroiditis spills that depot, so free hormone rises while the follicular cell is neither trapping nor organifying — hence a radioiodine uptake close to zero, which is the discriminating result. Receptor-stimulating antibodies and Jod-Basedow both drive synthesis and would give a high uptake. Increased peripheral conversion cannot raise total free T4 because it consumes T4 rather than producing it.",
      "tests": "mechanism"
    },
    {
      "id": "q2",
      "stem": "A 70-year-old man with a longstanding multinodular goitre and a previously normal TSH undergoes contrast-enhanced CT. Six weeks later he is thyrotoxic. A second patient, who has Hashimoto thyroiditis on thyroxine, is started on amiodarone and becomes progressively more hypothyroid. The mechanistic difference is best stated as:",
      "options": [
        {
          "id": "a",
          "text": "The first received a larger absolute iodine dose than the second"
        },
        {
          "id": "b",
          "text": "The first has autonomous tissue limited only by iodide supply, while the second has a gland that cannot escape the Wolff-Chaikoff block"
        },
        {
          "id": "c",
          "text": "The first has increased thyroxine-binding globulin and the second decreased"
        },
        {
          "id": "d",
          "text": "The first has increased type 2 deiodinase activity and the second increased type 3 activity"
        }
      ],
      "answerId": "b",
      "explanation": "An iodide load transiently inhibits organification in any gland. A normal follicular cell escapes within ten to fourteen days by down-regulating its sodium-iodide symporter; an autoimmune-damaged, irradiated, fetal or neonatal gland cannot, and stays suppressed — Wolff-Chaikoff without escape. Autonomous nodular tissue has left TSH control entirely, so its output is substrate-limited and a large iodine load simply removes the limit, which is Jod-Basedow. Amiodarone actually delivers far more iodine than contrast, so dose is not the discriminator; binding-protein changes move total and not free hormone; and deiodinase shifts do not explain either syndrome.",
      "tests": "mechanism"
    },
    {
      "id": "q3",
      "stem": "A patient with Graves disease presents in thyroid storm. Propylthiouracil is given, followed one hour later by potassium iodide. The rationale for the ordering and for the choice of thionamide is that:",
      "options": [
        {
          "id": "a",
          "text": "Iodide given first would be organified into new hormone, and propylthiouracil additionally blocks peripheral T4 to T3 conversion"
        },
        {
          "id": "b",
          "text": "Iodide given first would displace hormone from thyroxine-binding globulin and raise the free fraction"
        },
        {
          "id": "c",
          "text": "Propylthiouracil blocks release of stored hormone, and iodide then prevents further synthesis"
        },
        {
          "id": "d",
          "text": "Propylthiouracil has a faster onset than methimazole on colloid proteolysis"
        }
      ],
      "answerId": "a",
      "explanation": "Iodide blocks proteolytic release of stored hormone within hours, which is why it is invaluable in storm, but it is also substrate: if organification is not already inhibited it can be assembled into new hormone and worsen the picture, so the peroxidase block is given first. Propylthiouracil is preferred in storm because, uniquely among the thionamides, it also inhibits type 1 deiodinase and therefore cuts conversion of T4 to the far more active T3. The two drugs act on different steps, not the same one, and neither acts through binding proteins.",
      "tests": "treatment"
    }
  ]
};

export default ghpThyroidSynthesisStorageRelease;
