import type { Lecture } from '../../lib/types';

export const ghpEpilepsySeizures: Lecture = {
  id: 'ghp-epilepsy-seizures',
  title: 'Epilepsy: Synchronous Discharge, Spread and the Postictal State',
  system: 'neuro',
  source: 'Ch 59 — States of Brain Activity — Sleep, Brain Waves, Epilepsy, Psychoses',
  updated: '2026-09-10',
  tags: [
    { kind: 'system', label: 'Neuroscience' },
    { kind: 'lecture', label: 'Ch 59 States of Brain Activity' },
    { kind: 'mechanism', label: 'Paroxysmal depolarising shift, loss of surround inhibition' },
    { kind: 'disease', label: 'Tonic-clonic · absence · focal' },
  ],

  highYield: [
    '**A seizure is not too much brain activity, it is too much brain activity happening at the same instant.** The cortex normally keeps excitation local by **feedback and feed-forward GABA inhibition**, so a discharging group of neurons is ringed by a zone of suppression. A seizure begins when the balance tips — **more recurrent glutamatergic excitation, less GABA restraint, or a shift in the ionic environment** — and a population of neurons enters the **paroxysmal depolarising shift**: a prolonged calcium-driven depolarisation carrying a high-frequency burst of action potentials, repeated in unison across thousands of cells. Because the EEG measures synchrony, this is exactly what makes the trace explode into **high-voltage spikes**: the electrical signature and the pathophysiology are the same fact seen from two sides.',
    '**The generalised tonic-clonic seizure is the whole cortex plus the thalamocortical system recruited at once, and the phases are readable straight off the EEG.** The **tonic phase**, about **10–20 seconds**, is continuous synchronous discharge producing sustained contraction of all muscle groups — the patient is **rigid and apnoeic, becoming cyanosed**, often with **lateral tongue biting and incontinence**, and this is when a cry may be forced through a closed larynx. The **clonic phase** follows for **1–3 minutes** as **inhibitory mechanisms begin to interrupt the discharge**, chopping it into rhythmic bursts and so producing the jerks, which **slow and grow coarser** as inhibition wins. What follows is the **postictal state**: neurons are depleted of transmitter and metabolically exhausted, adenosine has accumulated, and active inhibition dominates, giving **depressed consciousness for minutes to hours**, and after a focal-onset event a **transient focal weakness, Todd paresis**, lasting up to a day.',
    '**Absence seizures are the thalamocortical loop oscillating, which is why the EEG number is so specific.** The rhythm is a **generalised, symmetrical, 3 Hz spike-and-wave** discharge generated by reverberation between **thalamic relay neurons with T-type calcium channels** and the **GABAergic nucleus reticularis thalami**, with cortex driven along. Clinically that gives **3–30 seconds of behavioural arrest** with a blank stare and often eyelid fluttering, **no aura, no fall, no convulsion and — the discriminator — no postictal confusion**: the child stops mid-sentence and finishes the sentence. It is typically **provoked within three minutes of hyperventilation** in the clinic, occurs many times a day, and mostly remits by adolescence.',
    '**A focal seizure is a lesion talking, and it says where it lives.** Focal epilepsy arises from a discrete hyperexcitable region — **glial scar after trauma, birth injury or infarct, a tumour, a vascular malformation, a cortical dysplasia, or mesial temporal sclerosis** — and the interictal EEG shows **spikes or sharp waves confined to the leads over that focus**. Semiology maps onto function: a **motor focus in the precentral gyrus** gives twitching that **marches along the homunculus (the Jacksonian march)**; a **temporal focus** gives an **epigastric rising sensation, intense familiarity or unfamiliarity, fear, an olfactory aura, and automatisms such as lip smacking and fumbling with amnesia for the event**. **Awareness is retained while the discharge stays in one region, and lost when it recruits both hemispheres and the thalamus** — which is what secondary generalisation means.',
    '**Spread is a failure of containment, and it follows the wiring that is already there.** As the focus discharges, **extracellular potassium rises and local GABA inhibition fatigues**, so the surrounding suppression collapses; excitation then travels by the routes the cortex already uses — **short intracortical collaterals, long corticocortical association fibres, the corpus callosum to the mirror region of the opposite hemisphere, and the thalamus as a relay that broadcasts to the entire cortex**. That last route is the difference between a limited focal event and a convulsion. It also explains why every seizure has a **threshold that can be lowered from outside**: **sleep deprivation, alcohol withdrawal, hypoglycaemia, hyponatraemia, hypocalcaemia, fever in a young child, photic stimulation, hyperventilation, fatigue and non-adherence to medication** are the standard provokers, and a seizure explained entirely by one of them is a **provoked seizure, not epilepsy**.',
    '**There are only two levers in seizure control: raise the threshold, or block the road — and the drug classes sort cleanly into those two ideas.** **Use-dependent sodium channel blockade (phenytoin, carbamazepine, lamotrigine)** works because it binds the inactivated channel preferentially, so it suppresses **high-frequency repetitive firing while leaving ordinary traffic almost untouched** — a beautifully selective way of limiting spread. **Enhancing GABA-A transmission (benzodiazepines increase channel opening frequency, barbiturates prolong opening duration)** and raising GABA availability (valproate, vigabatrin, tiagabine) raise the threshold everywhere. **T-type calcium channel blockade (ethosuximide)** targets the one oscillation that generates absence. **Levetiracetam acts on the SV2A vesicle protein to damp transmitter release.** Two consequences follow: the mechanism must match the seizure type (**sodium channel blockers can make absence worse**), and where a single structural focus drives everything, **removing it surgically is treating the cause rather than the threshold**. Prolonged convulsive activity that does not self-terminate is **status epilepticus**, where the exhaustion mechanism has failed and the emergency is metabolic as much as electrical.',
  ],

  mechanism: {
    title: 'From one hyperexcitable focus to a generalised convulsion and back',
    steps: [
      { id: 's1', label: 'A neuron group loses the balance between recurrent glutamatergic excitation and GABA restraint' },
      { id: 's2', label: 'Paroxysmal depolarising shift: a long calcium-driven depolarisation carrying a burst of spikes', emphasis: 'key' },
      { id: 's3', label: 'Extracellular potassium rises, surround inhibition fatigues, neighbouring cortex is recruited', emphasis: 'key' },
      { id: 's4', label: 'Spread along association fibres and the corpus callosum, or through the thalamus to the whole cortex', emphasis: 'danger' },
      { id: 's5', label: 'With both hemispheres and the thalamocortical system recruited, awareness is lost and the EEG generalises', emphasis: 'danger' },
      { id: 's6', label: 'Inhibition, adenosine and metabolic exhaustion terminate the discharge — the postictal state', emphasis: 'key' },
    ],
  },

  examFindings: [
    { sign: 'Sudden rigidity with apnoea and cyanosis for about 15 seconds, then rhythmic jerking that slows and coarsens over 2 minutes, then deep unresponsiveness', mechanism: 'Tonic continuous discharge, then inhibition chopping it into clonic bursts, then postictal exhaustion', significance: 'key' },
    { sign: 'A bitten lateral border of the tongue and wet clothing after a collapse', mechanism: 'Sustained masseter contraction during the tonic phase with sphincter release — rare after a simple faint', significance: 'key' },
    { sign: 'An 8-year-old stops mid-sentence, stares and flutters the eyelids for 8 seconds, then continues the sentence with no confusion', mechanism: 'Absence: 3 Hz thalamocortical oscillation, brief enough to leave no metabolic debt and so no postictal state', significance: 'key' },
    { sign: 'Twitching begins in the right thumb, spreads to the hand, then the arm, then the face, with awareness preserved throughout', mechanism: 'Jacksonian march — the discharge recruiting successive parts of the motor homunculus in the precentral gyrus', significance: 'key' },
    { sign: 'A rising sensation in the stomach with a sense of intense familiarity, then lip smacking and fumbling, with no memory of the episode', mechanism: 'Focal seizure of mesial temporal origin, with automatisms and impaired awareness', significance: 'key' },
    { sign: 'Weakness of the right arm for several hours after a convulsion, resolving completely', mechanism: 'Todd paresis: profound postictal inhibition and metabolic depletion in the cortex that discharged', significance: 'supportive' },
  ],

  investigations: [
    { clue: 'Generalised, symmetrical 3 Hz spike-and-wave, provoked by three minutes of hyperventilation', meaning: 'Absence seizures — thalamocortical reverberation through T-type calcium channels' },
    { clue: 'Interictal spikes or sharp waves confined to one temporal lead', meaning: 'A localised epileptogenic focus; the lead tells you where to look on the MRI' },
    { clue: 'A completely normal interictal EEG', meaning: 'Does not exclude epilepsy — a sleep-deprived or prolonged recording raises the yield, and diagnosis remains clinical' },
    { clue: 'Sodium, glucose, calcium, and a history of alcohol withdrawal or missed doses', meaning: 'Separates a provoked seizure, which needs the provoker corrected, from epilepsy, which needs a threshold raised' },
    { clue: 'MRI showing hippocampal atrophy with increased signal, or a cortical dysplasia', meaning: 'A structural focus — the group in whom removing the focus can outperform any drug' },
    { clue: 'Transient lactic acidosis and a raised creatine kinase after the event', meaning: 'Consistent with sustained whole-body muscle contraction during a genuine convulsion' },
  ],

  treatment: [
    { logic: 'Two levers only: raise the threshold, or block the road', detail: 'Every antiseizure drug is one of those two ideas. Use-dependent sodium channel block (phenytoin, carbamazepine, lamotrigine) silences high-frequency repetitive firing and therefore limits spread while sparing normal traffic. GABA-A enhancement (benzodiazepines increase opening frequency, barbiturates prolong opening) and increased GABA availability (valproate, vigabatrin, tiagabine) lift the threshold globally. Ethosuximide blocks the T-type calcium current that generates the 3 Hz oscillation, which is why it works in absence and nowhere else. Levetiracetam damps release through SV2A. Match the mechanism to the seizure type, correct the provoker in parallel, and treat failure to self-terminate as status epilepticus. The classification framework these mechanisms are pinned to: [[fcp1-seizure-classification]]. The synaptic excitation and inhibition being rebalanced: [[ghp-synaptic-transmission]].' },
    { logic: 'Where it is examined', detail: 'The commonest stem is not which drug but is this a seizure at all. The discriminators worth memorising are the presence of a genuine postictal state, lateral tongue biting, duration beyond a minute, and a stereotyped semiology that maps onto one cortical region. A brief flurry of jerks during a faint, with immediate orientation afterwards, is convulsive syncope. The full differential and the mimics: [[fcp1-seizure-vs-mimics]]. Note also that the same EEG technique reads sleep stages, and that sleep deprivation is among the most reliable seizure provokers: [[ghp-sleep-stages-brain-waves]].' },
  ],

  mnemonics: [
    { hook: '3 Hz, 3 to 30 seconds, no aura, no postictal', expansion: ['Generalised symmetrical 3 Hz spike-and-wave defines absence', 'Brief enough that no metabolic debt accumulates, hence no confusion afterwards', 'Provoked by hyperventilation; treated by blocking the T-type calcium current'] },
    { hook: 'Raise the floor, or block the road', expansion: ['Raise the floor: GABA-A enhancement and increased GABA availability raise threshold everywhere', 'Block the road: use-dependent sodium channel block stops high-frequency firing from propagating', 'And if a single structural focus is the road, remove it'] },
  ],

  traps: [
    {
      questionCategory: 'Seizure versus syncope',
      wrongInstinct: 'The witness saw jerking, therefore it was a seizure',
      rightAnswer: 'Brief jerks during a faint with immediate orientation afterwards are convulsive syncope; the discriminator is a genuine postictal state, not the jerking',
      why: 'Postictal depression reflects metabolic exhaustion of cortex that discharged for minutes — a few seconds of cerebral hypoperfusion cannot produce it.',
    },
    {
      questionCategory: 'Matching drug mechanism to seizure type',
      wrongInstinct: 'A child with staring spells should start carbamazepine, since it is a standard antiseizure drug',
      rightAnswer: 'Absence needs T-type calcium channel block (ethosuximide, or valproate if convulsions coexist); sodium channel blockers can worsen it',
      why: 'The absence oscillation is a thalamocortical calcium rhythm, not high-frequency sodium-driven repetitive firing, so the sodium blocker misses the mechanism entirely.',
    },
  ],

  quiz: [
    {
      id: 'q1',
      stem: 'An 8-year-old has episodes of blank staring lasting about 10 seconds, many times a day, with no warning, no fall and no confusion afterwards. Three minutes of hyperventilation in clinic reproduces an episode, and the EEG during it shows generalised symmetrical 3 Hz spike-and-wave. The first-line drug for this pattern acts on which target?',
      options: [
        { id: 'a', text: 'Use-dependent blockade of voltage-gated sodium channels' },
        { id: 'b', text: 'T-type calcium channels in thalamic relay neurons' },
        { id: 'c', text: 'Increased frequency of GABA-A channel opening' },
        { id: 'd', text: 'The SV2A synaptic vesicle protein' },
      ],
      answerId: 'b',
      explanation: 'The 3 Hz spike-and-wave rhythm is generated by reverberation between thalamic relay neurons carrying T-type calcium currents and the GABAergic nucleus reticularis thalami, with the cortex driven along. Ethosuximide blocks that current and therefore abolishes the oscillation at its generator. Sodium channel blockers act on high-frequency repetitive firing, which is not the mechanism here, and carbamazepine and phenytoin can actually aggravate absence. Benzodiazepines and levetiracetam raise threshold broadly but are not the targeted answer for the 3 Hz rhythm.',
      tests: 'treatment',
    },
    {
      id: 'q2',
      stem: 'A 34-year-old with an old left frontal head injury develops twitching that starts in the right thumb, spreads over about a minute to the hand, arm and then the face, and then becomes a generalised convulsion with loss of awareness. What best explains the orderly progression before consciousness was lost?',
      options: [
        { id: 'a', text: 'Sequential recruitment of adjacent cortex along the motor homunculus of the precentral gyrus' },
        { id: 'b', text: 'Spread of the discharge up the corticospinal tract from cord to cortex' },
        { id: 'c', text: 'Progressive rise in serum potassium activating successively larger motor units' },
        { id: 'd', text: 'Simultaneous discharge of both hemispheres from the outset' },
      ],
      answerId: 'a',
      explanation: 'A Jacksonian march is the discharge invading neighbouring cortex through short intracortical connections as surround inhibition fails, and because the motor cortex is somatotopically mapped, that spatial spread appears as an orderly progression up the body. Awareness was preserved while the event stayed in one region and was lost only when recruitment reached both hemispheres and the thalamocortical system, which is secondary generalisation. Propagation is cortical and orthograde, not retrograde up a descending tract, and a truly generalised onset would have no march at all.',
      tests: 'mechanism',
    },
    {
      id: 'q3',
      stem: 'A patient is brought in after a convulsion. Which single feature most strongly supports a genuine generalised tonic-clonic seizure rather than a faint with a few jerks?',
      options: [
        { id: 'a', text: 'Pallor and sweating immediately before the collapse' },
        { id: 'b', text: 'Prolonged drowsiness and confusion for 30 minutes afterwards' },
        { id: 'c', text: 'A brief cry at the moment of collapse' },
        { id: 'd', text: 'Rapid recovery of full orientation within 15 seconds' },
      ],
      answerId: 'b',
      explanation: 'The postictal state is the fingerprint. Minutes of synchronous discharge deplete transmitter stores, exhaust neuronal metabolism and leave a wave of active inhibition and accumulated adenosine, so consciousness is depressed for minutes to hours afterwards, sometimes with focal Todd paresis. Several seconds of global hypoperfusion in a faint cannot generate that debt, so recovery is prompt. Pallor and sweating are the autonomic prodrome of syncope, a cry can occur in either, and rapid full orientation argues against a seizure.',
      tests: 'exam',
    },
  ],
};

export default ghpEpilepsySeizures;
