import type { Lecture } from '../../lib/types';

export const ghpPrimaryHaemostasisPlatelets: Lecture = {
  id: 'ghp-primary-haemostasis-platelets',
  title: 'Primary Haemostasis & the Platelet Plug',
  system: 'heme',
  source: 'Ch 36 — Hemostasis & Blood Coagulation',
  updated: '2026-09-09',
  tags: [
    { kind: 'system', label: 'Haematology' },
    { kind: 'lecture', label: 'Ch 36 Haemostasis & Coagulation' },
    { kind: 'mechanism', label: 'Adhesion, activation, aggregation' },
    { kind: 'exam', label: 'Mucocutaneous bleeding' },
  ],

  highYield: [
    '**Haemostasis is four overlapping events, and the first two buy time for the third.** Vascular constriction narrows the breach, the platelet plug seals it provisionally, coagulation locks it in fibrin, and fibrous organisation or lysis finishes the job. Spasm is myogenic, neural and chemical — platelet **thromboxane A2** and **serotonin** contribute — which is why a crushed vessel bleeds less than one cut cleanly by a scalpel.',
    '**The platelet is a pre-loaded fragment with no nucleus, so everything it does is already packaged.** Shed from megakaryocytes at **150–400 × 10⁹/L** with a lifespan of **8–10 days** and about **one third pooled in the spleen**, it carries actin and myosin for contraction, **dense granules** (ADP, ATP, serotonin, calcium), **alpha granules** (fibrinogen, von Willebrand factor, factor V, growth factors), and the enzymes to make thromboxane A2. Its membrane phospholipid becomes the catalytic surface for the cascade in [[ghp-coagulation-cascade]].',
    '**Adhesion is a shear problem, and von Willebrand factor is the answer to it.** Endothelial breach exposes subendothelial **collagen**; vWF unfurls under high shear and bridges that collagen to platelet **GpIb-IX-V**. Direct collagen binding through GpVI and integrin alpha-2-beta-1 suffices in slow-flowing veins, but in arterioles and the microcirculation only the vWF tether holds — which is exactly why von Willebrand disease bleeds from mucosal surfaces where shear is highest.',
    '**Activation converts a passive disc into an amplifying, catalytic cell.** The platelet throws out pseudopods, contracts its actin-myosin, and releases its granules; **ADP acts at P2Y12**, **thromboxane A2** is generated by COX-1, and **thrombin acts at PAR-1** as the most powerful agonist of all. Simultaneously **phosphatidylserine flips to the outer leaflet**, creating the negatively charged surface on which tenase and prothrombinase assemble. Each of these three amplification arms is a drug target, as set out in [[antiplatelets]].',
    '**Aggregation has one final common step: GpIIb/IIIa.** Activation changes the conformation of this integrin so that it binds **fibrinogen**, and a single fibrinogen molecule cross-bridges two adjacent platelets. Adhesion is therefore platelet-to-wall via GpIb, while aggregation is platelet-to-platelet via GpIIb/IIIa — the distinction that separates Bernard-Soulier syndrome (GpIb defect, giant platelets, low count) from Glanzmann thrombasthenia (GpIIb/IIIa defect, normal count and normal morphology).',
    '**Platelet-type bleeding is immediate, superficial and mucocutaneous, and the reason is anatomical.** Platelets plug the thousands of tiny endothelial gaps that open in capillaries every day, so when they are absent or defective, blood escapes at those points as **petechiae and purpura**, with epistaxis, gum bleeding, menorrhagia and immediate oozing after a dental extraction. Deep bleeds into joints and muscles belong to the coagulation phenotype — the split drilled in [[fcp1-bleeding-primary-vs-secondary]].',
  ],

  mechanism: {
    title: 'From endothelial breach to a sealed platelet plug',
    steps: [
      { id: 's1', label: 'Injury exposes subendothelial collagen and removes the prostacyclin and nitric oxide brake', emphasis: 'key' },
      { id: 's2', label: 'von Willebrand factor bridges collagen to GpIb, tethering platelets against high shear', emphasis: 'key' },
      { id: 's3', label: 'Platelets spread, contract and release ADP, thromboxane A2, serotonin and calcium', emphasis: 'key' },
      { id: 's4', label: 'Released mediators recruit more platelets and reinforce local vasoconstriction' },
      { id: 's5', label: 'GpIIb/IIIa switches to high affinity and binds fibrinogen, cross-bridging adjacent platelets', emphasis: 'key' },
      { id: 's6', label: 'Phosphatidylserine exposure supplies the surface for thrombin generation, which then stabilises the plug in fibrin' },
    ],
  },

  examFindings: [
    { sign: 'Petechiae over dependent areas and the buccal mucosa', mechanism: 'Capillary gaps normally sealed by platelets leak red cells under hydrostatic pressure', significance: 'key' },
    { sign: 'Immediate oozing from a dental socket that restarts after apparent haemostasis', mechanism: 'Failure to form the initial plug rather than failure to stabilise it', significance: 'key' },
    { sign: 'Epistaxis and menorrhagia as the dominant lifelong symptoms', mechanism: 'High-shear mucosal beds depend most on vWF-mediated adhesion', significance: 'key' },
    { sign: 'Absence of haemarthrosis despite heavy mucosal bleeding', mechanism: 'Fibrin generation is intact, so closed-space deep bleeds do not occur', significance: 'key' },
    { sign: 'Giant platelets on the film with a modestly low count', mechanism: 'Bernard-Soulier syndrome from a defective GpIb-IX-V receptor', significance: 'supportive' },
    { sign: 'Moderate thrombocytopenia with splenomegaly', mechanism: 'Expansion of the splenic pool that normally holds about a third of platelets', significance: 'supportive' },
  ],

  investigations: [
    { clue: 'Prolonged bleeding time or PFA closure time with normal PT and aPTT', meaning: 'A primary haemostatic defect — platelet number, platelet function, or von Willebrand disease' },
    { clue: 'Normal platelet count with abnormal aggregometry', meaning: 'A qualitative defect: aspirin, uraemia, Glanzmann thrombasthenia or a storage pool disorder' },
    { clue: 'Absent ristocetin-induced aggregation that corrects when normal plasma is added', meaning: 'von Willebrand disease — the missing element is in plasma, not on the platelet' },
    { clue: 'Absent ristocetin-induced aggregation that does not correct with normal plasma', meaning: 'Bernard-Soulier syndrome — the receptor itself is defective' },
    { clue: 'Platelet count below 10–20 × 10⁹/L', meaning: 'Threshold for spontaneous petechial and mucosal bleeding without trauma' },
    { clue: 'Normal bleeding time with a markedly prolonged aPTT', meaning: 'Points away from platelets and towards a coagulation factor deficiency' },
  ],

  treatment: [
    {
      logic: 'Let the bleeding phenotype choose the test panel',
      detail: 'A history of **immediate, superficial, mucocutaneous** bleeding with petechiae points to primary haemostasis, so the first-line panel is a **platelet count, film, and a platelet function or von Willebrand screen**. Delayed, deep bleeding into joints and muscle points instead at the cascade and asks for **PT and aPTT**. Ordering the wrong panel is the commonest reason a bleeding disorder is missed.',
    },
    {
      logic: 'Antiplatelet drugs are built against the three amplification arms',
      detail: 'Aspirin blocks **COX-1** and so thromboxane A2, clopidogrel and its relatives block the **P2Y12** ADP receptor, and abciximab and tirofiban block **GpIIb/IIIa** itself. Because aspirin acetylates COX-1 irreversibly in an anucleate cell, the effect lasts the platelet lifespan of about **8–10 days** and can only be reversed by transfusing new platelets.',
    },
  ],

  mnemonics: [
    { hook: 'Ib binds the wall, IIb/IIIa binds the platelet', expansion: ['GpIb → vWF → collagen = adhesion', 'GpIIb/IIIa → fibrinogen → next platelet = aggregation', 'Bernard-Soulier breaks the first, Glanzmann the second'] },
    { hook: 'Platelets bleed early and shallow, factors bleed late and deep', expansion: ['Primary: immediate, petechiae, mucosal, menorrhagia', 'Secondary: delayed rebleed, haemarthrosis, muscle haematoma'] },
  ],

  traps: [
    {
      questionCategory: 'A normal platelet count in a patient who clearly bleeds',
      wrongInstinct: 'A normal count rules out a platelet problem',
      rightAnswer: 'Function matters as much as number — aspirin, uraemia, Glanzmann and von Willebrand disease all give a normal count',
      why: 'The bleeding time or PFA closure time interrogates function, which the count cannot see',
    },
    {
      questionCategory: 'Interpreting an absent response to ristocetin',
      wrongInstinct: 'Failure of ristocetin-induced aggregation proves von Willebrand disease',
      rightAnswer: 'Bernard-Soulier syndrome fails the same test, because ristocetin tests the whole vWF-to-GpIb axis',
      why: 'Adding normal plasma corrects von Willebrand disease but not a defective receptor',
    },
  ],

  quiz: [
    {
      id: 'q1',
      stem: 'A patient with a lifelong history of epistaxis and menorrhagia has a normal platelet count, normal PT and normal morphology, but a prolonged PFA closure time. Which step of primary haemostasis is most likely to have failed?',
      options: [
        { id: 'a', text: 'Fibrin cross-linking by factor XIII' },
        { id: 'b', text: 'Adhesion of platelets to subendothelial collagen under high shear' },
        { id: 'c', text: 'Thrombin generation on the platelet phospholipid surface' },
        { id: 'd', text: 'Vitamin K dependent carboxylation of factor IX' },
      ],
      answerId: 'b',
      explanation: 'Mucosal beds are high-shear, and at high shear the only adequate tether is von Willebrand factor bridging collagen to GpIb. A defect there gives immediate mucocutaneous bleeding with a prolonged closure time despite a normal count and normal cascade tests. The other options are secondary haemostasis and would produce delayed, deep bleeding instead.',
      tests: 'mechanism',
    },
    {
      id: 'q2',
      stem: 'What distinguishes Glanzmann thrombasthenia from Bernard-Soulier syndrome on a blood film and a platelet count?',
      options: [
        { id: 'a', text: 'Glanzmann shows giant platelets and thrombocytopenia; Bernard-Soulier is normal on both' },
        { id: 'b', text: 'Glanzmann has a normal count and normal morphology; Bernard-Soulier shows giant platelets with a low count' },
        { id: 'c', text: 'Both show giant platelets, separated only by the PT' },
        { id: 'd', text: 'Both show a normal film, separated only by the aPTT' },
      ],
      answerId: 'b',
      explanation: 'Bernard-Soulier is a defect of the GpIb-IX-V complex, and that complex also contributes to platelet size regulation and survival, so the film shows giant platelets with a mild thrombocytopenia. Glanzmann is a defect of the GpIIb/IIIa integrin, so platelets are normal in number and appearance but cannot cross-bridge with fibrinogen and fail to aggregate to every agonist.',
      tests: 'disease',
    },
    {
      id: 'q3',
      stem: 'Why does aspirin taken once continue to impair platelet function for about a week?',
      options: [
        { id: 'a', text: 'It has a plasma half-life of several days' },
        { id: 'b', text: 'It irreversibly acetylates COX-1 in an anucleate cell that cannot synthesise new enzyme' },
        { id: 'c', text: 'It competitively blocks the P2Y12 receptor until receptor turnover' },
        { id: 'd', text: 'It depletes dense granule ADP stores that take a week to refill' },
      ],
      answerId: 'b',
      explanation: 'Aspirin acetylates the COX-1 active site irreversibly. A nucleated cell would simply transcribe more enzyme, but the platelet has discarded its nucleus, so the loss of thromboxane A2 generation persists for that platelet lifespan of 8–10 days. Recovery depends on new platelets entering the circulation, which is also why transfused platelets restore function immediately.',
      tests: 'treatment',
    },
  ],
};

export default ghpPrimaryHaemostasisPlatelets;
