import type { Lecture } from '../../lib/types';

export const ghpLengthTensionLoadVelocity: Lecture = {
  id: 'ghp-length-tension-load-velocity',
  title: 'Length–Tension & Force–Velocity Relationships',
  system: 'msk',
  source: 'Ch 6 — Contraction of Skeletal Muscle',
  updated: '2026-09-09',
  tags: [
    { kind: 'system', label: 'Musculoskeletal' },
    { kind: 'lecture', label: 'Ch 6 Skeletal Muscle Contraction' },
    { kind: 'mechanism', label: 'Filament overlap' },
    { kind: 'exam', label: 'Preload vs afterload' },
  ],

  highYield: [
    '**Active tension is a direct read-out of cross-bridge overlap.** Maximum active force occurs at a sarcomere length of **~2.0–2.2 µm**, where **every myosin head faces actin** and the thin filaments have not yet collided. **Stretch beyond 2.2 µm** and tension falls off **linearly** as overlap is lost, reaching **zero at ~3.65 µm** where the filaments no longer touch. **Shorten below 2.0 µm** and tension falls steeply because opposing thin filaments **overlap and interfere**, and by **~1.65 µm the Z lines abut the thick filaments** and compress them.',
    '**Total tension = active tension + passive tension.** **Passive tension is developed by a non-stimulated muscle when it is stretched**, generated by **titin, sarcolemma and connective tissue**, not by cross-bridges. It is near zero up to resting length and then **rises steeply**, so the measured total-tension curve climbs again at long lengths even as active tension is failing. **Subtract passive from total to get active** — this is the classic graph-reading task.',
    '**In the body, muscles are held near their optimum.** Normal resting length in situ sits at or just above the length of maximal overlap, so ordinary movement operates near peak force. This is why a muscle is weak at the extremes of a joint\'s range — the physiology of "you cannot generate power with a fully flexed elbow".',
    '**Force–velocity: velocity of shortening falls as load rises, along a hyperbolic curve.** At **zero load, velocity is maximal (Vmax)** — roughly **>4 muscle lengths per second** in a fast fibre. As the load grows, velocity falls, and at the load equal to **maximal isometric force the velocity is zero** (the muscle is fully loaded and cannot shorten). **Load and velocity trade off; power (force × velocity) peaks in the middle**, at about **one-third of maximal load**.',
    '**The mechanism behind it: a load opposes the power stroke.** A heavier load means more cross-bridges must be attached and bearing force at any instant, and each attached head spends **longer in its force-bearing state** before it can complete the stroke and detach — the load acts as **drag on the ratchet**. At Vmax with no load, heads cycle as fast as their ATPase allows, which is why **fibre-type ATPase rate sets Vmax**.',
    '**Preload vs afterload — get the definitions right and both curves follow.** **Preload = the load applied BEFORE contraction begins; it stretches the muscle and therefore SETS the initial sarcomere length → it acts through the LENGTH–TENSION curve.** **Afterload = the load the muscle must overcome AFTER contraction begins; it opposes shortening → it acts through the FORCE–VELOCITY curve.** Raise preload → more force; raise afterload → less shortening and slower shortening.',
    '**Clinical anchor:** the heart obeys the same two curves. **Preload = end-diastolic volume, giving the Frank–Starling relationship (the cardiac length–tension curve)**; **afterload = aortic pressure / systemic vascular resistance**, which reduces stroke volume and ejection velocity. **Isometric** contraction (tension rises, length fixed) corresponds to isovolumetric contraction; **isotonic** shortening corresponds to ejection.',
  ],

  mechanism: {
    title: 'Overlap sets force; load sets speed',
    steps: [
      { id: 's1', label: 'Sarcomere ~2.0–2.2 µm → maximal overlap → every head can engage', emphasis: 'key' },
      { id: 's2', label: 'Stretch past 2.2 µm → overlap falls linearly → zero active tension at ~3.65 µm', emphasis: 'key' },
      { id: 's3', label: 'Shorten below 2.0 µm → thin filaments interfere; Z line hits myosin at ~1.65 µm' },
      { id: 's4', label: 'Passive tension from titin/connective tissue adds on above resting length' },
      { id: 's5', label: 'Preload sets starting length → moves you along the length–tension curve', emphasis: 'key' },
      { id: 's6', label: 'Afterload opposes the power stroke → heads dwell longer attached → velocity falls', emphasis: 'key' },
      { id: 's7', label: 'Velocity is maximal at zero load and zero at maximal isometric force' },
    ],
  },

  examFindings: [
    { sign: 'Peak active tension at a sarcomere length of about 2.2 µm', mechanism: 'Optimal thick–thin filament overlap: maximal number of cycling cross-bridges', significance: 'key' },
    { sign: 'Active tension is zero when the sarcomere is stretched to 3.65 µm', mechanism: 'No overlap remains, so no cross-bridge can form', significance: 'key' },
    { sign: 'Total tension rises again at long lengths despite falling active tension', mechanism: 'Passive tension from titin and connective tissue is added to the active component', significance: 'key' },
    { sign: 'Velocity of shortening falls progressively as the lifted weight increases', mechanism: 'Load opposes the power stroke and prolongs the attached, force-bearing state', significance: 'key' },
    { sign: 'A muscle lifting its maximal isometric load does not shorten at all', mechanism: 'Velocity reaches zero where load equals maximal developed force', significance: 'key' },
    { sign: 'Weakness at the extremes of joint range', mechanism: 'Sarcomeres are pushed off the plateau of the length–tension curve', significance: 'supportive' },
    { sign: 'Stroke volume falls when aortic pressure is raised acutely', mechanism: 'Afterload acting through the cardiac force–velocity relationship', significance: 'supportive' },
  ],

  investigations: [
    { clue: 'Sarcomere length giving maximal active tension', meaning: 'About 2.0–2.2 µm, the plateau of optimal overlap' },
    { clue: 'Tension developed by an unstimulated but stretched muscle', meaning: 'Passive tension (titin and connective tissue)' },
    { clue: 'Curve obtained by subtracting passive from total tension', meaning: 'The active length–tension curve' },
    { clue: 'Load applied before contraction that sets initial fibre length', meaning: 'Preload — acts through the length–tension relationship' },
    { clue: 'Load the muscle must lift once contraction has begun', meaning: 'Afterload — acts through the force–velocity relationship' },
    { clue: 'Velocity of shortening when the load is zero', meaning: 'Vmax, set by the myosin ATPase rate of the fibre type' },
    { clue: 'Contraction in which tension rises but length is unchanged', meaning: 'Isometric contraction' },
  ],

  treatment: [
    { logic: 'Why it matters', detail: 'These two curves are the bridge from muscle physiology to haemodynamics: length–tension in cardiac muscle is the Frank–Starling law, and force–velocity is why afterload reduction improves stroke volume in heart failure. Get preload and afterload separated here and the cardiovascular unit becomes bookkeeping. The overlap that generates the force: [[ghp-sarcomere-sliding-filament]]. The cardiac version of the length–tension curve: [[ghp-frank-starling-mechanism]] and [[frank-starling-cardiac-function]]. Loading conditions applied to the intact circulation: [[hemodynamics-preload-afterload-cardiac-output]].' },
    { logic: 'Where it is examined', detail: 'Two reliable question shapes: identify a point on a length–tension graph and say why tension is low there, and predict what raising preload or afterload does to force and velocity. What determines the ATPase rate behind Vmax: [[ghp-muscle-energetics-fibre-types]].' },
  ],

  mnemonics: [
    { hook: 'PRE-load comes PRE-contraction and sets LENGTH; AFTER-load comes after and sets SPEED', expansion: ['Preload → length–tension curve', 'Afterload → force–velocity curve'] },
    { hook: 'Too short, too long, or just right — force is a Goldilocks curve peaking near 2.2 µm', expansion: ['Too long: no overlap', 'Too short: filaments collide, Z line jams'] },
    { hook: 'Heavy = slow, light = fast, nothing = Vmax', expansion: ['Velocity zero at maximal isometric load', 'Power peaks near one-third of maximal load'] },
  ],

  traps: [
    {
      questionCategory: 'Reading the length–tension graph',
      wrongInstinct: 'Tension keeps rising as the muscle is stretched, because stretching a spring stores more force',
      rightAnswer: 'ACTIVE tension peaks at optimal overlap and then falls to zero; only the PASSIVE component keeps rising with stretch',
      why: 'The rising limb at long lengths on a total-tension curve is elastic recoil from titin and connective tissue, not cross-bridge force.',
    },
    {
      questionCategory: 'Distinguishing preload from afterload',
      wrongInstinct: 'Increasing the weight a muscle must lift will increase the force it develops, because it is stretched more',
      rightAnswer: 'A weight the muscle must lift after contraction begins is AFTERLOAD; it reduces shortening velocity and extent, it does not set initial length',
      why: 'Only load applied before contraction stretches the resting muscle and moves it along the length–tension curve.',
    },
    {
      questionCategory: 'Why short sarcomeres are weak',
      wrongInstinct: 'At short lengths there is more overlap, so tension should be greater',
      rightAnswer: 'Below about 2.0 µm thin filaments from opposite ends overlap and interfere, and the Z lines eventually collide with the thick filaments',
      why: 'Useful overlap means each head facing a distinct actin site; double overlap is obstruction, not extra binding.',
    },
  ],

  quiz: [
    {
      id: 'q1',
      stem: 'A skeletal muscle fibre is stretched so that its sarcomere length is 3.0 µm. Compared with a sarcomere length of 2.2 µm, the active tension developed on stimulation will be:',
      options: [
        { id: 'a', text: 'Greater, because stretching stores elastic energy in titin' },
        { id: 'b', text: 'Lower, because fewer myosin heads face actin filaments' },
        { id: 'c', text: 'Unchanged, because contraction is all-or-none' },
        { id: 'd', text: 'Zero, because overlap is abolished beyond 2.2 µm' },
      ],
      answerId: 'b',
      explanation: 'Active tension is proportional to the number of cross-bridges that can engage. Past the 2.2 µm plateau, overlap decreases linearly and active tension falls with it, reaching zero only at about 3.65 µm. The stored elastic energy in titin contributes passive, not active, tension, and a whole muscle grades its force rather than behaving all-or-none.',
      tests: 'mechanism',
    },
    {
      id: 'q2',
      stem: 'A muscle is stimulated to lift progressively heavier weights. As the load approaches the maximum the muscle can just barely hold, the velocity of shortening approaches:',
      options: [
        { id: 'a', text: 'Its maximum, because more cross-bridges are recruited' },
        { id: 'b', text: 'Zero, because the contraction becomes isometric' },
        { id: 'c', text: 'A constant value independent of load' },
        { id: 'd', text: 'Its maximum, because passive tension assists shortening' },
      ],
      answerId: 'b',
      explanation: 'The force–velocity relationship is inverse and hyperbolic: velocity is greatest at zero load and falls to zero when the load equals maximal isometric force, at which point tension rises without any change in length. The load acts as drag, keeping each cross-bridge in its force-bearing attached state longer before it can complete a stroke and detach.',
      tests: 'mechanism',
    },
    {
      id: 'q3',
      stem: 'Which pairing of loading condition with the relationship it acts through is correct?',
      options: [
        { id: 'a', text: 'Preload acts through the force–velocity relationship; afterload through length–tension' },
        { id: 'b', text: 'Preload acts through the length–tension relationship; afterload through force–velocity' },
        { id: 'c', text: 'Both act through the force–velocity relationship' },
        { id: 'd', text: 'Both act through the length–tension relationship' },
      ],
      answerId: 'b',
      explanation: 'Preload is applied before contraction and stretches the resting muscle, so it fixes initial sarcomere length and therefore the force available from filament overlap — the length–tension curve. Afterload is encountered only once contraction has begun and opposes shortening, so it determines how fast and how far the muscle shortens — the force–velocity curve. In the heart these become end-diastolic volume and aortic pressure respectively.',
      tests: 'exam',
    },
  ],
};

export default ghpLengthTensionLoadVelocity;
