import type { Lecture } from '../../lib/types';

export const innerEarHairCellHistology: Lecture = {
  id: 'inner-ear-hair-cell-histology',
  title: 'Inner Ear & Hair Cell Histology',
  system: 'neuro',
  source: 'L17 — Histology of the Ear',
  updated: '2026-07-02',
  tags: [
    { kind: 'system', label: 'Neuro' },
    { kind: 'lecture', label: 'L17 Ear Histology' },
    { kind: 'mechanism', label: 'Hair cells & endolymph' },
    { kind: 'exam', label: 'Organ of Corti; endocochlear potential' },
  ],

  highYield: [
    'The inner ear (bony labyrinth housing a membranous labyrinth) contains the COCHLEA (hearing) and the VESTIBULAR organs (balance), which share the same sensory cell: the HAIR CELL. Hair cells have an apical bundle of STEREOCILIA graded in height, and sit between two fluids — high-K⁺ ENDOLYMPH above and high-Na⁺ PERILYMPH below.',
    '**MECHANOTRANSDUCTION: deflection of the stereocilia bundle TOWARD the tallest stereocilium pulls "TIP LINKS" that open mechanically-gated cation channels → K⁺ (from endolymph) enters → DEPOLARISATION → Ca²⁺ entry → glutamate release onto the afferent nerve. Deflection the OTHER way closes channels → hyperpolarisation.** So a single bundle codes bidirectional movement.',
    '**The high-K⁺ ENDOLYMPH is generated by the STRIA VASCULARIS (in the cochlea) and creates a large positive ENDOCOCHLEAR POTENTIAL (~+80 mV) — the "battery" that drives K⁺ into hair cells and powers exquisite auditory sensitivity.** In the ORGAN OF CORTI, ONE row of INNER hair cells (the true sensory receptors, most afferents) and THREE rows of OUTER hair cells (electromotile amplifiers) sit on the basilar membrane under the tectorial membrane.',
    'In the VESTIBULAR organs the same hair cells sit in the cristae (semicircular canal ampullae, capped by the cupula) and maculae (utricle/saccule, weighted by otoliths in the otolithic membrane) — the histological basis of the physiology in [[vestibular-system-physiology]]. Hair cells do NOT regenerate in mammals, so their loss (noise, ototoxic aminoglycosides, ageing) causes permanent sensorineural deficit.',
    '**The take-home: hair cells (stereocilia + tip links) transduce mechanical deflection into K⁺-driven depolarisation, powered by the stria-vascularis endocochlear potential; organ of Corti = 1 inner (sensory) + 3 outer (amplifier) rows; vestibular cristae/maculae use the same cell; hair cells don\'t regenerate.** The functional consequences are in [[auditory-physiology-hearing]] and [[vestibular-system-physiology]].',
  ],

  mechanism: {
    title: 'Hair cell: stereocilia + tip links → K⁺ influx (from endolymph) → depolarise; endocochlear potential powers it',
    steps: [
      { id: 's1', label: 'Hair cell = shared receptor of cochlea + vestibular organs; apical stereocilia', emphasis: 'key' },
      { id: 's2', label: 'Deflection toward tallest → tip links open channels → K⁺ enters → depolarise', emphasis: 'key' },
      { id: 's3', label: 'Endolymph (high K⁺) from stria vascularis → endocochlear potential (~+80 mV)', emphasis: 'key' },
      { id: 's4', label: 'Organ of Corti: 1 inner (sensory) + 3 outer (amplifier) hair-cell rows', emphasis: 'key' },
      { id: 's5', label: 'Vestibular: cristae (cupula) + maculae (otoliths); hair cells DON\'T regenerate', emphasis: 'danger' },
    ],
  },

  examFindings: [
    { sign: 'Stereocilia deflection opening tip-link channels', mechanism: 'Mechanotransduction (K⁺ influx → depolarisation)', significance: 'key' },
    { sign: 'A large positive potential in the endolymph', mechanism: 'Endocochlear potential from the stria vascularis (high-K⁺ endolymph)', significance: 'key' },
    { sign: 'One row of inner + three rows of outer hair cells', mechanism: 'Organ of Corti (inner = sensory, outer = amplifier)', significance: 'key' },
    { sign: 'Permanent hearing loss after aminoglycosides or loud noise', mechanism: 'Hair cell death (no regeneration in mammals)', significance: 'key' },
    { sign: 'Hair cells capped by a cupula or an otolithic membrane', mechanism: 'Vestibular cristae (canals) and maculae (utricle/saccule)', significance: 'supportive' },
  ],

  investigations: [
    { clue: 'The shared sensory cell of hearing and balance', meaning: 'The hair cell' },
    { clue: 'The structures that open transduction channels on deflection', meaning: 'Tip links (between stereocilia)' },
    { clue: 'The source of the high-K⁺ endolymph/endocochlear potential', meaning: 'The stria vascularis' },
    { clue: 'The receptor organ for hearing on the basilar membrane', meaning: 'The organ of Corti' },
  ],

  treatment: [
    { logic: 'Why it matters', detail: 'Hair-cell histology explains sensorineural deafness — hair cells don\'t regenerate, so noise, ageing and ototoxic aminoglycosides cause permanent loss, and the stria vascularis/endocochlear potential is essential for sensitivity. This is the cellular basis of hearing ([[auditory-physiology-hearing]]) and balance ([[vestibular-system-physiology]]); the transduction uses ion gradients from EHP ([[resting-membrane-potential-nernst]]); clinical inner-ear disease is in HNS-2 ([[inner-ear-disorders]]).' },
  ],

  mnemonics: [
    { hook: 'Organ of Corti: "1 Inner (sensory), 3 Outer (amplifier)"', expansion: ['Inner = most afferents', 'Outer = electromotile'] },
    { hook: 'Hair cell "runs on K⁺ from endolymph" (stria vascularis battery)', expansion: ['Tip links open channels', 'No regeneration = permanent loss'] },
  ],

  traps: [
    {
      questionCategory: 'Ionic basis of hair cell transduction',
      wrongInstinct: 'Like most neurons, hair cells depolarise by letting Na⁺ in through their apical transduction channels',
      rightAnswer: 'Hair-cell apical transduction channels admit K⁺ — the surrounding ENDOLYMPH is uniquely HIGH in K⁺ (with a large positive endocochlear potential), so opening the tip-link channels drives K⁺ INTO the cell and depolarises it; this is the reverse of the usual Na⁺-based scheme and depends on the stria vascularis maintaining the endolymph',
      why: 'The unusual K⁺-in-from-endolymph mechanism (and the endocochlear potential powering it) explains why stria vascularis failure or endolymph disturbance (e.g. Ménière\'s) impairs hearing, unlike ordinary Na⁺-driven excitation.',
    },
  ],

  quiz: [
    {
      id: 'q1',
      stem: 'Deflection of a hair cell\'s stereocilia toward the tallest stereocilium causes depolarisation mainly by opening channels that admit:',
      options: [
        { id: 'a', text: 'Na⁺ from perilymph' },
        { id: 'b', text: 'K⁺ from the high-potassium endolymph' },
        { id: 'c', text: 'Cl⁻ out of the cell' },
        { id: 'd', text: 'Ca²⁺ from the tectorial membrane' },
      ],
      answerId: 'b',
      explanation: 'Hair-cell mechanotransduction channels, opened by tip-link tension when stereocilia deflect toward the tallest, admit K⁺ from the surrounding high-K⁺ endolymph (driven by the large positive endocochlear potential), depolarising the cell and triggering Ca²⁺-dependent glutamate release.',
      tests: 'mechanism',
    },
    {
      id: 'q2',
      stem: 'In the organ of Corti, the true auditory sensory receptors that carry most afferent information are the:',
      options: [
        { id: 'a', text: 'Three rows of outer hair cells' },
        { id: 'b', text: 'Single row of inner hair cells' },
        { id: 'c', text: 'Cells of the stria vascularis' },
        { id: 'd', text: 'Supporting (Deiters) cells' },
      ],
      answerId: 'b',
      explanation: 'The single row of inner hair cells are the principal sensory receptors, synapsing with most (~90–95%) of the afferent cochlear nerve fibres. The three rows of outer hair cells act mainly as the electromotile "cochlear amplifier" that sharpens sensitivity and tuning.',
      tests: 'exam',
    },
  ],

  figures: [],
};

export default innerEarHairCellHistology;
