import type { Lecture } from '../../lib/types';

// Original study notes aligned to Robbins Basic Pathology, 9th edition.
// Source and review scope: docs/robbins-coverage.md.
export const rbpAdrenalPathology: Lecture = {
  id: 'rbp-adrenal-pathology',
  title: 'Adrenal Pathology',
  system: 'endocrine',
  source: 'Ch 19 — Endocrine System',
  updated: '2026-09-22',
  tags: [
    { kind: 'system', label: 'Endocrine' },
    { kind: 'lecture', label: 'Ch 19 Endocrine System' },
    { kind: 'mechanism', label: 'Cortical zonation, ACTH drive and the morphology of the opposite gland' },
    { kind: 'disease', label: 'Cushing syndrome, Conn syndrome, CAH, Addison disease and phaeochromocytoma' },
  ],

  highYield: [
    '**The adrenal is two organs inside one capsule and the cortex is three organs stacked in order, so once you name the ZONE you have already named the hormone and the syndrome.** The cortex arises from coelomic mesoderm, the medulla from **neural crest**, and they never mix. Outermost, the **ZONA GLOMERULOSA** is about **15%** of the cortex, makes **ALDOSTERONE** through aldosterone synthase (CYP11B2), and is the one zone that **lacks 17-alpha-hydroxylase**, so it physically cannot make cortisol or androgens. It is also the one zone **not driven by ACTH** — its masters are **angiotensin II and potassium** — and that single fact is the root of half this page, because it means aldosterone survives when ACTH fails. Beneath it the **ZONA FASCICULATA** is about **75%**, arranged in radial cords of lipid-laden pale **clear cells**, and makes **CORTISOL** under ACTH. Innermost, the **ZONA RETICULARIS** is about **10%**, built of compact eosinophilic cells loaded with lipofuscin, and makes the weak androgens **DHEA and androstenedione**, also under ACTH. So the sequence is salt, then sugar, then sex, and each syndrome is a zone in excess: glomerulosa gives **Conn**, fasciculata gives **Cushing**, reticularis gives **virilisation**. The medulla is different tissue doing a different job: **chromaffin cells** secreting catecholamines, and it is the only chromaffin tissue in the body that makes mostly **ADRENALINE**, because the enzyme that methylates noradrenaline, **PNMT, is induced by cortisol**, and the medulla is bathed in cortical venous blood draining through the sinusoids before it leaves the gland ([[hen1-adrenal-cortex-histology-zones]]). The practical payoff is that the gross specimen reports the mechanism: **both glands small and atrophic means ACTH has been LOW; both glands diffusely enlarged means ACTH has been HIGH; one mass with an atrophic gland on the other side means the mass is making its own cortisol.** Normal combined adrenal weight is about **8 g**; ACTH-driven bilateral hyperplasia reaches **30 to 50 g**.',
    '**Cushing syndrome has four causes and you separate them with two numbers — the ACTH level, then the response to high-dose dexamethasone — because those two results between them localise the lesion to the drug cabinet, the pituitary, a tumour elsewhere, or the adrenal itself.** Start by confirming hypercortisolism at all (**late-night salivary cortisol**, **24-hour urinary free cortisol**, or failure to suppress on **1 mg overnight dexamethasone**), then measure **ACTH**. **EXOGENOUS GLUCOCORTICOID is by a wide margin the commonest cause of Cushing syndrome overall**, and it is the only one that gives **suppressed ACTH with BOTH adrenals ATROPHIC** — the negative feedback is being satisfied from outside the axis, so neither gland is being driven. **Adrenal adenoma or carcinoma** also suppresses ACTH, but the morphology is unmistakably different: a **bulky unilateral lesion with the CONTRALATERAL cortex atrophic**, because the tumour is autonomous and the axis it has shut down was still feeding the other gland. **CUSHING DISEASE**, a corticotroph pituitary microadenoma, accounts for about **70%** of endogenous cases, runs **ACTH raised but not extremely so**, gives **bilateral cortical hyperplasia**, and — the decisive point — **still SUPPRESSES on high-dose dexamethasone**, because the adenoma retains partial glucocorticoid feedback. **ECTOPIC ACTH**, classically from **small cell lung carcinoma** and from bronchial and thymic carcinoids, gives **ACTH markedly raised**, **bilateral hyperplasia**, and **NO suppression at any dexamethasone dose**, because the tumour has no feedback receptors worth speaking of. Non-tumorous corticotrophs exposed to any of this show **Crooke hyaline change**, a glassy perinuclear ring of cytokeratin — proof of hypercortisolaemia, silent about its source ([[adrenal-cushing-pathology]]).',
    '**Conn syndrome is hypertension with hypokalaemia, and the number that actually makes the diagnosis is the one that is LOW: the renin.** Aldosterone raises blood pressure and wastes potassium whatever its origin, so the aldosterone level alone cannot tell you where the problem is. Renin can. In **PRIMARY** hyperaldosteronism the adrenal is autonomous, the expanded plasma volume shuts the juxtaglomerular apparatus down, and **renin is SUPPRESSED** — so aldosterone is high and renin is low, and the **ALDOSTERONE-TO-RENIN RATIO** is the screening test, positive at roughly **above 30** with a plasma aldosterone above **15 ng/dL**. In **SECONDARY** hyperaldosteronism the kidney is the driver — renal artery stenosis, a renin-secreting tumour, diuretics, cirrhosis, heart failure — so **renin is HIGH and aldosterone follows it**, and the ratio stays normal. One measurement therefore splits a long differential in two. Confirm autonomy by showing that **aldosterone fails to suppress after a saline or fludrocortisone load**, then ask the surgical question with **adrenal vein sampling**, because the two primary lesions look alike biochemically and are treated completely differently: a **solitary aldosterone-producing adenoma** (about a third of cases; typically small, under 2 cm, bright yellow on section from stored lipid, composed of lipid-rich cells resembling fasciculata rather than glomerulosa, and characteristically showing **spironolactone bodies** — laminated eosinophilic cytoplasmic inclusions — after treatment) is cured by **unilateral adrenalectomy**, whereas **bilateral idiopathic hyperplasia** (about two-thirds) is not, and is treated with a **mineralocorticoid receptor antagonist**. Note what is absent: these patients are hypertensive but **NOT oedematous**, because after a few days of sodium retention the pressure natriuresis of **aldosterone escape**, helped by atrial natriuretic peptide, resets sodium balance while the potassium wasting continues unopposed.',
    '**Congenital adrenal hyperplasia is one idea applied three times: block an enzyme, and everything upstream of the block piles up and is forced down whichever pathway is still open, while everything downstream fails.** Work the commonest block, **21-HYDROXYLASE deficiency (CYP21A2)**, which is over **90%** of cases. The enzyme is needed for both **cortisol** and **aldosterone** but not for androgens. So cortisol falls, aldosterone falls, and the accumulating **17-hydroxyprogesterone** — which is the diagnostic assay, and it is grossly raised — is shunted into **androstenedione and testosterone**. The phenotype follows exactly: **virilisation** (ambiguous genitalia with clitoromegaly in a 46,XX newborn, precocious somatic and genital growth in a boy) plus **SALT WASTING** in the severe classic form, presenting at **day 7 to 14** with vomiting, dehydration, shock, **hyponatraemia, HYPERKALAEMIA and metabolic acidosis**. Meanwhile absent cortisol removes feedback, ACTH rises, and both glands become **diffusely hyperplastic with a brown cerebriform cut surface** from lipid-depleted compact cells. Now generate the other two from the same reasoning. **11-BETA-HYDROXYLASE deficiency** blocks one step later, so the pile-up is **11-deoxycorticosterone**, which is itself a potent mineralocorticoid: androgens are still high, so the patient still virilises, but instead of salt wasting there is **HYPERTENSION with hypokalaemia** — the same virilisation, the opposite salt phenotype. **17-ALPHA-HYDROXYLASE deficiency** blocks before the androgen branch is even reached, so cortisol and all sex steroids fail while mineralocorticoid precursors accumulate: **hypertension and hypokalaemia with NO virilisation at all**, giving a phenotypic female who fails to develop at puberty whatever the karyotype. The rule that generates all three: **androgens are high when the block is at or below 21-hydroxylase, and blood pressure is high when the block leaves a mineralocorticoid precursor accumulating above it.**',
    '**The cleanest discriminator in endocrine pathology is a pair: HYPERPIGMENTATION and HYPERKALAEMIA both belong to PRIMARY adrenal failure and neither belongs to secondary, and each has its own mechanism.** Pigment first. ACTH is cleaved from **pro-opiomelanocortin**, and the same precursor yields **melanocyte-stimulating hormone**; ACTH itself also binds the melanocortin-1 receptor directly. In **Addison disease** the adrenal is destroyed, cortisol cannot suppress the pituitary, POMC output soars, and the patient darkens where melanocytes are stimulated and where skin is traumatised — **palmar creases, buccal mucosa, gums, old scars, knuckles and the nipple areolae**. In **secondary** insufficiency the lesion is the pituitary or hypothalamus itself, so ACTH is LOW, and the patient is **pale, not pigmented**. Potassium second. **Aldosterone is regulated by renin and potassium, not by ACTH**, so it survives pituitary failure intact. Destroy the whole adrenal cortex and you lose it: salt wasting, volume depletion, **hyponatraemia, HYPERKALAEMIA, metabolic acidosis** and postural hypotension. Take away ACTH alone and the glomerulosa keeps working, so there is hyponatraemia (from unsuppressed vasopressin) but the **potassium is NORMAL**. State it as a rule: **pigmented and hyperkalaemic puts the lesion in the adrenal; pale and normokalaemic puts it above the adrenal.** Causes of primary failure are **autoimmune adrenalitis** in over 80% in developed countries (anti-21-hydroxylase antibodies, often within an autoimmune polyendocrine syndrome, giving a shrunken gland with a lymphocytic infiltrate that spares the medulla), then **tuberculosis and disseminated fungal infection** (a large caseating gland), **metastasis** (lung and breast, and it takes roughly **90%** destruction before symptoms appear, which is why adrenal metastases are common and Addison disease from them is rare), and **amyloid**. The acute form is **WATERHOUSE-FRIDERICHSEN syndrome**: fulminant meningococcal sepsis with endotoxin-driven disseminated intravascular coagulation infarcting both glands, turning them into bags of blood, alongside a purpuric rash and shock in a child — a rapidly fatal emergency ([[adrenal-insufficiency]]).',
    '**A mass in the adrenal medulla obeys the rule of tens in adults and the rule of neural crest in children, and the test you order is the metabolite, not the hormone.** **PHAEOCHROMOCYTOMA** arises from chromaffin cells and classically runs at **about 10% bilateral, 10% extra-adrenal, 10% paediatric and 10% malignant**, with the older teaching of 10% familial now firmly wrong: **a quarter to a third are germline**, through **RET (MEN2A and MEN2B), VHL, NF1** and the succinate dehydrogenase genes **SDHB, SDHC and SDHD**, so every patient warrants genetic testing and **SDHB** in particular flags metastatic risk ([[rbp-parathyroid-endocrine-neoplasia]]). Extra-adrenal tumours at the organ of Zuckerkandl and the bladder are called **paragangliomas**. Grossly the tumour is well circumscribed, and the classic exam detail is that the cut surface **turns brown-black in potassium dichromate**, which is where the word chromaffin comes from. Microscopically it is **ZELLBALLEN** — nests of polygonal chief cells wrapped by S100-positive sustentacular cells in a rich vascular network. The critical caution is that **neither pleomorphism nor capsular invasion predicts malignancy here; the ONLY criterion is metastasis to a site where chromaffin tissue does not normally occur.** Because release is **EPISODIC**, catecholamines can be entirely normal between paroxysms, but the tumour methylates its catecholamines **continuously and within its own cytoplasm**, so **plasma free or urinary fractionated METANEPHRINES are far more sensitive** and are the test — and they are why a normal noradrenaline level excludes nothing. The childhood counterpart is **NEUROBLASTOMA**, the commonest extracranial solid tumour of childhood, arising from neural crest sympathetic precursors in the adrenal medulla or the paravertebral chain. It is a small round blue cell tumour forming **HOMER-WRIGHT pseudorosettes** with a central tangle of neuropil, excretes **urinary HVA and VMA** in over 90%, and its prognosis is dominated by **N-MYC amplification**, which predicts aggressive disease whatever the stage. Its most striking property is that in infants under 18 months, and especially in stage 4S, it can **regress spontaneously or differentiate into a benign ganglioneuroma**. Finally, the **INCIDENTALOMA** asks exactly two questions and no others: **is it FUNCTIONAL** (overnight dexamethasone, plasma metanephrines, and an aldosterone-to-renin ratio if hypertensive) and **is it MALIGNANT** (size above **4 cm**, unenhanced CT attenuation above **10 Hounsfield units**, irregular margins and interval growth all argue for adrenocortical carcinoma, which is typically large, over **100 g**, with necrosis and haemorrhage, and frequently functional and virilising).',
  ],

  mechanism: {
    title: 'Localising hypercortisolism: the ACTH level, then the gland on the other side',
    steps: [
      { id: 's1', label: 'Confirm the cortisol is genuinely high and autonomous: late-night salivary cortisol, 24-hour urinary free cortisol, or failure to suppress on 1 mg overnight dexamethasone', detail: 'Cortisol is diurnal, so a single morning value proves nothing. Loss of the nocturnal trough is the earliest abnormality, which is why the late-night sample is the sensitive screen.', emphasis: 'normal' },
      { id: 's2', label: 'Measure ACTH: a SUPPRESSED ACTH means the cortisol is not coming through the pituitary at all, so the source is outside the axis', detail: 'This is the first fork and it is binary. A suppressed ACTH excludes both pituitary and ectopic disease in a single result, leaving only exogenous steroid and an autonomous adrenal lesion.', emphasis: 'key' },
      { id: 's3', label: 'ACTH-independent, so look at the adrenals: BOTH atrophic means exogenous glucocorticoid, the commonest cause of all; a unilateral mass with the CONTRALATERAL cortex atrophic means an adrenal adenoma or carcinoma', detail: 'The opposite gland is the specimen that answers the question. An autonomous tumour shuts the axis down, so the unaffected cortex loses its ACTH drive and atrophies while the tumour grows.', emphasis: 'key' },
      { id: 's4', label: 'ACTH RAISED instead: the drive is pituitary or ectopic, and both produce BILATERAL cortical hyperplasia, so morphology alone can no longer separate them', detail: 'Combined adrenal weight rises from about 8 g to 30 to 50 g in either case. This is exactly why a second, dynamic test is needed rather than more imaging.', emphasis: 'normal' },
      { id: 's5', label: 'High-dose dexamethasone plus CRH: a corticotroph adenoma retains partial feedback, so cortisol SUPPRESSES and ACTH rises to CRH — Cushing disease, confirmed by an ACTH gradient on inferior petrosal sinus sampling', detail: 'The adenoma is resistant to low-dose but not to high-dose suppression. Petrosal sinus sampling proves the central origin when imaging shows no microadenoma, which is common because most are under 5 mm.', emphasis: 'key' },
      { id: 's6', label: 'No suppression at any dose, ACTH markedly raised, rapid onset with weight loss, pigmentation and profound hypokalaemic metabolic alkalosis — ectopic ACTH, classically small cell lung carcinoma', detail: 'An ectopic tumour has no meaningful glucocorticoid feedback, so it cannot suppress. The illness outruns the classic Cushingoid habitus, so the patient is often wasted rather than obese.', emphasis: 'danger' },
    ],
    branches: [
      {
        fromId: 's6',
        title: 'Why the potassium collapses in ectopic ACTH and not in the others',
        steps: [
          { id: 'b1', label: 'Cortisol binds the mineralocorticoid receptor with the SAME affinity as aldosterone, and circulates at roughly a thousand times the concentration', emphasis: 'key' },
          { id: 'b2', label: 'Renal 11-beta-hydroxysteroid dehydrogenase type 2 normally converts cortisol to cortisone, which does not bind the receptor — that enzyme is what makes the receptor aldosterone-selective', emphasis: 'key' },
          { id: 'b3', label: 'Ectopic ACTH generates cortisol far beyond the capacity of the enzyme, which is saturated, so cortisol now reaches the receptor unconverted', emphasis: 'normal' },
          { id: 'b4', label: 'Apparent mineralocorticoid excess: sodium retention, hypertension, renal potassium wasting and a marked hypokalaemic metabolic alkalosis — the same lesion liquorice produces by inhibiting the enzyme directly', emphasis: 'danger' },
        ],
      },
    ],
  },

  examFindings: [
    { sign: 'Wide purple abdominal striae more than 1 cm across, thin skin that tears and bruises, and a patient who cannot rise from a chair without using the arms', mechanism: 'Cortisol is catabolic to protein: it suppresses fibroblast collagen synthesis so the dermis thins and the underlying vessels show through, which is why these striae are purple and broad rather than the pale narrow silvery lines of simple stretching. The same proteolysis wastes type II fibres in the girdle muscles, giving a proximal myopathy with preserved distal strength', significance: 'key' },
    { sign: 'Darkening of the palmar creases, buccal mucosa, gums and old surgical scars in a patient with fatigue, salt craving and postural hypotension', mechanism: 'Loss of cortisol feedback drives pro-opiomelanocortin transcription, and POMC cleavage yields melanocyte-stimulating hormone alongside ACTH while ACTH itself stimulates the melanocortin-1 receptor. Pigment therefore appears only when ACTH is HIGH, which places the lesion in the adrenal: secondary insufficiency has low ACTH and leaves the patient pale', significance: 'key' },
    { sign: 'Hypertension with a potassium of 2.9 mmol/L, muscle weakness and cramps, in a patient who is not oedematous and is on no diuretic', mechanism: 'Primary aldosteronism. Aldosterone drives distal sodium reabsorption in exchange for potassium and hydrogen, so pressure rises and potassium falls with a metabolic alkalosis. Oedema is absent because aldosterone escape, through pressure natriuresis and atrial natriuretic peptide, resets sodium balance after a few days while potassium wasting continues', significance: 'key' },
    { sign: 'A 46,XX newborn with clitoromegaly and fused labioscrotal folds, who at day 10 becomes vomiting, mottled and shocked', mechanism: 'Classic salt-wasting 21-hydroxylase deficiency. The block starves both cortisol and aldosterone while shunting accumulated 17-hydroxyprogesterone into androgens, so the fetus virilises in utero and then loses salt once the placenta is no longer handling electrolytes. The biochemistry is hyponatraemia with HYPERKALAEMIA and acidosis, which is the signature of absent aldosterone', significance: 'key' },
    { sign: 'Paroxysms lasting minutes of pounding headache, palpitations, drenching sweat and pallor, with blood pressure of 230/130 during the attack and normal readings between attacks', mechanism: 'Phaeochromocytoma releasing catecholamines episodically rather than continuously. Alpha-mediated vasoconstriction produces the pallor and the pressure surge while beta-mediated effects give the tachycardia, and the attack ends when the bolus is metabolised. The intermittency is exactly why a catecholamine level drawn between paroxysms is worthless and metanephrines are measured instead', significance: 'key' },
    { sign: 'A toddler with a firm abdominal mass that crosses the midline, periorbital ecchymoses with proptosis, and chaotic conjugate eye movements with myoclonic jerks', mechanism: 'Neuroblastoma. The mass is retroperitoneal and crosses the midline, unlike a Wilms tumour, which is intrarenal and does not. The raccoon eyes are metastatic deposits in the orbital bones bleeding into periorbital tissue, and the opsoclonus-myoclonus is a paraneoplastic autoimmune response to shared neural antigens, which paradoxically marks a tumour with a better prognosis', significance: 'key' },
  ],

  investigations: [
    { clue: 'Late-night salivary cortisol raised on two occasions, and serum cortisol 280 nmol/L the morning after 1 mg of dexamethasone at midnight', meaning: 'Hypercortisolism is established, and only then is it worth asking where it comes from. Cortisol normally falls to a nocturnal trough, so loss of that trough is the earliest and most sensitive abnormality, and a normal axis suppresses to below about 50 nmol/L after 1 mg of dexamethasone. Failure to suppress demonstrates autonomy. Order matters here: measuring ACTH before hypercortisolism is confirmed produces uninterpretable numbers' },
    { clue: 'ACTH undetectable, and CT shows both adrenal glands uniformly small and thin with no mass', meaning: 'Exogenous glucocorticoid, which is the commonest cause of Cushing syndrome of any kind and is diagnosed by drug history rather than by imaging. Steroid arriving from outside satisfies feedback, so ACTH is suppressed and both glands lose their trophic drive and atrophy together. Contrast the other ACTH-independent cause: an adrenal adenoma or carcinoma gives a bulky mass on one side with an atrophic cortex on the other, because the tumour is making the cortisol that is suppressing its neighbour' },
    { clue: 'ACTH 280 pg/mL, cortisol unsuppressed after 8 mg of dexamethasone, potassium 2.6 mmol/L with bicarbonate 36 mmol/L, in a 62-year-old smoker with a hilar mass', meaning: 'Ectopic ACTH, here from small cell lung carcinoma. A corticotroph adenoma keeps partial feedback and would suppress at high dose, so failure to suppress at any dose localises the source outside the pituitary, and inferior petrosal sinus sampling would show no central-to-peripheral gradient. The hypokalaemic alkalosis is the corroborating clue rather than a coincidence: cortisol at these concentrations saturates renal 11-beta-hydroxysteroid dehydrogenase type 2 and acts directly on the mineralocorticoid receptor' },
    { clue: 'Plasma aldosterone 38 ng/dL with plasma renin activity 0.2 ng/mL/hour, giving a ratio well above 30, and aldosterone fails to fall after a 2 litre saline infusion', meaning: 'Primary aldosteronism. The suppressed renin is what makes it primary: an autonomous adrenal expands plasma volume and shuts the juxtaglomerular apparatus down, whereas in secondary hyperaldosteronism the kidney is the driver and renin is HIGH. Saline confirms autonomy. The remaining question is surgical, and imaging cannot answer it reliably because small non-functioning nodules are common, so adrenal vein sampling separates a unilateral adenoma, which adrenalectomy cures, from bilateral idiopathic hyperplasia, which it does not' },
    { clue: 'Cortisol 90 nmol/L rising only to 210 nmol/L thirty minutes after 250 micrograms of synthetic ACTH, with ACTH 640 pg/mL, renin high and aldosterone low', meaning: 'Primary adrenal insufficiency. A healthy cortex reaches above about 500 nmol/L after stimulation, so failure to respond shows the gland itself cannot deliver, and the markedly raised ACTH proves the pituitary is driving it hard and being ignored. The high renin with low aldosterone confirms the glomerulosa has gone too, which is what generates the hyperkalaemia and salt wasting. In secondary insufficiency ACTH is low, and renin and aldosterone are normal because the glomerulosa answers to angiotensin II rather than to ACTH' },
    { clue: 'Plasma free metanephrine and normetanephrine both more than four times the upper reference limit, while plasma noradrenaline drawn during a symptom-free interval was normal', meaning: 'Phaeochromocytoma, and the discrepancy is the lesson rather than an inconsistency. Catecholamines are released in bursts, so a level between paroxysms samples a trough and can be entirely normal. The tumour, however, methylates catecholamines to metanephrines continuously within its own cytoplasm and leaks them steadily into the blood, so the metabolite is a time-averaged signal of tumour mass rather than a snapshot of secretion. Raised fourfold or more is essentially diagnostic; a minor rise is usually drugs or stress' },
  ],

  treatment: [
    {
      logic: 'Prove the cortisol, then localise it, and never forget what the other gland has been doing',
      detail: 'The sequence is fixed because each step is uninterpretable without the one before it. **First confirm hypercortisolism** with late-night salivary cortisol, 24-hour urinary free cortisol, or the **1 mg overnight dexamethasone** test. **Then measure ACTH**, which splits the problem in two. If ACTH is **SUPPRESSED**, review the drug chart before anything else, because **exogenous glucocorticoid is the commonest cause of Cushing syndrome overall**; image the adrenals only to find the unilateral tumour that would be the alternative. If ACTH is **RAISED**, use **high-dose dexamethasone with CRH**, and add **inferior petrosal sinus sampling** when MRI shows no adenoma, which is common since most corticotroph tumours are under 5 mm. Treatment then follows the localisation: **taper** a therapeutic steroid, never stop it abruptly, because the axis has been suppressed for months and needs time to recover; **transsphenoidal resection** for Cushing disease; resect or treat the source in ectopic disease, with **metyrapone or ketoconazole** to block steroidogenesis meanwhile; and **unilateral adrenalectomy** for an adrenal tumour. That last one carries the rule this page has been building toward: **the contralateral gland is ATROPHIC, so the patient must be given glucocorticoid cover through the operation and weaned over months**, because the remaining cortex cannot respond until ACTH has re-grown it.',
    },
    {
      logic: 'Alpha before beta in the medulla, and hydrocortisone before the result in the cortex',
      detail: 'Two sequencing rules, both of which kill when reversed. **In phaeochromocytoma, ALPHA blockade must precede BETA blockade**, conventionally **phenoxybenzamine or doxazosin for 10 to 14 days** with **liberal salt and fluid** to re-expand the chronically constricted plasma volume, and only then a beta blocker for residual tachycardia. The mechanism of the error matters: circulating adrenaline acts on **beta-2 receptors in skeletal muscle vessels to VASODILATE** at the same time as it constricts through alpha-1. Block beta first and that vasodilating brake is removed while alpha stimulation continues **UNOPPOSED**, so systemic resistance jumps and the patient can be thrown into a **hypertensive crisis, pulmonary oedema or myocardial infarction**. Intraoperative crises are treated with **phentolamine or sodium nitroprusside**, and hypotension after the tumour is clamped is expected, because the vasoconstrictor drive stops instantly. **In suspected adrenal crisis, give intravenous hydrocortisone and normal saline immediately and take the confirmatory samples around the treatment, not before it** — an untreated crisis is lethal within hours, and a single dose of hydrocortisone will not obscure a subsequent short Synacthen test if dexamethasone is used as the bridge. One further distinction on replacement: **primary** insufficiency also needs **fludrocortisone**, because aldosterone is lost with the cortex, while **secondary** insufficiency does not, since the glomerulosa is intact and answers angiotensin II.',
    },
  ],

  mnemonics: [
    {
      hook: 'Salt, sugar, sex, then adrenaline: the zone names the hormone and the hormone names the syndrome',
      expansion: [
        'Zona GLOMERULOSA makes aldosterone, is driven by angiotensin II and potassium and NOT by ACTH, and in excess gives Conn syndrome',
        'Zona FASCICULATA makes cortisol under ACTH, and in excess gives Cushing syndrome',
        'Zona RETICULARIS makes DHEA and androstenedione under ACTH, and in excess gives virilisation',
        'MEDULLA is neural crest, not cortex, and makes catecholamines: phaeochromocytoma in adults, neuroblastoma in children',
        'The glomerulosa lacks 17-alpha-hydroxylase, so it cannot make cortisol or androgens even if driven',
        'Because aldosterone is renin-driven, it survives pituitary failure and is lost only when the cortex itself is destroyed',
      ],
    },
    {
      hook: 'Two numbers localise every Cushing syndrome: the ACTH, then the high-dose suppression',
      expansion: [
        'ACTH SUPPRESSED with both adrenals atrophic: exogenous steroid, and this is the commonest cause of all',
        'ACTH SUPPRESSED with a unilateral mass and an atrophic opposite gland: adrenal adenoma or carcinoma',
        'ACTH RAISED and it SUPPRESSES on high-dose dexamethasone: pituitary corticotroph adenoma, which is Cushing disease',
        'ACTH MARKEDLY raised and it does NOT suppress: ectopic ACTH, classically small cell lung carcinoma',
        'Bilateral hyperplasia is shared by the last two, so morphology stops helping and the dynamic test takes over',
        'Prominent hypokalaemic alkalosis points to ectopic ACTH, because cortisol at that level saturates 11-beta-HSD2',
      ],
    },
  ],

  traps: [
    {
      questionCategory: 'Working up hypertension with hypokalaemia',
      wrongInstinct: 'Aldosterone is raised, so this is Conn syndrome and the patient should go for adrenalectomy',
      rightAnswer: 'Measure renin before anything else. Primary aldosteronism has aldosterone HIGH with renin SUPPRESSED and an aldosterone-to-renin ratio above about 30; secondary hyperaldosteronism has aldosterone high because renin is HIGH, and it is treated by finding the renal or circulatory cause',
      why: 'Aldosterone alone cannot say whether the adrenal is the driver or the passenger, whereas renin reports the direction of causation: an autonomous adrenal expands volume and shuts renin off, while a kidney that is under-perfused switches renin on and the adrenal simply obeys',
    },
    {
      questionCategory: 'Handling an adrenal mass found incidentally on imaging',
      wrongInstinct: 'The nature of the lesion is uncertain, so arrange a percutaneous biopsy to obtain tissue before deciding',
      rightAnswer: 'Answer the two questions biochemically first — is it functional, and is it malignant. Exclude phaeochromocytoma with plasma or urinary metanephrines, screen with overnight dexamethasone and, if hypertensive, an aldosterone-to-renin ratio; then use size above 4 cm, unenhanced attenuation above 10 Hounsfield units and interval growth to decide on resection',
      why: 'Needling an unsuspected phaeochromocytoma can precipitate a catecholamine crisis, and a needle cannot separate adrenocortical adenoma from carcinoma in any case, because that distinction rests on capsular and vascular invasion and mitotic count across the whole resected tumour',
    },
  ],

  quiz: [
    {
      id: 'q1',
      stem: 'A 62-year-old smoker has six weeks of proximal weakness, oedema and new diabetes, with marked pigmentation of the palmar creases. Potassium is 2.5 mmol/L and bicarbonate 37 mmol/L. Cortisol does not suppress after 1 mg or after 8 mg of dexamethasone, and ACTH is 310 pg/mL. CT shows bilaterally enlarged adrenals and a right hilar mass. Which single result most reliably localises the source of ACTH?',
      options: [
        { id: 'a', text: 'The bilateral adrenal enlargement, which occurs only in ectopic ACTH secretion' },
        { id: 'b', text: 'Failure of cortisol to suppress after high-dose dexamethasone, since a corticotroph adenoma retains partial glucocorticoid feedback and would suppress' },
        { id: 'c', text: 'The pigmentation, which is specific to an ectopic rather than a pituitary source of ACTH' },
        { id: 'd', text: 'The raised ACTH itself, which distinguishes ectopic secretion from Cushing disease' },
      ],
      answerId: 'b',
      explanation: 'The raised ACTH has already done half the work by excluding exogenous steroid and an adrenal tumour, both of which suppress ACTH, but it cannot separate a pituitary from an ectopic source because both raise it, which disposes of option d. Both also drive bilateral cortical hyperplasia, so the CT appearance is shared and option a fails for the same reason. Pigmentation follows any high ACTH and is therefore seen in Cushing disease as well, excluding option c. The discriminating result is the dynamic one: a corticotroph adenoma is a pituitary cell that has lost sensitivity to low-dose but not to high-dose glucocorticoid feedback, so it suppresses at 8 mg, whereas an ectopic tumour has no meaningful feedback apparatus and suppresses at no dose. The profound hypokalaemic alkalosis corroborates the answer, because cortisol at ectopic concentrations saturates renal 11-beta-hydroxysteroid dehydrogenase type 2 and reaches the mineralocorticoid receptor unconverted.',
      tests: 'investigation',
    },
    {
      id: 'q2',
      stem: 'Two patients both have fatigue, weight loss, hyponatraemia and a morning cortisol of 90 nmol/L. Patient A has darkened palmar creases and buccal mucosa and a potassium of 5.9 mmol/L. Patient B is pale, with a potassium of 4.1 mmol/L, and has a known pituitary macroadenoma. Which statement best explains the two findings that separate them?',
      options: [
        { id: 'a', text: 'Patient A is more severely cortisol deficient, and pigmentation and hyperkalaemia are both markers of the severity of that deficiency' },
        { id: 'b', text: 'POMC cleavage yields MSH alongside ACTH, so pigment appears only when ACTH is high; and aldosterone is renin-driven rather than ACTH-driven, so it is lost only when the cortex itself is destroyed' },
        { id: 'c', text: 'Patient B retains pigmentation and normal potassium because the posterior pituitary is intact' },
        { id: 'd', text: 'Hyperkalaemia in patient A reflects renal failure from volume depletion rather than any adrenal hormone deficiency' },
      ],
      answerId: 'b',
      explanation: 'These two signs are the cleanest discriminator in endocrine pathology because each reports a different limb of the axis. Pigment reports the ACTH level: pro-opiomelanocortin is cleaved to melanocyte-stimulating hormone as well as ACTH, and ACTH also stimulates the melanocortin-1 receptor directly, so a destroyed adrenal that cannot suppress the pituitary darkens the palmar creases, buccal mucosa, scars and knuckles, while a failing pituitary produces low ACTH and leaves the patient pale. Potassium reports the glomerulosa: aldosterone is regulated by angiotensin II and potassium rather than by ACTH, so it survives pituitary failure intact and the potassium stays normal, whereas destruction of the whole cortex removes it and gives salt wasting with hyperkalaemia and a metabolic acidosis. Both patients share hyponatraemia, so sodium does not discriminate, which is precisely why the pigment and the potassium are the pair worth memorising. Option a inverts the reasoning, since the cortisol values are the same.',
      tests: 'mechanism',
    },
    {
      id: 'q3',
      stem: 'A 44-year-old with episodic headache, sweating and palpitations has plasma free metanephrines five times the upper reference limit and a 4 cm right adrenal mass. The resting pulse is 108 and the house officer proposes starting propranolol today, with an alpha blocker added before surgery next month. What is the correct response?',
      options: [
        { id: 'a', text: 'Agree, because controlling the tachycardia first reduces myocardial oxygen demand and makes the patient safer' },
        { id: 'b', text: 'Refuse: alpha blockade must come first, because blocking beta-2-mediated vasodilatation while alpha-1 stimulation continues leaves vasoconstriction unopposed and can precipitate a hypertensive crisis' },
        { id: 'c', text: 'Agree, but only if a calcium channel blocker is given at the same time to offset the risk' },
        { id: 'd', text: 'Refuse, and proceed directly to surgery without any blockade, since preoperative drugs delay definitive treatment' },
      ],
      answerId: 'b',
      explanation: 'Adrenaline acts on two vascular receptor populations with opposite effects: alpha-1 receptors constrict most beds, while beta-2 receptors in skeletal muscle vasculature dilate and so act as a partial brake on the pressor response. A beta blocker given first removes the brake and leaves alpha-1 stimulation entirely unopposed, so systemic vascular resistance rises abruptly and the patient can be thrown into a hypertensive crisis, pulmonary oedema or myocardial infarction. The correct sequence is alpha blockade with phenoxybenzamine or doxazosin for 10 to 14 days, together with liberal salt and fluid to re-expand a plasma volume that chronic vasoconstriction has contracted, and only then a beta blocker for residual tachycardia. Option d is unsafe for the same reason in a different form, since handling the tumour at operation releases a catecholamine bolus into an unprotected circulation. Note also what this case demands afterwards: a quarter to a third of phaeochromocytomas are germline, so genetic testing for RET, VHL, NF1 and the succinate dehydrogenase genes follows.',
      tests: 'treatment',
    },
  ],
};

export default rbpAdrenalPathology;
