import type { Lecture } from '../../lib/types';

// Original study notes aligned to Robbins Basic Pathology, 9th edition.
// Source and review scope: docs/robbins-coverage.md.
export const rbpNeoplasiaNomenclatureBiology: Lecture = {
  id: 'rbp-neoplasia-nomenclature-biology',
  title: 'Neoplasia: Nomenclature & Tumour Biology',
  system: 'pathology',
  source: 'Ch 5 — Neoplasia',
  updated: '2026-09-16',
  tags: [
    { kind: 'system', label: 'Pathology' },
    { kind: 'lecture', label: 'Ch 5 Neoplasia' },
    { kind: 'mechanism', label: 'Nomenclature as a generator; the basement membrane as the line' },
    { kind: 'exam', label: 'Metastasis is the only absolutely reliable criterion of malignancy' },
  ],

  highYield: [
    "**Tumour names are generated by a rule, not memorised as a list: tissue of origin plus a suffix that encodes behaviour.** Benign tumours take -oma on the cell of origin — lipoma, leiomyoma, fibroma, chondroma, osteoma. Malignant tumours split by germ layer: epithelial malignancies are **carcinomas**, mesenchymal malignancies are **sarcomas**. So the pairs run adenoma and adenocarcinoma, lipoma and liposarcoma, leiomyoma and leiomyosarcoma, chondroma and chondrosarcoma. Architecture supplies the prefix: adeno- for gland formation, papillary for finger-like fronds, cystadeno- for glands that form cysts, squamous cell for keratinising epithelium. Learn the generator and you can name a tumour you have never seen. The full scheme is set out in [[neoplasia-nomenclature]].",
    "**The rule has a fixed exception list, and it is the exception list that gets examined.** Five malignancies keep a benign-sounding -oma: **lymphoma, melanoma, seminoma, mesothelioma and glioma**. Add the childhood -blastomas — neuroblastoma, retinoblastoma, hepatoblastoma, medulloblastoma — which are malignant by convention. Three further names mislead in a different way. A **teratoma** arises from germ cells and contains tissue from more than one germ layer; its behaviour follows site and age, not the name, so a mature cystic teratoma of the ovary is almost always benign while any teratoma in the postpubertal testis is handled as malignant. A **hamartoma** is a disorganised mass of tissue that belongs at that site — cartilage, fat and respiratory epithelium in a lung nodule. A **choristoma** is normal, well-organised tissue sitting in the wrong site, such as a pancreatic rest in the gastric wall. Hamartoma is at home and untidy; choristoma is tidy and abroad.",
    "**Benign and malignant are judged on four axes, and only one of them is decisive.** Differentiation (resemblance to the parent tissue, with anaplasia at the far end), growth rate, local invasion and metastasis. Anaplasia reads as pleomorphism, hyperchromatic nuclei with a nuclear-to-cytoplasmic ratio approaching 1:1 against a normal 1:4 to 1:6, coarsely clumped chromatin, prominent nucleoli, tumour giant cells, loss of polarity and atypical tripolar or quadripolar mitoses. But **metastasis is the only absolutely reliable criterion**, because the other three are spectra: a well-differentiated follicular carcinoma of thyroid can look almost normal, a benign uterine leiomyoma can grow quickly under oestrogen, and invasion is often uncallable on a small biopsy. Metastasis is 100 per cent specific and poorly sensitive — its presence proves malignancy, its absence proves nothing. Basal cell carcinoma of skin and glioblastoma invade relentlessly and virtually never metastasise, and both are malignant.",
    "**Dysplasia is disordered growth that is still reversible; carcinoma in situ is where the reversibility ends.** Dysplastic epithelium loses uniformity of cell size and shape and loses its architectural orientation, with mitoses appearing above the basal layer, and it is graded mild, moderate and severe. Remove the driver — clear the high-risk HPV, stop the reflux, stop the smoking — and mild to moderate dysplasia can regress, which is the entire justification for screening programmes. When the atypia occupies the full thickness of the epithelium while the basement membrane stays intact, the lesion is **carcinoma in situ**: cytologically malignant, biologically still trapped. Dysplasia is not an obligate precursor to cancer, and in most organs severe dysplasia and carcinoma in situ are managed as one entity. The adaptive end of the same spectrum is [[metaplasia-dysplasia]].",
    "**One basement membrane carries the whole prognosis.** Surface epithelium is avascular: above the membrane there are no capillaries and no lymphatics, so carcinoma in situ has no anatomical route out of the tissue and cannot metastasise — complete local excision is curative in essentially every case. The moment tumour cells degrade that sheet of type IV collagen and laminin they reach stroma, capillaries and lymphatics, and the lesion acquires a metastatic risk measured in tens of per cent. Nothing else about the tumour has to change; same cells, same grade, yet treatment moves from local excision to nodal staging, wider resection and adjuvant therapy. Invasion also recruits the stroma: **desmoplasia** is the dense fibrous reaction that makes an invasive carcinoma hard, gritty and fixed, while a benign tumour stays soft, encapsulated and mobile. What happens past that line is [[rbp-carcinogenesis-tumour-progression]].",
    "**Grade says how the cells look, stage says how far they have gone — and stage wins.** Grade is cytological and organ-specific: Nottingham grade in breast from tubule formation, nuclear pleomorphism and mitotic count; Gleason score in prostate from architecture alone. Stage is anatomical and standardised as **TNM** — T for size or depth of local invasion, N for the number and level of involved regional nodes, M for distant metastasis — collapsed into stage groups I to IV. For most solid tumours stage is the stronger prognostic variable and nodal status is usually the single strongest item within it, so a grade 1 tumour with a liver deposit is stage IV and does worse than a grade 3 tumour confined to mucosa with clear nodes. The honest exception is prostate, where Gleason grade carries at least as much prognostic weight as stage. Working rule: grade helps choose the therapy, stage predicts the outcome. The behavioural basis of both is developed in [[neoplasia-differentiation-invasion]].",
  ],

  mechanism: {
    title: 'Normal epithelium → dysplasia → carcinoma in situ → basement membrane breach → invasion → metastasis',
    steps: [
      {
        id: 's1',
        label: 'Chronic injury drives adaptation first: hyperplasia, then metaplasia to a tougher epithelium',
        detail: 'Barrett oesophagus and bronchial squamous metaplasia are adaptations, not neoplasms — but the replacement epithelium now sits in an environment it did not evolve for, and it is the metaplastic epithelium that becomes dysplastic.',
      },
      {
        id: 's2',
        label: 'Dysplasia appears: loss of uniformity, loss of polarity, mitoses above the basal layer',
        detail: 'Graded mild, moderate, severe. Still reversible if the driver is removed — this is the window that screening programmes are built to catch.',
        emphasis: 'key',
      },
      {
        id: 's3',
        label: 'Full-thickness atypia with an intact basement membrane: carcinoma in situ',
        detail: 'Cytologically malignant, biologically confined. There are no capillaries or lymphatics above the membrane, so metastasis is anatomically impossible and complete excision is curative.',
        emphasis: 'key',
      },
      {
        id: 's4',
        label: 'Type IV collagen and laminin are degraded and the membrane is breached: invasive carcinoma',
        detail: 'The single event that converts a curable lesion into one with a measurable risk of death. Desmoplastic stroma is its histological signature and the hard fixed mass is its clinical one.',
        emphasis: 'danger',
      },
      {
        id: 's5',
        label: 'Tumour reaches stroma, lymphatics and capillaries; regional nodes are seeded first for most carcinomas',
        detail: 'Node status becomes the strongest single prognostic variable, which is why a staging operation samples nodes rather than simply removing the mass.',
        emphasis: 'key',
      },
      {
        id: 's6',
        label: 'Distant deposits establish stage IV — the only finding that proves malignancy outright',
        detail: 'Grade can be argued between pathologists; a metastasis cannot. The asymmetry also means absence of metastasis never argues for benignity.',
        emphasis: 'danger',
      },
    ],
    branches: [
      {
        fromId: 's2',
        title: 'The reversible arm',
        steps: [
          { id: 'b1', label: 'Driver removed — HPV cleared, reflux controlled, smoking stopped', emphasis: 'key' },
          { id: 'b2', label: 'Mild to moderate dysplasia regresses; the epithelium re-establishes polarity and basal mitoses' },
          { id: 'b3', label: 'This arm closes once the lesion is full-thickness: severe dysplasia and carcinoma in situ are excised, not watched' },
        ],
      },
    ],
  },

  examFindings: [
    {
      sign: 'Nuclear-to-cytoplasmic ratio approaching 1:1 with coarse clumped chromatin and prominent nucleoli',
      mechanism: 'Anaplasia — transcription and replication run without restraint, so the nucleus enlarges while the cytoplasm cannot keep pace',
      significance: 'key',
    },
    {
      sign: 'A tripolar or quadripolar mitotic figure',
      mechanism: 'Abnormal spindle assembly on an unstable genome; regenerating epithelium and germinal centres also show many mitoses, so it is the atypical form and not the count that argues for malignancy',
      significance: 'key',
    },
    {
      sign: 'A hard, gritty, fixed mass with an irregular infiltrative edge on cut section',
      mechanism: 'Desmoplastic stromal reaction to invasion tethers the tumour to surrounding tissue — the palpable counterpart of a breached basement membrane',
      significance: 'key',
    },
    {
      sign: 'A soft, encapsulated, mobile mass that shells out cleanly at operation',
      mechanism: 'A benign tumour expands and compresses adjacent tissue into a fibrous rim rather than infiltrating through it',
      significance: 'supportive',
    },
    {
      sign: 'Full-thickness epithelial atypia with a continuous basement membrane on a type IV collagen stain',
      mechanism: 'Carcinoma in situ — malignant cells with no anatomical access to vessels or lymphatics, so the metastatic risk is nil',
      significance: 'key',
    },
    {
      sign: 'A lung nodule with popcorn calcification composed of cartilage, fat and respiratory epithelium',
      mechanism: 'Hamartoma — tissue indigenous to the lung in the right place but disorganised; the abnormality is architectural rather than behavioural',
      significance: 'supportive',
    },
  ],

  investigations: [
    {
      clue: 'An immunohistochemistry panel on a poorly differentiated malignant neoplasm',
      meaning: 'Recovers lineage when morphology has been lost: cytokeratin points to carcinoma, vimentin to sarcoma, S100 with SOX10 or HMB-45 to melanoma, CD45 to lymphoma, chromogranin with synaptophysin to a neuroendocrine tumour. Read the panel, never a single stain — some sarcomas express cytokeratin',
    },
    {
      clue: 'Type IV collagen or laminin immunostain around an atypical epithelial nest',
      meaning: 'Continuous supports carcinoma in situ; interrupted or absent supports microinvasion. This is the stain that decides between cure by excision and a staging operation',
    },
    {
      clue: 'Ki-67 proliferation index',
      meaning: 'The percentage of nuclei in cycle. It formalises grade where mitotic counting is unreliable — pancreatic neuroendocrine tumours are G1 below 3 per cent, G2 from 3 to 20 per cent and G3 above 20 per cent',
    },
    {
      clue: 'Fine needle aspiration reporting atypical cells in a thyroid nodule with follicular architecture',
      meaning: 'Cytology shows cells but destroys tissue relationships, so it can never demonstrate invasion. Follicular adenoma and follicular carcinoma are cytologically identical; only capsular or vascular invasion on the resected capsule separates them, and that requires histology',
    },
    {
      clue: 'Sentinel lymph node biopsy',
      meaning: 'Converts a clinical N into a pathological N by sampling the first node draining the tumour bed. It exists because nodal status usually outweighs every other prognostic variable while full nodal clearance carries lymphoedema',
    },
    {
      clue: 'A TNM stage group that conflicts with the histological grade',
      meaning: 'Trust the stage in most solid tumours. One distant deposit makes a low-grade tumour stage IV, while a high-grade tumour confined to mucosa with clear nodes still has an excellent outlook',
    },
  ],

  treatment: [
    {
      logic: 'Why it matters',
      detail: "Three lines here change management rather than vocabulary. The first is the **basement membrane**: in situ disease is cured by complete local excision, invasive disease needs nodal assessment and usually adjuvant therapy, and the only thing separating them is a sheet of type IV collagen. That is why no pathologist reports invasion from cytology, and why a core biopsy showing only in situ disease can be upstaged once the whole lesion is resected. The second is **stage over grade**: staging decides whether treatment is curative or palliative, so cross-sectional imaging and nodal sampling come before the treatment decision, not after it. The third costs marks and occasionally patients — **benign does not mean harmless**. A benign pituitary adenoma blinds through chiasmal compression, a benign insulinoma causes fatal hypoglycaemia, and a benign meningioma in the posterior fossa kills by mass effect inside a closed box.",
    },
    {
      logic: 'Where it is examined',
      detail: "Five recurring stems. **Which criterion proves malignancy** — metastasis and nothing else; every distractor built on size, growth rate or mitotic count is a spectrum. **In situ versus invasive** — the answer is always the basement membrane, and the stem will hand you an intact or a breached one. **Grade versus stage** — the option describing anatomical extent is stage, and where the two conflict the stage governs prognosis. **Name the lesion** — disorganised tissue native to the organ is a hamartoma, normal tissue in the wrong organ is a choristoma, tissue from more than one germ layer is a teratoma. And **which -oma is malignant**, where the answer set is lymphoma, melanoma, seminoma, mesothelioma or glioma. The molecular machinery under all of this is taken up in [[rbp-carcinogenesis-tumour-progression]].",
    },
  ],

  mnemonics: [
    {
      hook: 'Carcinoma covers, sarcoma supports',
      expansion: [
        'Epithelium covers surfaces, lines tubes and forms glands — its malignancies are carcinomas',
        'Mesenchyme supports: bone, cartilage, fat, muscle, vessels, fibrous tissue — its malignancies are sarcomas',
        'Benign versions of both simply take -oma on the parent cell: osteoma, lipoma, leiomyoma, adenoma',
        'The prefix carries architecture: adeno- for glands, papillary for fronds, cystadeno- for glands that form cysts',
      ],
    },
    {
      hook: 'Five -omas that lie, and two that mislead',
      expansion: [
        'Lymphoma, melanoma, seminoma, mesothelioma, glioma — every one of them malignant',
        'Add the -blastomas: neuroblastoma, retinoblastoma, hepatoblastoma, medulloblastoma',
        'Hamartoma is at home and untidy — right tissue, right site, wrong architecture',
        'Choristoma is tidy and abroad — normal organised tissue sitting in the wrong organ',
      ],
    },
  ],

  traps: [
    {
      questionCategory: 'Staging scans show no metastases',
      wrongInstinct: 'No metastasis means the lesion is benign.',
      rightAnswer: 'Metastasis proves malignancy but never disproves it; invasion through the basement membrane is already sufficient.',
      why: 'Metastasis is 100 per cent specific and poorly sensitive — basal cell carcinoma and glioblastoma are frankly malignant and essentially never metastasise.',
    },
    {
      questionCategory: 'A high-grade node-negative tumour against a low-grade tumour with liver deposits',
      wrongInstinct: 'The high-grade tumour must do worse because the cells look worse.',
      rightAnswer: 'The low-grade tumour with distant deposits is stage IV and has the worse prognosis.',
      why: 'Stage beats grade in most solid tumours; the exception worth naming is prostate, where Gleason grade carries prognostic weight equal to stage.',
    },
  ],

  quiz: [
    {
      id: 'q1',
      stem: 'Which tumour is malignant despite a name ending in -oma?',
      options: [
        { id: 'a', text: 'Leiomyoma of the uterus' },
        { id: 'b', text: 'Mesothelioma of the pleura' },
        { id: 'c', text: 'Fibroadenoma of the breast' },
        { id: 'd', text: 'Osteoma of the frontal bone' },
      ],
      answerId: 'b',
      explanation: 'Mesothelioma belongs to the fixed exception list — lymphoma, melanoma, seminoma, mesothelioma and glioma are malignant despite the benign-sounding suffix. The other three are genuinely benign, so the suffix is a naming convention rather than a statement about behaviour.',
      tests: 'disease',
    },
    {
      id: 'q2',
      stem: 'A cervical biopsy shows full-thickness atypia with a continuous basement membrane on a type IV collagen stain. Which statement is correct?',
      options: [
        { id: 'a', text: 'The lesion cannot metastasise, because there are no vessels or lymphatics above the basement membrane' },
        { id: 'b', text: 'The lesion is already stage II and requires adjuvant chemotherapy' },
        { id: 'c', text: 'Full-thickness atypia excludes malignancy and confirms reactive change' },
        { id: 'd', text: 'Sentinel node biopsy is required before excision' },
      ],
      answerId: 'a',
      explanation: 'This is carcinoma in situ: cytologically malignant but anatomically trapped. Surface epithelium is avascular, so the cells have no route into vessels or lymphatics and complete local excision is curative. Nodal assessment and adjuvant therapy only become relevant once the membrane is breached.',
      tests: 'mechanism',
    },
    {
      id: 'q3',
      stem: 'Patient A has a grade 1 gastric adenocarcinoma invading the serosa with nine positive nodes. Patient B has a grade 3 gastric adenocarcinoma confined to the mucosa with no involved nodes. Which is correct?',
      options: [
        { id: 'a', text: 'Patient B does worse, because grade 3 cells are poorly differentiated' },
        { id: 'b', text: 'Prognosis cannot be compared without a Ki-67 index' },
        { id: 'c', text: 'Patient A does worse, because stage outweighs grade in most solid tumours' },
        { id: 'd', text: 'Both have the same prognosis, since grade and stage carry equal weight' },
      ],
      answerId: 'c',
      explanation: 'Grade describes appearance, stage describes anatomical extent, and for most solid tumours stage is the stronger prognostic variable, with nodal status usually the strongest single item within it. Serosal invasion plus nine positive nodes therefore outweighs poor differentiation in a mucosally confined tumour.',
      tests: 'investigation',
    },
  ],
};

export default rbpNeoplasiaNomenclatureBiology;
