import type { Lecture } from '../../lib/types';

// Original study notes aligned to Robbins Basic Pathology, 9th edition.
// Source and review scope: docs/robbins-coverage.md.
export const rbpPancreatitisAcuteChronic: Lecture = {
  id: 'rbp-pancreatitis-acute-chronic',
  title: 'Acute & Chronic Pancreatitis',
  system: 'gi',
  source: 'Ch 16 — Pancreas',
  updated: '2026-09-19',
  tags: [
    { kind: 'system', label: 'GI' },
    { kind: 'lecture', label: 'Ch 16 Pancreas' },
    { kind: 'mechanism', label: 'Intrapancreatic trypsin activation and autodigestion' },
    { kind: 'disease', label: 'Interstitial, necrotising and chronic pancreatitis' },
  ],

  highYield: [
    '**Every form of pancreatitis is the same accident: zymogens activated INSIDE the gland instead of inside the duodenum — and trypsin is the master switch, because activating trypsin activates everything downstream.** The acinar cell makes about twenty digestive enzymes. The proteases are exported as inert proenzymes; **amylase, lipase and ribonuclease are secreted already ACTIVE**, which is the detail that explains why fat necrosis does not have to wait for anything. Normally **trypsinogen is cleaved only by enterokinase on the duodenal brush border**, and the trypsin so made then activates chymotrypsinogen, proelastase, procarboxypeptidase and prophospholipase A2 — a deliberate single point of control, sited outside the organ. Move that one cleavage inside the pancreas and the same amplification works against the gland. Worse, trypsin also activates **prekallikrein** (kinins: vasodilatation, oedema, pain) and **factor XII** (coagulation, fibrinolysis, complement), which is how an injury confined to one retroperitoneal organ becomes shock and disseminated intravascular coagulation. Three routes converge on that one cleavage: **duct obstruction**, **direct acinar cell injury**, and **defective intracellular transport** in which zymogen granules are delivered into the lysosomal compartment, where **cathepsin B** cleaves trypsinogen. Normal secretory physiology is in [[ghp-pancreatic-biliary-secretion]].',
    '**Three defences normally keep that from happening, and the hereditary pancreatitides are the natural experiment that removes them one at a time.** Ranked by importance: **(1) spatial separation** — the activating enzyme, enterokinase, is fixed to the duodenal brush border and never meets the zymogen until the zymogen has left the gland, and within the acinar cell the granules are membrane-bound and physically segregated from lysosomal hydrolases; **(2) synthesis as inactive proenzymes**, so even a leaking granule spills nothing that can digest; **(3) trypsin inhibitors**, chiefly **SPINK1** (pancreatic secretory trypsin inhibitor), co-packaged in the granule to mop up any trypsin generated by accident, backed by trypsin’s own **autolysis** — trypsin cleaves itself at an arginine site and self-destructs. Hereditary pancreatitis proves the model. **PRSS1** encodes cationic trypsinogen, and the classic **R122H** mutation abolishes exactly that self-destruct site, so once trypsin appears it cannot be removed: autosomal dominant, roughly **80% penetrance**, attacks from childhood, and a lifetime pancreatic cancer risk near **40%**. **SPINK1** loss-of-function removes the inhibitor instead, reaching the same endpoint from the other direction. **CFTR** mutation dehydrates and acidifies ductal secretion so the zymogen sits in the gland longer. Three different genes, one failure mode.',
    '**Gallstones and alcohol cause about 80% of acute pancreatitis between them; everything else is worth knowing only by its mechanism, because the mechanism is what the question tests.** **Gallstones** work by obstruction: a stone impacted at the ampulla raises ductal pressure, produces interstitial oedema, and oedema compromises the local blood supply, so ischaemia is added to obstruction ([[gallstones-cholecystitis-cholangitis]]). **Alcohol** works by at least three routes at once — direct acinar toxicity with oxidative injury, secretion of protein-rich fluid that precipitates as **ductal protein plugs**, and transient contraction of the sphincter of Oddi. The rest sort neatly by route. Obstructive: tumour, ascariasis, sludge; **pancreas divisum** is present in **3 to 10%** of people and only a small minority ever get pancreatitis, so it is genuinely disputed whether it is a cause or merely a predisposition — that is the one place here where hedging is honest. Acinar toxicity: **hypertriglyceridaemia above 1000 mg/dL (about 11 mmol/L)**, where lipase liberates toxic free fatty acids; **hypercalcaemia**, usually hyperparathyroidism, where calcium both activates trypsinogen and helps form ductal plugs; **drugs** — azathioprine, thiazides, valproate, oestrogens, didanosine; **mumps** and other viruses; **ischaemia**. Mechanical: blunt trauma against the vertebral column, and **ERCP**, which causes pancreatitis in about **3 to 5%** of procedures.',
    '**The morphology derives the clinical picture line by line, and fat necrosis is the most satisfying derivation in the chapter.** Five basic alterations: microvascular leak with oedema, fat necrosis by lipases, acute inflammation, proteolytic destruction of parenchyma, and destruction of vessels with interstitial haemorrhage. Take them in order. **Lipase** — released already active — hydrolyses triglyceride in peripancreatic, mesenteric and omental adipocytes; the liberated **free fatty acids chelate calcium into insoluble soaps**, and the result is visible to the naked eye as **chalky-white, opaque plaques** scattered over fat. That saponification physically removes calcium from the circulation, so **HYPOCALCAEMIA follows extensive fat necrosis** — the serum calcium is low because the calcium is sitting in the omentum, which is why a corrected calcium under **2 mmol/L (8 mg/dL)** at 48 hours is a severity criterion rather than an electrolyte curiosity. Circulating lipase can digest fat at a distance, giving subcutaneous nodular fat necrosis and arthritis. Meanwhile **elastase digests the elastin of vessel walls**, so vessels rupture and blood escapes into the retroperitoneum: this converts interstitial (oedematous) pancreatitis into **necrotising** and then **haemorrhagic** pancreatitis, red-black necrosis interspersed with chalky-white plaques. Blood tracking along retroperitoneal planes to the flank is **Grey Turner’s sign**; blood tracking along the falciform ligament to the umbilicus is **Cullen’s sign**. Both appear only after **24 to 48 hours**, occur in about **1 to 3%** of cases, and mean necrosis has already happened.',
    '**Lipase beats amylase for two separate reasons, and neither enzyme grades severity — state that plainly, because acting on a big number is a mistake with real consequences.** Timing: **amylase rises in 6 to 12 hours and is back to normal within 3 to 5 days**, while **lipase rises in 4 to 8 hours and stays elevated for 8 to 14 days** — so a patient presenting on day four has a normal amylase and a diagnostic lipase. Specificity: salivary glands, fallopian tube, bowel and kidney contribute to serum amylase, so parotitis, perforation, ectopic pregnancy, renal failure, diabetic ketoacidosis and macroamylasaemia all raise it, whereas lipase is far more pancreas-restricted. Diagnosis needs a level above **three times the upper limit of normal** together with the clinical picture. But the **magnitude carries NO prognostic information at all**: enzyme concentration measures how much acinar cytoplasm has leaked, not how much gland has died, and the most necrotic glands can show modest levels because little viable acinus remains to leak. Severity is read from organ failure, from **CRP above 150 mg/L at 48 hours**, and from **non-enhancing parenchyma on contrast CT**. The systemic complications all follow from what was released: **phospholipase A2 destroys surfactant → ARDS**; kinins and cytokines (TNF, IL-1, IL-6) produce vasodilatation and third-space loss → **shock**; hypovolaemia plus tubular injury → **acute kidney injury**; trypsin activating factor XII and prothrombin → **disseminated intravascular coagulation**.',
    '**Local complications have a timetable, and chronic pancreatitis has an ORDER in which function fails — both are examinable precisely because they are predictable.** Within the first four weeks a collection is an acute peripancreatic fluid collection or acute necrotic collection; after **four weeks** it has a defined wall and becomes a **PSEUDOCYST** or walled-off necrosis. A pseudocyst is enzyme-rich fluid walled by **granulation and fibrous tissue with NO EPITHELIAL LINING** — which is exactly why it is called pseudo, and it is the single discriminator from a true cystic neoplasm: no epithelium means nothing that can undergo dysplasia, so a pseudocyst has **no malignant potential** and can simply resolve. Its fluid is **amylase-rich and CEA-poor**. Pseudocysts are about **75%** of all pancreatic cysts. **Infected necrosis** peaks at **2 to 3 weeks** and is suggested by gas within the necrosis; a true pancreatic **abscess** is a later, walled collection of pus. Splenic vein thrombosis behind an inflamed tail gives isolated gastric varices. **Chronic pancreatitis** is different in kind: irreversible fibrosis with acinar loss, ductal protein plugs that calcify, and a dilated beaded duct. Because **exocrine reserve is enormous, steatorrhoea appears only once about 90% of acinar function is gone** — and the islets, embedded in fibrosis, survive longer still. So the sequence is fixed: **EXOCRINE failure with steatorrhoea comes FIRST, endocrine failure with diabetes comes later** ([[malabsorption-patterns]]). Management of both is in [[acute-chronic-pancreatitis]].',
  ],

  mechanism: {
    title: 'Three doors into one room: intrapancreatic trypsin activation',
    steps: [
      { id: 's1', label: 'Three initiating routes: duct obstruction, direct acinar cell injury, or defective intracellular transport of zymogens', detail: 'Gallstones and tumours obstruct; alcohol, drugs, trauma, viruses and ischaemia injure the acinus; metabolic injury misroutes granules into the lysosomal compartment.', emphasis: 'normal' },
      { id: 's2', label: 'Trypsinogen is cleaved to trypsin inside the gland — by lysosomal cathepsin B, or by zymogen concentrated behind an obstructed duct', detail: 'Enterokinase, the normal activator, is fixed to the duodenal brush border and is never involved here.', emphasis: 'key' },
      { id: 's3', label: 'Trypsin is the master switch: it activates chymotrypsinogen, proelastase, procarboxypeptidase, prophospholipase A2, prekallikrein and factor XII', detail: 'One cleavage in the wrong place recruits the entire proteolytic, kinin, complement and coagulation apparatus.', emphasis: 'key' },
      { id: 's4', label: 'Lipase hydrolyses peripancreatic fat; free fatty acids chelate calcium into chalky-white soaps, and serum calcium falls', detail: 'Saponification is visible as opaque plaques on omentum and mesentery, and it is the reason hypocalcaemia signals extensive fat necrosis.', emphasis: 'key' },
      { id: 's5', label: 'Elastase digests elastin in vessel walls: vessels rupture, the gland becomes necrotising and then haemorrhagic', detail: 'Retroperitoneal blood tracks to the flank as Grey Turner’s sign and along the falciform ligament as Cullen’s sign, both after 24 to 48 hours.', emphasis: 'danger' },
      { id: 's6', label: 'Enzymes and cytokines enter the circulation: ARDS, shock, acute kidney injury and disseminated intravascular coagulation; repeated attacks leave irreversible fibrosis', detail: 'Phospholipase A2 destroys surfactant, kinins drop vascular resistance, and trypsin activates factor XII. Surviving the attack does not undo the fibrosis.', emphasis: 'danger' },
    ],
  },

  examFindings: [
    { sign: 'Severe boring epigastric pain radiating straight through to the back, eased by sitting forward and worse lying flat', mechanism: 'The pancreas is retroperitoneal, so inflammatory exudate irritates the retroperitoneum and coeliac plexus directly; leaning forward reduces tension on the inflamed bed, which is why posture discriminates this from a hollow viscus perforation where any movement hurts', significance: 'key' },
    { sign: 'Bluish discolouration of the flanks (Grey Turner) or around the umbilicus (Cullen) appearing on the second day', mechanism: 'Elastase has digested elastin in vessel walls, so blood escapes into the retroperitoneum and tracks along fascial planes to the flank, or along the falciform ligament to the umbilicus. Present in only about 1 to 3% and always late, so its absence excludes nothing while its presence means necrosis', significance: 'key' },
    { sign: 'Perioral tingling with carpopedal spasm, and a positive Chvostek sign', mechanism: 'Hypocalcaemia from saponification: lipase-liberated free fatty acids have chelated calcium into insoluble soaps in the peripancreatic and omental fat, so the calcium is sequestered rather than lost. Parathyroid hormone is appropriately high, which is how it is separated from hypoparathyroidism', significance: 'key' },
    { sign: 'Tender red nodules on the shins with painful polyarthritis in a patient with abdominal pain', mechanism: 'Pancreatic panniculitis: circulating lipase digests subcutaneous and periarticular fat at a distance from the gland, producing fat necrosis in the skin and joints. Uncommon, but it is fat necrosis by the identical mechanism, seen where it can be inspected directly', significance: 'supportive' },
    { sign: 'A smooth, non-tender epigastric mass with early satiety, appearing five or six weeks after an attack has settled', mechanism: 'Pseudocyst: enzyme-rich fluid has been walled off by granulation and fibrous tissue, needing at least four weeks to acquire a definable wall. There is no epithelial lining, so it can resolve spontaneously and it cannot become malignant', significance: 'supportive' },
    { sign: 'Bulky, pale, offensive stools that float, with weight loss and a normal duodenal biopsy, in a patient whose fasting glucose is still normal', mechanism: 'Chronic pancreatitis: exocrine reserve is so large that steatorrhoea appears only after roughly 90% of acinar function is lost, while islets embedded in the fibrosis survive longer. A normal small bowel biopsy locates the fault in digestion rather than absorption', significance: 'key' },
  ],

  investigations: [
    { clue: 'Serum lipase eight times the upper limit of normal on day four with an amylase that is already normal', meaning: 'Entirely consistent with acute pancreatitis. Amylase clears within 3 to 5 days while lipase stays up for 8 to 14 days, so late presentation is exactly where lipase earns its place, and lipase is also the more specific of the two. The magnitude of either enzyme grades nothing — severity comes from organ failure and from CRP above 150 mg/L at 48 hours' },
    { clue: 'Corrected serum calcium of 1.8 mmol/L at 48 hours with an appropriately raised parathyroid hormone', meaning: 'Calcium sequestered as soaps in areas of fat necrosis rather than a parathyroid problem — the raised parathyroid hormone proves the axis is responding normally. This is a recognised severity criterion because it is an indirect measure of how much fat has been digested' },
    { clue: 'Contrast-enhanced CT at 72 hours showing a segment of pancreas that does not enhance', meaning: 'Necrosis, defined radiologically by absent perfusion. Timing matters: imaging before 72 hours systematically underestimates the extent, because necrosis takes days to declare itself. Gas within the non-enhancing area indicates infected necrosis, which is the finding that changes management' },
    { clue: 'A unilocular collection at six weeks whose aspirate has an amylase of 40 000 U/L, a CEA of 3 ng/mL and no epithelial cells', meaning: 'Pseudocyst. High amylase says the cavity communicates with the ductal system or was filled by leaked enzyme; low CEA says the lining is not mucinous; absent epithelium says there is no lining at all. That triad separates it from a mucinous cystic neoplasm, where CEA runs high and epithelium is present' },
    { clue: 'Coarse calcification scattered through the gland on plain film, with a dilated, irregularly beaded main pancreatic duct on MRCP', meaning: 'Chronic pancreatitis. The calcification is intraductal protein plugs that have mineralised, and the beaded duct is alternating stricture and dilatation from the same process — the so-called chain of lakes. It also flags a background risk of ductal adenocarcinoma, which chronic pancreatitis raises over decades' },
    { clue: 'Faecal elastase-1 below 100 µg/g of stool in a patient whose fasting glucose and HbA1c are normal', meaning: 'Severe exocrine insufficiency with endocrine function still intact — the expected order, since acinar reserve fails long before islet reserve. Elastase-1 is measured rather than other enzymes because it survives intestinal transit undegraded, so stool concentration reflects pancreatic output' },
  ],

  treatment: [
    {
      logic: 'Treat the fluid compartment in the first 24 hours, because by the time the patient arrives the enzymes are already released and there is nothing left to switch off',
      detail: 'No drug usefully inhibits intrapancreatic trypsin, so the treatable problem is the **third-space loss** driven by kinin-mediated vasodilatation and retroperitoneal exudation — hence **early, goal-directed crystalloid resuscitation**, with the therapeutic window measured in hours rather than days. Two reflexes to resist. **Do not give prophylactic antibiotics** for sterile necrosis: they do not reduce mortality and they select resistant organisms, so antibiotics wait for demonstrated **infected necrosis**. **Do not operate early**: intervention on necrosis before about four weeks increases mortality, so debridement is delayed until the collection has walled off, and then done by the least invasive route available. **ERCP within 24 to 72 hours is for gallstone pancreatitis WITH cholangitis or persistent biliary obstruction only** — it is drainage of infected bile, not treatment of the pancreas. Finally, **cholecystectomy on the same admission** for gallstone pancreatitis: recurrence approaches 30% within weeks if the gallbladder stays in. Clinical detail and scoring in [[acute-chronic-pancreatitis]].',
    },
    {
      logic: 'In chronic pancreatitis replace what is lost in the order it is lost, and remember the enzyme you are giving is acid-labile',
      detail: 'Exocrine failure comes first, so **pancreatic enzyme replacement** comes first — and it must be given **with acid suppression**, because **lipase is irreversibly denatured below about pH 4** and an unprotected preparation is destroyed in the stomach before it reaches the duodenum. That single fact explains most treatment failures. Add **fat-soluble vitamins A, D, E and K**, since it is fat digestion that has failed. Endocrine failure arrives later and is not ordinary type 2 diabetes: this is **type 3c**, in which **glucagon-producing alpha cells are destroyed alongside the beta cells**, so the counter-regulatory defence against hypoglycaemia is gone and insulin therapy is brittle — the safe target is deliberately looser than usual. Pain management is the hardest part and alcohol and tobacco cessation are the only interventions that alter the trajectory of the gland itself.',
    },
  ],

  mnemonics: [
    {
      hook: 'One cleavage decides everything: activate trypsin in the wrong place and you have activated the whole pancreas',
      expansion: [
        'Duct obstruction, acinar cell injury and defective intracellular transport are three doors into one room',
        'Trypsin activates chymotrypsinogen, proelastase, procarboxypeptidase and prophospholipase A2',
        'Trypsin also activates prekallikrein and factor XII, which is how one retroperitoneal organ produces shock and disseminated intravascular coagulation',
        'Amylase and lipase are secreted already active, so fat necrosis does not wait for trypsin',
        'Three defences: enterokinase kept out in the duodenum, enzymes made as zymogens, and SPINK1 plus trypsin autolysis inside the granule',
      ],
    },
    {
      hook: 'Lipase eats fat and the serum calcium pays; elastase eats vessels and the flank pays',
      expansion: [
        'Lipase hydrolyses peripancreatic triglyceride into free fatty acids',
        'Free fatty acids chelate calcium into insoluble soaps: chalky-white plaques on omentum and mesentery',
        'Calcium locked into soaps is calcium missing from serum, so hypocalcaemia measures how much fat has been digested',
        'Elastase digests elastin in vessel walls, so blood escapes into the retroperitoneum',
        'Blood to the flank is Grey Turner, blood along the falciform ligament to the umbilicus is Cullen, and both take 24 to 48 hours to appear',
      ],
    },
  ],

  traps: [
    {
      questionCategory: 'Grading the severity of an attack from the laboratory sheet',
      wrongInstinct: 'The amylase is fifteen times normal, so this attack is far worse than the one with an amylase twice normal',
      rightAnswer: 'Enzyme magnitude does not grade severity at all. Grade it by organ failure, by CRP above 150 mg/L at 48 hours, and by non-enhancing parenchyma on contrast CT at 72 hours',
      why: 'Amylase and lipase measure how much acinar cytoplasm has leaked, not how much gland has died — so a thoroughly necrotic pancreas can show modest levels because little viable acinus remains to leak, and hypertriglyceridaemic pancreatitis lowers the measured amylase outright',
    },
    {
      questionCategory: 'Naming a cystic lesion found after an attack of pancreatitis',
      wrongInstinct: 'A round, well-defined cystic lesion in the pancreas is a cystic neoplasm, so it needs resection',
      rightAnswer: 'A collection with NO epithelial lining, appearing four or more weeks after an attack, with amylase-rich and CEA-poor fluid, is a pseudocyst — it has no malignant potential and is drained only if it is symptomatic, infected or obstructing',
      why: 'The epithelial lining is the entire distinction: a pseudocyst is walled by granulation and fibrous tissue, and tissue with no epithelium has nothing that can become dysplastic, whereas a mucinous neoplasm is lined by mucin-secreting epithelium and therefore can progress to carcinoma',
    },
  ],

  quiz: [
    {
      id: 'q1',
      stem: 'A 14-year-old boy is admitted with his fourth episode of pancreatitis. His father and paternal aunt had recurrent attacks from childhood. There are no gallstones, no alcohol exposure, and serum triglycerides and calcium are normal. Sequencing shows a missense mutation in PRSS1 that replaces the arginine at position 122. Which mechanism best explains his disease?',
      options: [
        { id: 'a', text: 'Enterokinase is absent from the duodenal brush border, so zymogens are activated proximally instead' },
        { id: 'b', text: 'Trypsin can no longer cleave and inactivate itself, so once it appears inside the gland it persists and activates the remaining zymogens' },
        { id: 'c', text: 'Acinar cells fail to synthesise trypsinogen, so pancreatic secretion is replaced by an inflammatory infiltrate' },
        { id: 'd', text: 'The main pancreatic duct is congenitally obstructed by inspissated protein plugs' },
      ],
      answerId: 'b',
      explanation: 'PRSS1 encodes cationic trypsinogen, and arginine 122 is the site at which trypsin cleaves and destroys itself. The R122H substitution removes that fail-safe, so this is a gain-of-function, autosomal dominant disease with roughly 80% penetrance. It is the cleanest natural experiment for the model: the three defences are spatial separation from enterokinase, synthesis as inactive zymogens, and inhibition by SPINK1 together with trypsin autolysis, and hereditary pancreatitis knocks out the last of these. A SPINK1 loss-of-function mutation removes the inhibitor and reaches the same endpoint from the other side. The clinical consequence is not just recurrent attacks: lifetime pancreatic cancer risk approaches 40%, so these patients need long-term surveillance rather than episodic care.',
      tests: 'mechanism',
    },
    {
      id: 'q2',
      stem: 'A 52-year-old man is on day two of severe alcohol-related pancreatitis. He reports perioral tingling, and inflating a blood pressure cuff on his arm provokes carpopedal spasm. Corrected calcium is 1.75 mmol/L and parathyroid hormone is appropriately raised. At laparotomy for an unrelated indication, chalky-white opaque plaques are seen over the omentum and mesentery. What is the cause of the hypocalcaemia?',
      options: [
        { id: 'a', text: 'Suppression of the parathyroid glands by the systemic inflammatory response' },
        { id: 'b', text: 'Dilution by the crystalloid given during resuscitation' },
        { id: 'c', text: 'Calcium sequestered as insoluble soaps in fat that pancreatic lipase has hydrolysed' },
        { id: 'd', text: 'Renal calcium wasting caused by acute tubular necrosis' },
      ],
      answerId: 'c',
      explanation: 'Lipase is secreted in an already active form, so it begins digesting peripancreatic, mesenteric and omental triglyceride immediately. The liberated free fatty acids chelate calcium into insoluble soaps, and those soaps are precisely the chalky-white plaques described at laparotomy. The calcium is therefore not lost from the body but sequestered, which is why the parathyroid response is appropriately brisk rather than absent, excluding hypoparathyroidism. The clinically useful consequence is that serum calcium becomes an indirect measure of how much fat has been digested, which is why a corrected calcium below 2 mmol/L at 48 hours is a recognised severity criterion while the amylase level is not.',
      tests: 'disease',
    },
    {
      id: 'q3',
      stem: 'Seven weeks after an episode of necrotising pancreatitis, a 45-year-old man has a 6 cm unilocular cyst in the body of the pancreas with no septations and no mural nodule. Endoscopic ultrasound-guided aspiration gives fluid with an amylase of 42 000 U/L and a CEA of 3 ng/mL; cytology shows macrophages and debris with no epithelial cells. Which statement is correct?',
      options: [
        { id: 'a', text: 'The fluid profile is typical of a mucinous cystic neoplasm, since CEA is the marker of ductal origin' },
        { id: 'b', text: 'This is a pseudocyst: the absent epithelial lining with amylase-rich, CEA-poor fluid identifies it, and it carries no malignant potential' },
        { id: 'c', text: 'Ovarian-type stroma would be expected beneath the lining on histology' },
        { id: 'd', text: 'All pancreatic cysts larger than 3 cm are premalignant and must be resected' },
      ],
      answerId: 'b',
      explanation: 'Two fluid numbers answer two different questions. High amylase says the cavity contains pancreatic juice, so it communicates with the duct system or was filled by leaked enzyme. Low CEA says the lining, if any, is not mucinous; a CEA above roughly 192 ng/mL is the threshold that indicates a mucinous lesion. Absent epithelium on cytology settles it: a pseudocyst is walled by granulation and fibrous tissue only, which is why it is called pseudo and why it can resolve spontaneously and cannot become malignant. A mucinous cystic neoplasm would show mucinous columnar epithelium over ovarian-type stroma, would occur almost exclusively in women, and would not communicate with the duct; a branch-duct intraductal papillary mucinous neoplasm would communicate with the duct but would also give a high CEA.',
      tests: 'investigation',
    },
  ],
};

export default rbpPancreatitisAcuteChronic;
