import type { Lecture } from '../../lib/types';

// Original study notes aligned to Robbins Basic Pathology, 9th edition.
// Source and review scope: docs/robbins-coverage.md.
export const rbpParathyroidEndocrineNeoplasia: Lecture = {
  id: 'rbp-parathyroid-endocrine-neoplasia',
  title: 'Parathyroid Disease & Endocrine Neoplasia',
  system: 'endocrine',
  source: 'Ch 19 — Endocrine System',
  updated: '2026-09-22',
  tags: [
    { kind: 'system', label: 'Endocrine' },
    { kind: 'lecture', label: 'Ch 19 Endocrine System' },
    { kind: 'mechanism', label: 'Reading PTH against calcium, and autonomy after prolonged stimulation' },
    { kind: 'disease', label: 'Hyperparathyroidism, hypoparathyroidism and the MEN syndromes' },
  ],

  highYield: [
    '**The whole diagnosis of primary hyperparathyroidism sits in one word: INAPPROPRIATE. A PTH inside the reference range is abnormal in the face of hypercalcaemia, because a healthy parathyroid exposed to a high calcium should be switched off altogether.** The calcium-sensing receptor on the chief cell is a G-protein-coupled receptor that reads extracellular ionised calcium and, when calcium rises, actively SUPPRESSES PTH release — so the expected result in a patient with a calcium of 2.9 mmol/L is an undetectable or near-undetectable PTH. A detectable, mid-normal PTH therefore means a gland that is no longer listening, and a frankly raised one means the same thing more loudly. Read against the calcium rather than against the reference interval, and the two commonest causes of hypercalcaemia separate instantly. **PRIMARY HYPERPARATHYROIDISM: calcium HIGH, PTH inappropriately normal or HIGH, phosphate LOW** (because PTH drives phosphaturia through the proximal tubular sodium-phosphate cotransporter), **urinary calcium HIGH, alkaline phosphatase normal to raised, chloride-to-phosphate ratio above 33**. **MALIGNANCY-ASSOCIATED HYPERCALCAEMIA: calcium HIGH, PTH SUPPRESSED**, because the tumour secretes **PTHrP**, which activates the same PTH1 receptor but shares almost no epitopes with PTH and so **does NOT cross-react on the intact-PTH immunoassay** — the parathyroids see the calcium, obey it, and shut down. That gives the clean rule: **hypercalcaemia with a measurable PTH is parathyroid, hypercalcaemia with a suppressed PTH is not.** Together these two account for well over 90% of hypercalcaemia, and they split by timing as well: primary disease is usually an incidental finding on a routine panel in an asymptomatic outpatient, while malignant hypercalcaemia is severe, symptomatic and of short duration ([[hen1-pth-regulation-actions]]).',
    '**About 85 to 95% of primary hyperparathyroidism is a SINGLE ADENOMA, and the specimen proves it by what the other three glands are doing.** A parathyroid adenoma is a solitary, well-circumscribed, soft tan-to-brown nodule, usually **0.5 to 5 g**, composed of sheets of uniform **CHIEF CELLS** with two features worth learning because they are the ones examiners ask for: a **rim of COMPRESSED NORMAL parathyroid tissue outside a delicate capsule**, and **LOSS of the STROMAL FAT** that normally occupies a quarter to a half of a parathyroid gland. Crucially, the **remaining three glands are NORMAL or shrunken**, because the adenoma is autonomous and the resulting hypercalcaemia suppresses them. That is the entire distinction from **PRIMARY HYPERPLASIA** (about 5 to 10%, often syndromic), in which **ALL FOUR glands are enlarged** and the whole tissue mass is the lesion — which is why the operations differ: excise one gland for an adenoma, but subtotal or total parathyroidectomy with autotransplantation for hyperplasia. **PARATHYROID CARCINOMA is about 1%**, is diagnosed like phaeochromocytoma by behaviour rather than by cytology — **invasion of adjacent structures or metastasis**, not pleomorphism — and is suspected before operation by a **palpable neck mass with a calcium above about 3.5 mmol/L and a PTH many times normal**. Genetically, adenomas commonly show a **cyclin D1 (PRAD1) rearrangement** that places the cyclin under the PTH promoter, and about a fifth carry **MEN1** mutations, so a parathyroid lesion in a young patient is a reason to look for a syndrome. Do not confuse any of this with the **secondary** gland, where all four are hyperplastic because they are being driven from outside.',
    '**The classic tetrad is stones, bones, abdominal groans and psychic moans, and the skeletal end-stage — osteitis fibrosa cystica with brown tumours — is the one lesion here that looks malignant and is not.** PTH does not resorb bone itself; it has no receptor on the osteoclast. It binds the **PTH1 receptor on OSTEOBLASTS and osteocytes**, which respond by raising **RANKL** and lowering **osteoprotegerin**, and RANKL then drives osteoclast differentiation and activity — so the osteoclast is doing the damage under instruction. Sustained excess gives **OSTEITIS FIBROSA CYSTICA**: cortical thinning, **DISSECTING OSTEITIS** in which osteoclasts tunnel along the centre of trabeculae, marrow replaced by fibrovascular tissue, and cystic spaces. Within those spaces sit **BROWN TUMOURS**, and the name is a trap because they are **NOT neoplasms at all** — they are reactive collections of **osteoclastic giant cells, haemorrhage, haemosiderin-laden macrophages and reactive fibrous tissue**, brown precisely because of the haemosiderin, and they **HEAL and remineralise once the parathyroid lesion is removed**. The most specific radiographic sign is **SUBPERIOSTEAL RESORPTION on the RADIAL aspect of the middle phalanges** of the index and middle fingers, with tuft acro-osteolysis and a granular salt-and-pepper skull. Fill in the rest of the tetrad by mechanism: **stones** because filtered calcium load rises, giving nephrolithiasis and nephrocalcinosis; **abdominal groans** because hypercalcaemia depresses smooth muscle giving constipation, and stimulates gastrin and activates trypsinogen giving peptic ulceration and pancreatitis; **psychic moans** because high calcium raises the neuronal depolarisation threshold, giving fatigue, depression, poor concentration and, at extremes, stupor. Hypercalcaemia also shortens the **QT interval**, which is the exact mirror of hypocalcaemia.',
    '**Secondary and tertiary hyperparathyroidism are one continuous story, and it is worth deriving rather than memorising, because the transition is defined by the CALCIUM finally turning around.** Chronic kidney disease attacks calcium from two directions at once. First, the diseased proximal tubule loses **1-alpha-hydroxylase**, so **25-hydroxyvitamin D is not converted to calcitriol**; intestinal calcium absorption falls, and the direct suppression that calcitriol normally exerts on the PTH gene through the vitamin D receptor is also lost ([[hen1-vitamin-d-metabolism-actions]]). Second, the falling GFR **retains PHOSPHATE**, which lowers ionised calcium by complexing it, independently stimulates the chief cell, and raises **FGF23**, which further inhibits 1-alpha-hydroxylase and so tightens the same loop. All four glands are therefore driven hard and undergo **chief-cell hyperplasia**, giving the signature of **SECONDARY disease: PTH HIGH, calcium LOW or low-normal, phosphate HIGH, calcitriol LOW**. The skeletal result is **renal osteodystrophy**, a mixture of osteitis fibrosa, osteomalacia from the vitamin D defect, and adynamic bone. Now the transition. After years of maximal stimulation one nodule within the hyperplastic tissue expands **clonally** and **downregulates its calcium-sensing receptors and vitamin D receptors**, so it stops responding to correction — the gland has become **AUTONOMOUS**. That is **TERTIARY hyperparathyroidism**, and it announces itself by the one value that had always been low now rising: **PTH remains HIGH and calcium becomes HIGH**, typically after transplantation or after prolonged dialysis, and it needs surgery rather than medical management. So the sequence reads cleanly: **secondary is high PTH with LOW calcium; tertiary is high PTH with HIGH calcium; and the difference is autonomy purchased by years of drive.**',
    '**Two mimics on either side of the parathyroid: FAMILIAL HYPOCALCIURIC HYPERCALCAEMIA, which looks like primary hyperparathyroidism but must never be operated on, and PSEUDOHYPOPARATHYROIDISM, which looks like hypoparathyroidism but has a HIGH PTH.** **FHH** is an autosomal dominant **inactivating mutation of the calcium-sensing receptor**. The receptor sits on both the parathyroid chief cell and the thick ascending limb, so a receptor that under-reads calcium does two things: the gland tolerates a higher calcium set-point, giving lifelong **mild hypercalcaemia with a normal or mildly raised PTH** that is biochemically indistinguishable from mild primary disease; and the kidney, believing calcium to be low, **reabsorbs it avidly**. The urine is therefore the discriminator, and it is the only one that works: **24-hour urinary calcium is LOW** and the **calcium-to-creatinine CLEARANCE RATIO is below 0.01**, against above 0.02 in primary hyperparathyroidism. Recognising it prevents a real harm — **FHH is asymptomatic, causes no stones or bone disease, and parathyroidectomy does not cure it**, because the defect is in the receptor rather than in the gland, so the operation delivers a scar, a recurrent laryngeal nerve risk and persistent hypercalcaemia. On the other side, **HYPOPARATHYROIDISM** is most often **POST-SURGICAL** — inadvertent removal or devascularisation during thyroidectomy or parathyroidectomy — with **autoimmune** disease (part of autoimmune polyendocrine syndrome type 1, with the **AIRE** mutation, chronic mucocutaneous candidiasis and adrenalitis) and the **22q11.2 deletion of DiGeorge syndrome** (third and fourth pharyngeal pouch failure, so absent parathyroids and absent thymus) next. It gives **low calcium with a LOW PTH**, tetany, **Chvostek and Trousseau signs**, a **PROLONGED QT**, laryngospasm, seizures, and with time basal ganglia calcification and cataracts. **PSEUDOHYPOPARATHYROIDISM type 1A** is end-organ resistance, not hormone failure: a maternally inherited loss-of-function **GNAS** mutation disables the Gs alpha subunit downstream of the PTH1 receptor, so **calcium is LOW while PTH is HIGH**, and the somatic phenotype of **Albright hereditary osteodystrophy** — short stature, round face, shortened fourth and fifth metacarpals, subcutaneous ossification — accompanies it. Inherit the identical mutation from the father and imprinting spares the renal tubule, giving the same appearance with **normal biochemistry: pseudopseudohypoparathyroidism**.',
    '**The MEN syndromes organise endocrine neoplasia, and one contrast explains why they are managed so differently: MEN1 is a TUMOUR SUPPRESSOR while MEN2 is an ONCOGENE.** **MEN1** is an autosomal dominant loss-of-function mutation of the **MEN1** gene at **11q13**, encoding **menin**; it is a classic **two-hit** tumour suppressor, so tumours appear only where a somatic second hit lands, unpredictably, in any of a wide range of tissues. The tumours are the **three Ps: PARATHYROID** hyperplasia or adenomas, which are the earliest and most penetrant lesion and are present in nearly all patients by 50; **PANCREATIC and duodenal neuroendocrine tumours**, typically multifocal, of which **gastrinoma causing the Zollinger-Ellison syndrome** is the most lethal and **insulinoma** the next commonest; and **PITUITARY adenomas**, usually prolactinomas. **MEN2** is the inverse genetically: an autosomal dominant **ACTIVATING** (gain-of-function) mutation of the **RET** proto-oncogene at **10q11**, a receptor tyrosine kinase, and a single hit is enough to drive proliferation in every cell that carries it — which is why the target tissue undergoes diffuse **hyperplasia before it becomes carcinoma** and why penetrance is near complete. **MEN2A (Sipple)**, typically codon **634**, gives **MEDULLARY THYROID CARCINOMA, PHAEOCHROMOCYTOMA and PARATHYROID hyperplasia**. **MEN2B**, almost always codon **918**, gives **MEDULLARY THYROID CARCINOMA and PHAEOCHROMOCYTOMA with MUCOSAL NEUROMAS and a MARFANOID habitus, and NO parathyroid disease** — that absence is the examinable difference. Medullary carcinoma in either is **bilateral, multicentric and preceded by C-cell hyperplasia**, and in MEN2B it appears in infancy and is the most aggressive form ([[thyroid-neoplasms]]). Now the consequence of the genetics. Because RET is a dominantly acting oncogene with near-complete penetrance in one predictable organ, the cancer can be **pre-empted: PROPHYLACTIC TOTAL THYROIDECTOMY** is offered to gene carriers, in infancy for codon 918 and in early childhood for codon 634, before carcinoma has developed. No such operation exists for MEN1, because a tumour suppressor needs an unpredictable second hit in an unpredictable one of several organs, so there is no single gland whose removal would pre-empt the disease and management is lifelong biochemical surveillance instead. Phaeochromocytoma must always be excluded and blocked before any operation in MEN2 ([[rbp-adrenal-pathology]]).',
  ],

  mechanism: {
    title: 'From failing kidney to autonomous gland: deriving secondary and then tertiary hyperparathyroidism',
    steps: [
      { id: 's1', label: 'GFR falls, so filtered phosphate falls and phosphate is RETAINED; FGF23 rises in compensation and further inhibits 1-alpha-hydroxylase', detail: 'Phosphate retention is the first insult and it is doubly damaging, because FGF23 secreted to excrete it also shuts down the enzyme the kidney needs for vitamin D activation.', emphasis: 'normal' },
      { id: 's2', label: 'The diseased proximal tubule loses 1-alpha-hydroxylase, so 25-hydroxyvitamin D is not converted to calcitriol and intestinal calcium absorption falls', detail: 'Calcitriol also acts through the vitamin D receptor to suppress PTH gene transcription directly, so losing it removes both the calcium supply and a brake on the gland.', emphasis: 'key' },
      { id: 's3', label: 'Ionised calcium falls, and retained phosphate lowers it further by complexing it while stimulating the chief cell in its own right', detail: 'Three independent stimuli now converge on the same cell: low calcium, high phosphate, and absent calcitriol suppression.', emphasis: 'key' },
      { id: 's4', label: 'All FOUR glands undergo chief-cell hyperplasia: PTH HIGH, calcium LOW or low-normal, phosphate HIGH, calcitriol LOW — this is SECONDARY hyperparathyroidism', detail: 'Four-gland enlargement is the morphological signature of a gland driven from outside, as against the single adenoma with three suppressed neighbours that defines primary disease.', emphasis: 'key' },
      { id: 's5', label: 'The skeleton pays: renal osteodystrophy, a mixture of osteitis fibrosa from the PTH drive, osteomalacia from the vitamin D defect, and adynamic bone from oversuppression of turnover', detail: 'Unlike primary disease the bone lesion here is mixed, because two different metabolic insults are acting on the same tissue at once.', emphasis: 'normal' },
      { id: 's6', label: 'After years of maximal drive a nodule expands clonally and downregulates its calcium-sensing and vitamin D receptors: it stops listening, and PTH stays HIGH while calcium now RISES — TERTIARY hyperparathyroidism', detail: 'Autonomy is the whole definition. The calcium turning from low to high is the single result that marks the transition, and it makes the disease surgical rather than medical.', emphasis: 'danger' },
    ],
    branches: [
      {
        fromId: 's4',
        title: 'When the calcium-phosphate product turns lethal',
        steps: [
          { id: 'b1', label: 'Phosphate stays high while calcium is corrected with calcium-based binders and vitamin D analogues, so the calcium-phosphate product climbs', emphasis: 'normal' },
          { id: 'b2', label: 'Calcium phosphate precipitates in the MEDIA of dermal arterioles and small subcutaneous vessels, which undergo osteogenic transformation', emphasis: 'key' },
          { id: 'b3', label: 'Intimal proliferation and fibrosis narrow the already calcified lumen, and thrombosis completes the occlusion', emphasis: 'key' },
          { id: 'b4', label: 'Calciphylaxis: exquisitely painful retiform purpura progressing to black necrotic skin ulcers over fat-rich areas, with mortality above 50% at one year, usually from sepsis', emphasis: 'danger' },
        ],
      },
    ],
  },

  examFindings: [
    { sign: 'Carpopedal spasm — wrist flexed, thumb adducted, fingers extended at the interphalangeal joints — appearing within three minutes of inflating a sphygmomanometer cuff above systolic pressure', mechanism: 'Trousseau sign of latent tetany. Low ionised calcium relieves the surface-charge screening of voltage-gated sodium channels, lowering the threshold for axonal firing, and the ischaemia produced by the cuff unmasks that hyperexcitability in the underlying motor nerve. It is more specific than the Chvostek sign and is the bedside test worth doing', significance: 'key' },
    { sign: 'Twitching of the ipsilateral upper lip or nasolabial fold when the facial nerve is tapped just anterior to the tragus', mechanism: 'Chvostek sign, the same peripheral nerve hyperexcitability of hypocalcaemia expressed in a motor cranial nerve. Treat it as corroborative rather than decisive: it is present in up to 10% of normocalcaemic people and absent in around a third of genuinely hypocalcaemic ones, which is exactly why Trousseau outranks it', significance: 'supportive' },
    { sign: 'Hand radiograph showing lacy erosion of the periosteal surface on the RADIAL side of the middle phalanges of the index and middle fingers, with resorption of the terminal tufts', mechanism: 'Subperiosteal resorption, the most specific radiographic sign of hyperparathyroidism. PTH acts on osteoblasts and osteocytes to raise RANKL, and the recruited osteoclasts attack bone at its most metabolically exposed surfaces first. The same process gives the granular salt-and-pepper skull and dissecting osteitis within trabeculae', significance: 'key' },
    { sign: 'An expansile, painless lytic lesion of the mandible in a patient with a calcium of 3.0 mmol/L, which on section is soft and deep brown', mechanism: 'A brown tumour of osteitis fibrosa cystica. It is not a neoplasm: it is a reactive mass of osteoclastic giant cells, fresh and old haemorrhage, haemosiderin-laden macrophages and fibrous tissue, brown from the haemosiderin. Recognising it matters because it mimics a giant cell tumour radiologically yet remineralises once the parathyroid lesion is excised', significance: 'key' },
    { sign: 'A tall teenager with long limbs, a high-arched palate, lumpy nodules studding the lips, eyelids and anterior tongue, and a firm thyroid nodule', mechanism: 'MEN2B. The activating RET mutation at codon 918 drives proliferation in every neural-crest-derived tissue that expresses the receptor, so mucosal neuromas and a marfanoid habitus accompany medullary thyroid carcinoma and phaeochromocytoma. Parathyroid disease is characteristically ABSENT, which is what separates MEN2B from MEN2A at the bedside', significance: 'key' },
    { sign: 'A short adult with a round face and a dimple instead of a knuckle over the fourth and fifth fingers when the fist is clenched, with subcutaneous bony lumps', mechanism: 'Albright hereditary osteodystrophy: the shortened fourth and fifth metacarpals are the reason the knuckle is missing. It accompanies pseudohypoparathyroidism type 1A, in which a maternally inherited GNAS loss-of-function mutation blocks Gs alpha signalling downstream of the PTH1 receptor, so the biochemistry is low calcium with a HIGH PTH — end-organ resistance rather than hormone deficiency', significance: 'key' },
  ],

  investigations: [
    { clue: 'Calcium 2.86 mmol/L with intact PTH 61 pg/mL against a reference range of 15 to 65, phosphate 0.68 mmol/L and raised 24-hour urinary calcium', meaning: 'Primary hyperparathyroidism, and the apparently normal PTH is the diagnosis rather than an argument against it. A chief cell whose calcium-sensing receptor is working should be almost completely suppressed at a calcium of 2.86, so any measurable PTH identifies a gland that has stopped listening. The low phosphate corroborates it, because PTH inhibits the proximal tubular sodium-phosphate cotransporter and forces phosphaturia. Read PTH against the calcium, never against the reference interval' },
    { clue: 'Calcium 3.42 mmol/L with intact PTH below 5 pg/mL, in a 68-year-old smoker with a cavitating lung lesion and a two-week history', meaning: 'Malignancy-associated hypercalcaemia, most likely humoral, from PTHrP secreted by a squamous carcinoma. PTHrP activates the same PTH1 receptor but shares almost no epitopes with PTH, so it does not cross-react on the intact-PTH assay: the parathyroids correctly sense the high calcium and switch off, and the suppressed PTH is therefore the expected result. Measure PTHrP to confirm, and look separately for lytic metastases or myeloma, which raise calcium through local osteoclast activation instead' },
    { clue: 'Calcium 2.72 mmol/L with PTH mid-normal, present unchanged on records going back twelve years, 24-hour urinary calcium 62 mg, and a calcium-to-creatinine clearance ratio of 0.006', meaning: 'Familial hypocalciuric hypercalcaemia, and the finding that makes the call is the urine. An inactivating calcium-sensing receptor mutation raises the parathyroid set-point AND makes the thick ascending limb reabsorb calcium as though the patient were hypocalcaemic, so urinary calcium is low, against a ratio above 0.02 in primary hyperparathyroidism. The lifelong stable history fits. This patient must NOT be sent for parathyroidectomy: the defect is in the receptor, so surgery leaves the hypercalcaemia unchanged' },
    { clue: 'A dialysis patient with phosphate 2.4 mmol/L, calcium 2.02 mmol/L and PTH 880 pg/mL, whose values four years later read calcium 2.84 mmol/L with PTH 1350 pg/mL', meaning: 'Secondary hyperparathyroidism progressing to tertiary. The first set is the textbook secondary pattern of a gland driven from outside: PTH high because calcium is LOW and phosphate high. The second set is the transition, and the single value that defines it is the calcium, which has crossed from low to high while PTH stayed up. A nodule within the hyperplastic tissue has expanded clonally and downregulated its calcium-sensing and vitamin D receptors, so it no longer responds to correction and the disease has become surgical' },
    { clue: 'Sestamibi scan and neck ultrasound both localise a single inferior focus, and intraoperative PTH falls from 142 to 38 pg/mL ten minutes after excision', meaning: 'A solitary adenoma, cured. The intraoperative assay works because circulating PTH has a half-life of only about 2 to 4 minutes, so removing the only autonomous source produces a measurable fall within minutes, and a drop of more than 50% into the normal range predicts cure. Failure of the level to fall means residual autonomous tissue and therefore four-gland hyperplasia rather than an adenoma, which changes the operation on the table to subtotal parathyroidectomy' },
    { clue: 'A germline RET mutation at codon 634 in an asymptomatic 4-year-old whose father had medullary thyroid carcinoma and a phaeochromocytoma', meaning: 'MEN2A. RET is an activating oncogene needing only a single hit, so penetrance for medullary thyroid carcinoma approaches 100% and the tumour is preceded by diffuse C-cell hyperplasia in a predictable organ. That combination is what makes prophylactic total thyroidectomy in early childhood both possible and standard, with calcitonin used for surveillance. Before any operation, plasma metanephrines must exclude a phaeochromocytoma, because an unblocked tumour can turn anaesthesia into a hypertensive crisis' },
  ],

  treatment: [
    {
      logic: 'Read the PTH against the calcium, and never open a neck before you have seen the urine',
      detail: 'Three checks, in order, and each one has prevented a wrong operation. **First, interpret PTH against the calcium rather than the reference range.** A chief cell with an intact calcium-sensing receptor should be fully suppressed at a high calcium, so an **inappropriately normal PTH is as diagnostic as a raised one**, while a **SUPPRESSED PTH sends you to malignancy** and to PTHrP, lytic metastases or myeloma, because PTHrP does not cross-react on the intact-PTH assay. **Second, measure a 24-hour urinary calcium and the calcium-to-creatinine clearance ratio before referring anyone for surgery.** A ratio **below 0.01** with lifelong stable mild hypercalcaemia is **familial hypocalciuric hypercalcaemia**, which is harmless and is **not cured by parathyroidectomy**, since the lesion is a receptor rather than a gland. **Third, operate for the right reasons.** Parathyroidectomy is indicated for symptomatic disease and, in the asymptomatic patient, for **age under 50, calcium more than 0.25 mmol/L above the upper limit, creatinine clearance below 60 mL/min, nephrolithiasis or nephrocalcinosis, or a T-score at or below -2.5**. Localise with **sestamibi and ultrasound**, use the **intraoperative PTH assay** to confirm that the single source has gone, and expect **transient postoperative hypocalcaemia** — with **hungry bone syndrome** after a long-standing high turnover, where a remineralising skeleton strips calcium, phosphate and magnesium from the blood for days.',
    },
    {
      logic: 'In MEN2 you can remove the organ before the cancer arrives; in MEN1 you cannot, and the reason is oncogene against tumour suppressor',
      detail: 'This is the clearest place in pathology where a genetic mechanism dictates an operation. **RET in MEN2 is an ACTIVATING mutation of a proto-oncogene**, so a **single inherited hit is already sufficient** to drive proliferation, penetrance approaches **100%**, and the target is one predictable organ that passes through **C-cell hyperplasia** before it becomes carcinoma. A gland that is certain to become malignant and can be removed entirely is therefore worth removing pre-emptively: **prophylactic TOTAL thyroidectomy**, in the **first year of life for codon 918 (MEN2B)** and in **early childhood for codon 634 (MEN2A)**, with lifelong thyroxine and **calcitonin and CEA** for surveillance. **MEN1 is a two-hit TUMOUR SUPPRESSOR** encoding **menin**, so disease requires an unpredictable somatic second hit in an unpredictable one of several organs — parathyroid, pancreatic islet and duodenum, pituitary — and **no single prophylactic operation exists**, which is why management is **annual biochemical surveillance** (calcium and PTH, gastrin, fasting glucose and insulin, prolactin and IGF-1) with imaging, and surgery only when a lesion declares itself. Two sequencing rules complete the picture. **Exclude and ALPHA-block a phaeochromocytoma before any other operation in MEN2**, because an unrecognised tumour turns induction of anaesthesia into a hypertensive crisis. And in MEN1, **resect the parathyroids before the gastrinoma is tackled**, because hypercalcaemia itself stimulates gastrin secretion and correcting it often improves the Zollinger-Ellison syndrome.',
    },
  ],

  mnemonics: [
    {
      hook: 'Stones, bones, abdominal groans and psychic moans — and PTH raises calcium while LOWERING phosphate',
      expansion: [
        'Stones: the filtered calcium load rises, giving nephrolithiasis and nephrocalcinosis',
        'Bones: osteitis fibrosa cystica with brown tumours, which are osteoclasts, haemorrhage and fibrous tissue and NOT neoplasms',
        'Abdominal groans: constipation from depressed smooth muscle, peptic ulceration from raised gastrin, and pancreatitis',
        'Psychic moans: fatigue, depression, poor concentration and, at extremes, stupor, because high calcium raises the depolarisation threshold',
        'PTH raises calcium and LOWERS phosphate, so a high calcium with a LOW phosphate is parathyroid until proved otherwise',
        'Hypercalcaemia SHORTENS the QT interval; hypocalcaemia prolongs it, with Chvostek and Trousseau signs alongside',
      ],
    },
    {
      hook: 'Count the Ps, then ask whether the gene is a brake or an accelerator',
      expansion: [
        'MEN1 is three Ps: PARATHYROID, PANCREATIC and duodenal neuroendocrine tumours, and PITUITARY adenoma',
        'MEN2A is medullary thyroid carcinoma plus PHAEOCHROMOCYTOMA plus PARATHYROID hyperplasia',
        'MEN2B is medullary thyroid carcinoma plus PHAEOCHROMOCYTOMA plus mucosal neuromas and a marfanoid habitus, with NO parathyroid disease',
        'MEN1 is a TUMOUR SUPPRESSOR (menin, 11q13) needing a second hit, so the tumours are scattered and unpredictable',
        'MEN2 is an ONCOGENE (RET, 10q11) activated by one hit, so penetrance is near complete in one predictable organ',
        'That is exactly why prophylactic thyroidectomy is offered in MEN2 and why nothing equivalent exists for MEN1',
      ],
    },
  ],

  traps: [
    {
      questionCategory: 'Interpreting a PTH that falls inside the reference range',
      wrongInstinct: 'Calcium is high but PTH is within the normal range, so the parathyroids are behaving normally and the search should move to malignancy',
      rightAnswer: 'A measurable PTH in the presence of hypercalcaemia is diagnostic of primary hyperparathyroidism. A normal gland exposed to a calcium of 2.9 mmol/L should be suppressed to an undetectable level, so a mid-normal value identifies a gland that has stopped responding',
      why: 'PTH must be read against the calcium, not against the reference interval, because the reference interval was constructed in people with normal calcium — and the discriminating rule is that malignancy SUPPRESSES PTH, since PTHrP drives the receptor without cross-reacting on the assay',
    },
    {
      questionCategory: 'Selecting a hypercalcaemic patient for parathyroidectomy',
      wrongInstinct: 'Mild hypercalcaemia with a non-suppressed PTH is primary hyperparathyroidism, so refer for neck exploration',
      rightAnswer: 'Measure the 24-hour urinary calcium and the calcium-to-creatinine clearance ratio first. A ratio below 0.01, lifelong stable mild hypercalcaemia and an affected first-degree relative identify familial hypocalciuric hypercalcaemia, which is benign and needs no operation at all',
      why: 'The inactivating calcium-sensing receptor mutation acts on the renal tubule as well as the chief cell, so the kidney reabsorbs calcium avidly and the urine gives it away — and because the defect is in the receptor rather than in the gland, removing parathyroid tissue leaves the hypercalcaemia exactly where it was',
    },
  ],

  quiz: [
    {
      id: 'q1',
      stem: 'A 58-year-old woman is found on a routine panel to have calcium 2.88 mmol/L. Intact PTH is 58 pg/mL (reference 15 to 65), phosphate 0.65 mmol/L, and 24-hour urinary calcium is raised with a calcium-to-creatinine clearance ratio of 0.031. Which statement is correct?',
      options: [
        { id: 'a', text: 'The normal PTH excludes a parathyroid cause, so this is most likely occult malignancy' },
        { id: 'b', text: 'This is primary hyperparathyroidism: a PTH that is merely normal is inappropriate when calcium is high, because a responsive gland would be suppressed' },
        { id: 'c', text: 'The low phosphate points away from the parathyroid, since PTH raises both calcium and phosphate' },
        { id: 'd', text: 'The picture fits familial hypocalciuric hypercalcaemia and no further action is needed' },
      ],
      answerId: 'b',
      explanation: 'The calcium-sensing receptor on the chief cell actively suppresses PTH release as calcium rises, so the expected PTH at a calcium of 2.88 mmol/L is undetectable or close to it. A value sitting comfortably inside the reference range therefore identifies a gland that is no longer responding to calcium, and inappropriateness rather than absolute elevation is what makes the diagnosis. Option a inverts the discriminator: malignancy-associated hypercalcaemia SUPPRESSES PTH, because PTHrP activates the PTH1 receptor without cross-reacting on the intact-PTH immunoassay, so a measurable PTH argues against it. Option c has the physiology backwards, since PTH raises calcium and LOWERS phosphate by inhibiting the proximal tubular sodium-phosphate cotransporter, and the low phosphate here supports the diagnosis. Option d is excluded by the urine: familial hypocalciuric hypercalcaemia has a clearance ratio below 0.01, whereas 0.031 is firmly in the primary range.',
      tests: 'investigation',
    },
    {
      id: 'q2',
      stem: 'A man on haemodialysis for six years had calcium 2.05 mmol/L with PTH 790 pg/mL two years ago. He now has calcium 2.87 mmol/L with PTH 1420 pg/mL, phosphate 2.1 mmol/L, and painful violaceous skin lesions over the thighs progressing to black eschars. Which statement best explains what has happened?',
      options: [
        { id: 'a', text: 'He has developed primary hyperparathyroidism from a new solitary adenoma, unrelated to his renal disease' },
        { id: 'b', text: 'Years of maximal stimulation have allowed a nodule in the hyperplastic glands to expand clonally and downregulate its calcium-sensing and vitamin D receptors, so PTH secretion has become autonomous and calcium has risen: tertiary hyperparathyroidism, now complicated by calciphylaxis' },
        { id: 'c', text: 'This remains secondary hyperparathyroidism, and the rise in calcium simply reflects better dietary intake' },
        { id: 'd', text: 'The skin lesions are vasculitic and indicate an unrelated autoimmune process' },
      ],
      answerId: 'b',
      explanation: 'The whole transition is captured by one value changing direction. Secondary hyperparathyroidism in chronic kidney disease is a gland driven from outside by three simultaneous stimuli — loss of renal 1-alpha-hydroxylation so calcitriol falls and stops suppressing the PTH gene, retained phosphate that both complexes calcium and stimulates the chief cell directly, and the resulting low ionised calcium — and its signature is a high PTH with a LOW or low-normal calcium, which is exactly what he had two years ago. Tertiary disease is the acquisition of autonomy after prolonged drive: a clonal nodule downregulates its calcium-sensing and vitamin D receptors and no longer responds to correction, so PTH stays high while calcium crosses to HIGH. That makes the disease surgical rather than medical, which is why the distinction matters. The skin lesions are calciphylaxis, not vasculitis: a raised calcium-phosphate product drives medial calcification and osteogenic transformation of dermal arterioles, with intimal fibrosis and thrombosis producing painful retiform purpura and necrotic ulcers, and a one-year mortality above 50%.',
      tests: 'mechanism',
    },
    {
      id: 'q3',
      stem: 'A 5-year-old girl is asymptomatic but carries a germline RET mutation at codon 634; her mother had medullary thyroid carcinoma at 31. Calcitonin is normal and the thyroid is impalpable. Her brother is a confirmed MEN1 carrier and asks why he is not offered a comparable preventive operation. Which statement is correct?',
      options: [
        { id: 'a', text: 'She should be observed with annual calcitonin and operated on only once the level rises, since removing a normal thyroid cannot be justified' },
        { id: 'b', text: 'She should have prophylactic total thyroidectomy after plasma metanephrines exclude a phaeochromocytoma; no equivalent exists in MEN1 because menin is a two-hit tumour suppressor whose tumours arise unpredictably in several organs' },
        { id: 'c', text: 'Both siblings should have prophylactic surgery, since MEN1 and MEN2 carry equivalent near-certain cancer risk in a single organ' },
        { id: 'd', text: 'Neither needs surgery, because RET and MEN1 mutations both require a somatic second hit and penetrance is therefore low' },
      ],
      answerId: 'b',
      explanation: 'The management difference is a direct readout of the genetics. RET is a proto-oncogene and the MEN2 mutation is ACTIVATING, so the single inherited allele is already sufficient to drive proliferation: penetrance for medullary thyroid carcinoma approaches 100%, the target is one predictable organ, and the tumour is preceded by diffuse C-cell hyperplasia. An organ certain to become malignant and removable in its entirety is therefore removed pre-emptively, in early childhood for codon 634 and in infancy for codon 918, which disposes of option a, since waiting for calcitonin to rise means waiting for carcinoma. MEN1 encodes menin and is a classic two-hit tumour suppressor, so disease needs an unpredictable somatic second hit in an unpredictable one of parathyroid, pancreatic islet, duodenum or pituitary; no single gland can be removed to pre-empt that, so surveillance is the only option and option c is wrong. Option d misstates RET, which acts dominantly through gain of function. The metanephrine screen first is not a detail: an unrecognised phaeochromocytoma can make induction of anaesthesia lethal.',
      tests: 'treatment',
    },
  ],
};

export default rbpParathyroidEndocrineNeoplasia;
