// MedCMU curriculum: Year → Subject (block). Lectures attach to a subject via
// `subjectOfSource` below. Only HCVS-2 (Year 3) has content so far.

export interface Subject {
  code: string;
  name: string;
}

export interface CurriculumYear {
  year: number;
  label: string;
  note?: string;
  subjects: Subject[];
}

export const curriculum: CurriculumYear[] = [
  {
    year: 1,
    label: 'Year 1',
    subjects: [
      { code: 'MBH', name: 'Molecular Basis of Human Body' },
      { code: 'HGD', name: 'Human Genetics and Developmental Biology' },
      { code: 'MFN', name: 'Metabolism of Fuel Nutrients in Human' },
      { code: 'ABM', name: 'Applied Biochemistry in Medicine' },
      { code: 'BMR', name: 'Intro to Biomedical Research' },
    ],
  },
  {
    year: 2,
    label: 'Year 2',
    subjects: [
      { code: 'BHCB', name: 'Basic Histology and Cell Biology' },
      { code: 'HIM', name: 'Human Immunology' },
      { code: 'EHP', name: 'Essential Human Physiology' },
      { code: 'HGA', name: 'Human Gross Anatomy' },
      { code: 'HEN-1', name: 'Human Endocrine System-1' },
      { code: 'HMS-1', name: 'Human Musculoskeletal System-1' },
      { code: 'HCVS-1', name: 'Human Cardiovascular System-1' },
      { code: 'HRS-1', name: 'Human Respiratory System-1' },
      { code: 'HGB-1', name: 'Human Gastrointestinal and Biliary Tract System-1' },
      { code: 'HRP-1', name: 'Human Reproductive System and Perinatal Period-1' },
      { code: 'HRU-1', name: 'Human Renal and Urinary System-1' },
      { code: 'HNS-1', name: 'Human Nervous and Special Senses System-1' },
      { code: 'MHI', name: 'Microbiology of Human Infectious Diseases' },
      { code: 'PHI', name: 'Parasitology of Human Infectious Diseases' },
      { code: 'BAP', name: 'Basic Human Anatomical Pathology' },
      { code: 'BCP', name: 'Basic Clinical Pharmacology' },
    ],
  },
  {
    year: 3,
    label: 'Year 3',
    subjects: [
      { code: 'HHL', name: 'Human Hematopoietic and Lymphoreticular System' },
      { code: 'HEN-2', name: 'Human Endocrine System-2' },
      { code: 'HMS-2', name: 'Human Musculoskeletal System-2' },
      { code: 'HCVS-2', name: 'Human Cardiovascular System-2' },
      { code: 'HRS-2', name: 'Human Respiratory System-2' },
      { code: 'HGB-2', name: 'Human Gastrointestinal and Biliary Tract System-2' },
      { code: 'HRP-2', name: 'Human Reproductive System and Perinatal Period-2' },
      { code: 'HRU-2', name: 'Human Renal and Urinary System-2' },
      { code: 'HNS-2', name: 'Human Nervous and Special Senses System-2' },
      { code: 'HSC', name: 'Human Skin and Connective Tissue System' },
      { code: 'ACP', name: 'Applied Clinical Pharmacology' },
      { code: 'BEH', name: 'Behavioral Science' },
      { code: 'ERS-1', name: 'Essential Research Skill-1' },
      { code: 'ICH', name: 'Intro to Community Health' },
      { code: 'IFH', name: 'Intro to Family Health' },
      { code: 'FCP-1', name: 'Fundamentals of Clinical Practice-1' },
    ],
  },
];

// Map each lecture `source` (L1–L4) to its subject. Add new lecture sources here
// as content for other subjects is authored.
export const subjectOfSource: Record<string, string> = {
  // HNS-1 — Human Nervous and Special Senses System-1 (Year 2)
  'L20 — Reticular Activating System, Sleep & Circadian Rhythms': 'HNS-1',
  'L14 — Auditory, Gustatory & Olfactory Pathways': 'HNS-1',
  'L13 — Cerebellum': 'HNS-1',
  'L12 — Basal Ganglia': 'HNS-1',
  'L11 — Brainstem Motor Centers': 'HNS-1',
  'L9 — Motor System': 'HNS-1',
  'L10 — Neurotransmission': 'HNS-1',
  'L22 — Development of the Nervous System': 'HNS-1',
  'L7 — Sensory Receptors': 'HNS-1',
  'L8 — Ascending Sensory Pathways': 'HNS-1',
  'L6 — Blood Supply of the Brain': 'HNS-1',
  'L6 — Ventricular System & CSF': 'HNS-1',
  'L3 — Cerebral Cortex': 'HNS-1',
  'L4 — Forebrain: Cerebrum': 'HNS-1',
  'L5 — Forebrain: Diencephalon': 'HNS-1',
  'L2 — Brainstem': 'HNS-1',
  'L1 — Spinal Cord': 'HNS-1',
  'L23 — Integrative Functions of the Brain': 'HNS-1',
  'L21 — Vestibular System': 'HNS-1',
  'L18 — Limbic System': 'HNS-1',
  'L19 — Brain Metabolism': 'HNS-1',
  'L15 — Physiology of Hearing': 'HNS-1',
  'L17 — Histology of the Ear': 'HNS-1',
  'L17 — Histology of Chemical Senses': 'HNS-1',
  'L16 — Phototransduction': 'HNS-1',

  // BCP — Basic Clinical Pharmacology (Year 2)
  'L1 — Introduction & Drug Development': 'BCP',
  'L2 — Pharmacokinetics': 'BCP',
  'L3 — Pharmacodynamics': 'BCP',
  'L4 — Antifungal Agents': 'BCP',
  'L5 — Anthelmintics': 'BCP',
  'L6 — Antiviral & Antiretroviral Agents': 'BCP',
  'L7 — Antibacterial Agents': 'BCP',
  'L8 — Cholinergic (Parasympathetic) Drugs': 'BCP',
  'L9 — Adrenergic (Sympathetic) Drugs': 'BCP',
  'L10 — Antineoplastic Agents': 'BCP',
  'L11 — Drug Interactions': 'BCP',
  'L12 — Antidotes': 'BCP',
  'L13 — Immunomodulating Agents': 'BCP',
  'L14 — Pharmacogenomics': 'BCP',
  'L15 — Drug Allergy & Adverse Drug Reactions': 'BCP',

  // MHI — Microbiology of Human Infectious Diseases (Year 2)
  'L1 — Introduction to Medical Virology': 'MHI',
  'L2 — RNA Viruses I (Non-enveloped)': 'MHI',
  'L3 — RNA Viruses II (Enveloped)': 'MHI',
  'L4 — Retroviruses': 'MHI',
  'L5 — RNA Viruses III (Arboviruses)': 'MHI',
  'L6 — DNA Viruses I': 'MHI',
  'L7 — DNA Viruses II': 'MHI',
  'L8 — Introduction to Medical Bacteriology': 'MHI',
  'L9 — Bacterial Genetics & Antibiotic Resistance': 'MHI',
  'L10 — Gram-Positive Cocci I (Staphylococci)': 'MHI',
  'L11 — Gram-Positive Cocci II (Streptococci)': 'MHI',
  'L12 — Gram-Positive Bacilli': 'MHI',
  'L13 — Gram-Negative Bacilli I (Enterobacterales)': 'MHI',
  'L14 — Gram-Negative Bacilli II': 'MHI',
  'L15 — Gram-Negative Cocci & Small Gram-Negative Rods': 'MHI',
  'L16 — Anaerobes': 'MHI',
  'L17 — Rickettsia & Chlamydia': 'MHI',
  'L18 — Mycobacteria, Nocardia & Actinomyces': 'MHI',
  'L19 — Spirochetes & Mycoplasma': 'MHI',
  'L20 — Introduction to Medical Mycology': 'MHI',
  'L21 — Fungal Toxins & Toxic Mushrooms': 'MHI',
  'L22 — Pathogenic Yeasts': 'MHI',
  'L23 — Dimorphic Pathogenic Fungi': 'MHI',
  'L24 — Pathogenic Filamentous Fungi I': 'MHI',
  'L25 — Pathogenic Filamentous Fungi II': 'MHI',

  // BAP — Basic Human Anatomical Pathology (Year 2, general pathology)
  'L1 — Introduction to Pathology': 'BAP',
  'L2 — Cell Injury & Cell Death': 'BAP',
  'L3 — Adaptive Responses to Cell Injury': 'BAP',
  'L4 — Intracellular Accumulations': 'BAP',
  'L5 — Inflammation & Repair': 'BAP',
  'L6 — Hemodynamic Disorders': 'BAP',
  'L7 — Neoplasm': 'BAP',
  'L8 — Environmental & Occupational Pathology': 'BAP',

  // HSC — Human Skin and Connective Tissue System (Year 3)
  'L1 — Dermatologic Diagnosis': 'HSC',
  'L2 — Skin Anatomy & Histology': 'HSC',
  'L3 — Skin Aging': 'HSC',
  'L4 — Cutaneous Immunology & Hypersensitivity': 'HSC',
  'L5 — Physiology of Skin & Thermoregulation': 'HSC',
  'L6 — Wound Healing': 'HSC',
  'L7 — Skin Infections': 'HSC',
  'L8 — Infestations & Helminthic Infections': 'HSC',
  'L9 — Papulosquamous & Vesiculobullous Diseases': 'HSC',
  'L10 — Panniculitis & Vasculitis': 'HSC',
  'L11 — Connective Tissue Diseases': 'HSC',
  'L12 — Cutaneous Drug Reactions': 'HSC',
  'L13 — Pediatric Skin Diseases': 'HSC',
  'L14 — Hair Diseases': 'HSC',
  'L15 — Pigmentary Disorders': 'HSC',
  'L16 — Eczema & Dermatitis': 'HSC',
  'L17 — Acne': 'HSC',
  'L18 — Skin Neoplasms': 'HSC',
  'L19 — Dermatologic Therapy': 'HSC',

  // HRU-2 — Human Renal and Urinary System-2 (Year 3)
  'L1 — Renal Defense Mechanisms': 'HRU-2',
  'L2 — Infectious UTI': 'HRU-2',
  'L3 — Urine Collection & Examination': 'HRU-2',
  'L4 — Urinary Tract Pathology': 'HRU-2',
  'L5 — Urinary Tract Infection (Clinical)': 'HRU-2',
  'L6 — Nephrotic & Nephritic Syndromes': 'HRU-2',
  'L7 — Interstitial & Mechanical Renal Disease': 'HRU-2',
  'L8 — Cystic Diseases of the Kidney': 'HRU-2',
  'L9 — Neoplasms of the Urinary System': 'HRU-2',
  'L10 — Renovascular Disorders': 'HRU-2',
  'L11 — Acute Kidney Injury & CKD': 'HRU-2',
  'L12 — Diuretics': 'HRU-2',
  'L13 — Drug Dosing in CKD': 'HRU-2',
  'L14 — Introduction to Glomerular Disease': 'HRU-2',
  'L15 — Fluid & Electrolyte Disorders (Clinical)': 'HRU-2',
  'L16 — Drugs for Urinary Frequency, Incontinence & Enuresis': 'HRU-2',
  'L17 — Fluid, Electrolytes & Acid–Base (KUB)': 'HRU-2',
  'L18 — Blood Gas & Anion Gap': 'HRU-2',

  // PHI — Parasitology of Human Infectious Diseases (Year 2)
  'L1 — Introduction to Parasitology': 'PHI',
  'L2 — Introduction to Protozoology': 'PHI',
  'L3 — Amoebae & Free-Living Amoebae': 'PHI',
  'L4 — Flagellates & Ciliates': 'PHI',
  'L5 — Introduction to Helminths & Ascariasis': 'PHI',
  'L6 — Toxocariasis & Anisakiasis': 'PHI',
  'L7 — Gnathostomiasis & Angiostrongyliasis': 'PHI',
  'L8 — Trematodes & Cestodes': 'PHI',
  'L9 — Apicomplexa': 'PHI',
  'L10 — Medical Acarology (Mites)': 'PHI',
  'L11 — Sparganosis & Echinococcosis': 'PHI',
  'L12 — Medical Entomology & Mosquito Vectors': 'PHI',
  'L13 — Medical Flies': 'PHI',

  // HGB-2 — Human Gastrointestinal and Biliary Tract System-2 (Year 3)
  'L1 — Pathology of the Upper GI Tract': 'HGB-2',
  'L2 — Pathology of the Lower GI Tract': 'HGB-2',
  'L3 — Pathology of the Liver': 'HGB-2',
  'L4 — Pathology of the Exocrine Pancreas': 'HGB-2',
  'L5 — Drugs in GI Disorders & ORS': 'HGB-2',
  'L6 — Peptic Ulcer Disease': 'HGB-2',
  'L7 — Nutrition & Malnutrition': 'HGB-2',
  'L8 — Obesity': 'HGB-2',
  'L9 — Drugs in Obesity': 'HGB-2',
  'L10 — Pharmacology in Liver Disease': 'HGB-2',
  'L11 — Viral Hepatitis': 'HGB-2',
  'L12 — Viral Gastroenteritis': 'HGB-2',
  'L13 — Bacterial GI Infection I': 'HGB-2',
  'L14 — Bacterial GI Infection II': 'HGB-2',
  'L15 — Intestinal Roundworms': 'HGB-2',
  'L16 — Aphasmid Nematodes': 'HGB-2',
  'L17 — GI Flukes & Tapeworms': 'HGB-2',
  'L18 — Vitamins & Trace Elements': 'HGB-2',
  'L19 — Eating Disorders': 'HGB-2',

  // HRS-2 — Human Respiratory System-2 (Year 3)
  'L1 — Bacterial Infection of the Upper Respiratory Tract': 'HRS-2',
  'L2 — Common Pathology of the Upper Respiratory Tract': 'HRS-2',
  'L3 — Respiratory Pharmacology': 'HRS-2',
  'L4 — Pathology of Obstructive Lung Diseases': 'HRS-2',
  'L5 — Pathology of Restrictive Lung Diseases': 'HRS-2',
  'L6 — Bacterial Infection of the Lower Respiratory Tract': 'HRS-2',
  'L7 — Fungal Lung Infections': 'HRS-2',
  'L8 — Viral Respiratory Pathogens & Lung Infection': 'HRS-2',
  'L9 — Parasitic Lung Infection': 'HRS-2',
  'L10 — Pathology of Pulmonary Infection': 'HRS-2',
  'L11 — Ventilation & Circulatory Disorders of the Lung': 'HRS-2',
  'L12 — Pulmonary Neoplasms': 'HRS-2',
  'L13 — Drugs for Lower Respiratory Disease': 'HRS-2',
  'L14 — Antibiotics for Respiratory Diseases': 'HRS-2',
  'L15 — Antiviral Drugs in Respiratory Infection': 'HRS-2',
  'L16 — Anti-Tuberculosis Drugs': 'HRS-2',
  'L17 — Pathology of the Mediastinum & Pleura': 'HRS-2',
  'L18 — Chest Radiology': 'HRS-2',
  'L19 — Early Clinical Exposure (HRS-II)': 'HRS-2',

  'L1 — Cardiac Arrhythmias': 'HCVS-2',
  'L2 — Abnormal ECG': 'HCVS-2',
  'L3 — Congenital Heart Disease': 'HCVS-2',
  'L4 — Antiarrhythmic Drugs': 'HCVS-2',
  'L5 — Vascular Disorders': 'HCVS-2',
  'L6 — Ischemic Heart Disease': 'HCVS-2',
  'L7 — Coagulation & Hemostasis': 'HCVS-2',
  'L8 — Valvular Heart Disease': 'HCVS-2',
  'L9 — Acute Coronary Syndrome': 'HCVS-2',
  'L10 — Cardiomyopathy & Myocarditis': 'HCVS-2',
  'L11 — Cardiogenic Shock': 'HCVS-2',
  'L12 — Heart Failure': 'HCVS-2',
  'L13 — Antianginal Drugs': 'HCVS-2',
  'L14 — Pathology of Heart Failure': 'HCVS-2',
  'L15 — Drugs Used in Heart Failure': 'HCVS-2',
  'L16 — Hypertension': 'HCVS-2',
  'L17 — Shock': 'HCVS-2',
  'L18 — Antihypertensive Drugs': 'HCVS-2',
  'L19 — Vascular Diseases II': 'HCVS-2',
  'L20 — Cardiac Tumors': 'HCVS-2',
  'L21 — Pericardial Disease': 'HCVS-2',

  // HEN-1 — Human Endocrine System-1 (Year 2)
  'L1 — Introduction to Endocrinology': 'HEN-1',
  'L2 — Development & Anatomy of Pituitary Gland & Hypothalamus': 'HEN-1',
  'L3 — Function & Metabolism of Pituitary Gland & Hypothalamus': 'HEN-1',
  'L4 — Development & Anatomy of Thyroid, Parathyroid Glands & Pancreatic Islets': 'HEN-1',
  'L5 — Metabolism & Function of Thyroid Gland': 'HEN-1',
  'L6 — Calcium, Phosphate & Vitamin D Metabolism': 'HEN-1',
  'L7 — Diagnosis of Diabetes Mellitus': 'HEN-1',
  'L8 — Function of Endocrine Pancreas & Adipose Tissue': 'HEN-1',
  'L9 — Development & Anatomy of Adrenal Gland': 'HEN-1',
  'L10 — Metabolism & Function of Adrenal Gland': 'HEN-1',

  // HNS-2 — Human Nervous and Special Senses System-2 (Year 3)
  'L1 — Clinical Neuroanatomy I': 'HNS-2',
  'L2 — Clinical Neuroanatomy II': 'HNS-2',
  'L3 — Common Ear Disorders': 'HNS-2',
  'L4 — Common Eye Disorders': 'HNS-2',
  'L5 — CNS Trauma & Hemorrhage': 'HNS-2',
  'L6 — Metabolic & Regulatory Disorders': 'HNS-2',
  'L7 — CNS Pharmacology & Stimulants': 'HNS-2',
  'L8 — Antiepileptic Drugs': 'HNS-2',
  'L9 — Antiparkinson Agents': 'HNS-2',
  'L10 — CNS Neoplasms': 'HNS-2',
  'L11 — Drugs for Ear Disorders': 'HNS-2',
  'L12 — Cognition & Consciousness': 'HNS-2',
  'L13 — Antimigraine Drugs': 'HNS-2',
  'L14 — Sedatives & Hypnotics': 'HNS-2',
  'L15 — Opioid Analgesics': 'HNS-2',
  'L16 — Antipsychotics': 'HNS-2',
  'L17 — Antidepressants': 'HNS-2',
  'L18 — CNS Infections & Immune Disorders': 'HNS-2',

  // HMS-2 — Human Musculoskeletal System-2 (Year 3)
  'L1 — Diseases of Bone': 'HMS-2',
  'L2 — Diseases of Skeletal Muscle': 'HMS-2',
  'L3 — Diseases of Joint': 'HMS-2',
  'L4 — Autacoids, NSAIDs & Salicylates': 'HMS-2',
  'L5 — Antirheumatic & Gout Drugs': 'HMS-2',
  'L6 — MSK Rehabilitation & Modalities': 'HMS-2',
  'L7 — Drugs & Bone Metabolism': 'HMS-2',
  'L8 — Musculoskeletal Tumors': 'HMS-2',

  // HEN-2 — Human Endocrine System-2 (Year 3)
  'L1 — Pituitary & Hypothalamus Pathology': 'HEN-2',
  'L2 — Pituitary & Hypothalamic Drugs': 'HEN-2',
  'L3 — Adrenal Pathology & MEN': 'HEN-2',
  'L4 — Cushing Syndrome': 'HEN-2',
  'L5 — Corticosteroids & Antagonists': 'HEN-2',
  'L6 — Thyroid & Parathyroid Pathology': 'HEN-2',
  'L7 — Clinical Pathology in Diabetes Mellitus': 'HEN-2',
  'L8 — Drugs Used in Thyroid Diseases': 'HEN-2',
  'L9 — Drugs Used in Parathyroid Diseases': 'HEN-2',
  'L10 — Investigations in Diabetes Mellitus': 'HEN-2',
  'L11 — DKA & Thyroid Storm': 'HEN-2',
  'L12 — Drugs Used in Diabetes': 'HEN-2',

  // HGD — Human Genetics and Developmental Biology (Year 1)
  'L1 — Genes & Embryonic Development': 'HGD',
  'L2 — Pre-embryonic Development': 'HGD',
  'L3 — Third Week & Germ Layer Derivatives': 'HGD',
  'L4 — Congenital Anomalies & Teratology': 'HGD',
  'L5 — Placenta & Extraembryonic Membranes': 'HGD',
  'L6 — Cell Cycle & Human Chromosomes': 'HGD',
  'L7 — Chromosome Aberrations': 'HGD',
  'L8 — Cytogenetic Nomenclature': 'HGD',
  'L9 — Autosomal Chromosome Syndromes': 'HGD',
  'L10 — Sex Chromosome Abnormalities': 'HGD',
  'L11 — Mendelian, Multifactorial & Population Genetics': 'HGD',
  'L12 — Prenatal Diagnosis': 'HGD',

  // MFN — Metabolism of Fuel Nutrients in Human (Year 1)
  'L1 — Nutrients, Digestion & Absorption': 'MFN',
  'L2 — Bioenergetics': 'MFN',
  'L3 — Carbohydrate Metabolism': 'MFN',
  'L4 — Amino Acid Metabolism': 'MFN',
  'L5 — Lipid Metabolism': 'MFN',
  'L6 — Integrative Metabolism': 'MFN',

  // ABM — Applied Biochemistry in Medicine (Year 1)
  'Case 1 — Acetaminophen Hepatotoxicity': 'ABM',
  'Case 2 — Cholangitis & Obstructive Jaundice': 'ABM',
  'Case 3 — ALDH2 Deficiency & Hepatic Encephalopathy': 'ABM',
  'Case 4 — G6PD Deficiency & Hemolysis': 'ABM',
  'Case 5 — Galactokinase Deficiency': 'ABM',
  'Case 6 — Hereditary Fructose Intolerance': 'ABM',
  'Case 7 — Familial Chylomicronemia Syndrome': 'ABM',
  'Case 8 — Familial Hypercholesterolemia': 'ABM',
  'Case 9 — MCAD Deficiency': 'ABM',
  'Case 10 — Obesity & Prediabetes': 'ABM',
  'Case 11 — Alcoholic Ketoacidosis': 'ABM',
  'Case 12 — Ketogenic Diet & Intermittent Fasting': 'ABM',
  'Case 13 — BRCA1-Mutant Triple-Negative Breast Cancer': 'ABM',
  'Case 14 — EGFR-Mutant Non-Small Cell Lung Cancer': 'ABM',
  'Case 15 — Epigenetics & Colon Cancer': 'ABM',

  // HGB-1 — Human Gastrointestinal and Biliary Tract System-1 (Year 2)
  'L1 — Histology of the Digestive Tract': 'HGB-1',
  'L2 — Histology of Accessory Digestive Organs': 'HGB-1',
  'L3 — Development of the Digestive System': 'HGB-1',
  'L4 — Chewing & Swallowing': 'HGB-1',
  'L5 — General & Integrative GI Physiology': 'HGB-1',
  'L6 — Gastric & Intestinal Motility': 'HGB-1',
  'L7 — GI Secretion': 'HGB-1',
  'L8 — Digestion & Absorption': 'HGB-1',
  'L9 — Bile Secretion': 'HGB-1',

  // HRP-1 — Human Reproductive System and Perinatal Period-1 (Year 2)
  'L1 — Gross Anatomy of Female Reproductive System': 'HRP-1',
  'L2 — Histology of the Female Reproductive System': 'HRP-1',
  'L3 — Anatomy of Breast & Placenta': 'HRP-1',
  'L4 — Gross Anatomy of Male Reproductive System': 'HRP-1',
  'L5 — Sex Steroid Hormones': 'HRP-1',
  'L6 — Histology of the Male Reproductive System': 'HRP-1',
  'L7 — Puberty & Disorders': 'HRP-1',
  'L8 — Female Reproductive Cycle': 'HRP-1',
  'L9 — Anatomy of Pelvic & Urogenital Diaphragm': 'HRP-1',
  'L10 — Gestational Hormones': 'HRP-1',
  'L11 — Lactation & Breastfeeding': 'HRP-1',
  'L12 — Menopause': 'HRP-1',
  'L13 — Pregnancy & Puerperium': 'HRP-1',
  'L14 — Child Abuse & Trauma': 'HRP-1',
  'L15 — Human Sexual Response & Sexual Dysfunction': 'HRP-1',
  'L16 — Gender Identity': 'HRP-1',
  'L17 — Development of the Reproductive System': 'HRP-1',
  'L18 — Semen Production & Analysis': 'HRP-1',

  // HRP-2 — Human Reproductive System & Perinatal Period-2 (Year 3): pathology,
  // infection, pharmacology & perinatal medicine of the reproductive system.
  'L1 — Vulvovaginitis & Vaginal Discharge': 'HRP-2',
  'L2 — Bacterial STIs & PID': 'HRP-2',
  'L3 — Viral STIs & Antiviral Therapy': 'HRP-2',
  'L4 — Perinatal (Congenital TORCH) Infections': 'HRP-2',
  'L5 — Pathology of the Cervix, Vagina & Vulva': 'HRP-2',
  'L6 — Pathology of the Uterine Corpus': 'HRP-2',
  'L7 — Gestational Trophoblastic Disease': 'HRP-2',
  'L8 — Pathology of the Ovary': 'HRP-2',
  'L9 — Pathology of the Breast': 'HRP-2',
  'L10 — Pathology of the Male Reproductive System': 'HRP-2',
  'L11 — Abnormal Uterine Bleeding': 'HRP-2',
  'L12 — HPO Axis, Amenorrhoea & Puberty': 'HRP-2',
  'L13 — Disorders Related to Pregnancy': 'HRP-2',
  'L14 — Perinatal Jaundice': 'HRP-2',
  'L15 — Female Sex Hormones & Inhibitors': 'HRP-2',
  'L16 — Androgens & Anti-androgens': 'HRP-2',
  'L17 — Drugs Affecting Uterine Contraction': 'HRP-2',

  // HGA — Human Gross Anatomy (Year 2) · Part 1: Upper Limb & Back
  'L1 — Pectoral Girdle, Superficial Back & Axilla': 'HGA',
  'L2 — Humerus, Shoulder Region & Cubital Fossa': 'HGA',
  'L3 — Forearm, Wrist Bones & Dorsum of Hand': 'HGA',
  'L4 — Palm of Hand & Joints of Upper Limb': 'HGA',
  'L5 — Deep Back & Joints of Vertebral Column': 'HGA',
  // Part 2: Head, Neck & Thorax
  'L6 — Face, Scalp, Parotid & Temporal Regions': 'HGA',
  'L7 — Triangles & Root of the Neck': 'HGA',
  'L8 — Thorax, Pleura, Trachea & Lungs': 'HGA',
  'L9 — Mediastinum & Heart': 'HGA',
  // Part 3: Skull & Deep Head Regions
  'L10 — Infratemporal & Pterygopalatine Fossae': 'HGA',
  'L11 — Skull & Cranial Fossae': 'HGA',
  'L12 — Orbit, Eye & Ear': 'HGA',
  'L13 — Nasal Cavity & Paranasal Sinuses': 'HGA',
  'L14 — Pharynx & Larynx': 'HGA',
  // Part 4: Oral Cavity & Abdomen
  'L15 — Mouth & Oral Cavity': 'HGA',
  'L16 — Anterior Abdominal Wall & Stomach': 'HGA',
  'L17 — Posterior Abdominal Wall & Urinary System': 'HGA',
  'L18 — Intestines, Liver & Biliary System': 'HGA',
  // Part 5: Lower Limb
  'L19 — Lower Limb Bones & Anterior/Medial Thigh': 'HGA',
  'L20 — Gluteal Region, Posterior Thigh & Popliteal Fossa': 'HGA',
  'L21 — Leg & Foot': 'HGA',

  // HRU-1 — Human Renal and Urinary System-1 (Year 2)
  'L1 — Microscopic Anatomy of the Kidney & Urinary Tract': 'HRU-1',
  'L2 — Development of the Kidney & Urinary Tract': 'HRU-1',
  'L3 — Glomerular Filtration, Hemodynamics & Tubular Transport': 'HRU-1',
  'L4 — Urinary Concentration & Dilution': 'HRU-1',
  'L5 — Micturition': 'HRU-1',
  'L6 — Body Fluids & Water Balance': 'HRU-1',
  'L7 — Renal Handling of Electrolytes': 'HRU-1',
  'L8 — Urinalysis I: Physical & Chemical': 'HRU-1',
  'L9 — Biochemistry of Urine': 'HRU-1',
  'L10 — Urinalysis II: Urine Sediment': 'HRU-1',
  'L11 — Renal Metabolism': 'HRU-1',
  'L12 — Renal Acid-Base Balance': 'HRU-1',

  // HCVS-1 — Human Cardiovascular System-1 (Year 2)
  'L1 — Overview of the Cardiovascular System': 'HCVS-1',
  'L2 — Histology of the Cardiovascular System': 'HCVS-1',
  'L3 — Development of the Cardiovascular System': 'HCVS-1',
  'L4 — Cardiac Electrophysiology': 'HCVS-1',
  'L5 — ECG Formation': 'HCVS-1',
  'L6 — Electrocardiography': 'HCVS-1',
  'L7 — Regulation of Blood Pressure': 'HCVS-1',
  'L8 — ECG in Clinical Practice': 'HCVS-1',
  'L9 — Echocardiography & Chest X-ray': 'HCVS-1',
  'L10 — Cardiac Cycle & Hemodynamics': 'HCVS-1',
  'L11 — Biomarkers in ACS': 'HCVS-1',
  'L12 — Ambulatory Blood Pressure Monitoring': 'HCVS-1',
  'L13 — Early Clinical Exposure (CVS)': 'HCVS-1',

  // HRS-1 — Human Respiratory System-1 (Year 2)
  'L1 — Development of the Respiratory System': 'HRS-1',
  'L2 — Structure of the Respiratory System': 'HRS-1',
  'L3 — Pulmonary Circulation': 'HRS-1',
  'L4 — Breathing & Ventilation': 'HRS-1',
  'L5 — Gas Exchange & Transport': 'HRS-1',
  'L6 — Regulation of Respiration & ABG': 'HRS-1',

  // HMS-1 — Human Musculoskeletal System-1 (Year 2)
  'L1 — Embryonic Development of the MSK System': 'HMS-1',
  'L2 — The Neuromuscular Junction': 'HMS-1',
  'L3 — Molecular Basis of Muscle Contraction': 'HMS-1',
  'L4 — Behaviour of Skeletal Muscle': 'HMS-1',
  'L5 — Energy Sources of Skeletal Muscle': 'HMS-1',
  'L6 — Fracture & Fracture Healing': 'HMS-1',

  // EHP — Essential Human Physiology (Year 2)
  'L1 — Transport of Solutes & Water': 'EHP',
  'L2 — Cellular Homeostasis': 'EHP',
  'L3 — Membrane Transport': 'EHP',
  'L4 — Genesis of the Action Potential': 'EHP',
  'L5 — Regulation of the Resting Membrane Potential': 'EHP',
  'L6 — Neurotransmitters & Neuromodulators': 'EHP',
  'L7 — Cell Communication': 'EHP',
  'L8 — Synaptic Plasticity': 'EHP',
  'L9 — Autonomic Nervous System': 'EHP',
  'L10 — Reflexes': 'EHP',
  'L11 — Cellular Aging & Cell Death': 'EHP',

  // HIM — Human Immunology (Year 2)
  'L1 — Cells & Tissues of the Immune System': 'HIM',
  'L2 — Innate Immunity': 'HIM',
  'L3 — Immunoglobulins': 'HIM',
  'L4 — Complement System': 'HIM',
  'L5 — Cell-Mediated Immunity': 'HIM',
  'L6 — MHC & Antigen Presentation': 'HIM',
  'L7 — Lymphocyte Development': 'HIM',
  'L8 — Immunodeficiency': 'HIM',
  'L9 — Humoral Immune Response': 'HIM',
  'L10 — Immunity to Microbes': 'HIM',
  'L11 — Mucosal Immunology & Microbiota': 'HIM',
  'L12 — Autoimmunity': 'HIM',
  'L13 — Hypersensitivity': 'HIM',
  'L14 — Antigen-Antibody Reactions': 'HIM',
  'L15 — Transplantation Immunology': 'HIM',
  'L16 — Tumor Immunology': 'HIM',
  'L17 — Manipulating the Immune System': 'HIM',

  // BHCB — Basic Histology and Cell Biology (Year 2)
  'L1 — Cytology': 'BHCB',
  'L2 — Cytoskeleton': 'BHCB',
  'L3 — Epithelium & Cell Adhesion': 'BHCB',
  'L4 — Glands & Connective Tissue': 'BHCB',
  'L5 — Membrane & Integument': 'BHCB',
  'L6 — Cartilage & Bone': 'BHCB',
  'L7 — Muscle Tissue': 'BHCB',
  'L8 — Nervous Tissue': 'BHCB',
  'L9 — Extracellular Matrix': 'BHCB',
  'L10 — Clinical Cell Biology': 'BHCB',

  // BMR — Intro to Biomedical Research (Year 1)
  'L1 — History of Medicine': 'BMR',
  'L2 — Introduction to Research': 'BMR',
  'L3 — Literature Review': 'BMR',
  'L4 — Research Methodology': 'BMR',
  'L5 — Outbreak Investigation': 'BMR',
  'L6 — Basic Statistics': 'BMR',
  'L7 — Human Research Ethics': 'BMR',
  'L8 — Types of Research Publication': 'BMR',
  'L9 — Academic Authorship': 'BMR',

  // ERS-1 — Essential Research Skill-1 (Year 3, the ERS-68 / RS2 course)
  'L1 — Research Question, Protocol & Ethics': 'ERS-1',
  'L2 — Epidemiologic Study Designs': 'ERS-1',
  'L3 — Measures of Frequency & Association': 'ERS-1',
  'L4 — Causal Inference: Bias & Confounding': 'ERS-1',
  'L5 — Diagnostic Test Evaluation': 'ERS-1',
  'L6 — Basic Biostatistics': 'ERS-1',
  'L7 — Statistical Tests & Sample Size': 'ERS-1',
  'L8 — Randomized Controlled Trials': 'ERS-1',
  'L9 — Systematic Review & Meta-Analysis': 'ERS-1',
  'L10 — Critical Appraisal of the Literature': 'ERS-1',

  // HHL — Human Hematopoietic and Lymphoreticular System (Year 2, CMU 330230)
  'L1 — Development of Blood & Lymphatics': 'HHL',
  'L2 — Red Blood Cell Structure & Function': 'HHL',
  'L3 — Abnormal Red Cell Morphology': 'HHL',
  'L4 — White Blood Cells: Morphology & Non-neoplastic': 'HHL',
  'L5 — Histology of the Lymphoid System': 'HHL',
  'L6 — Classification of Anemia & Aplastic Anemia': 'HHL',
  'L7 — Thalassemia & Hemoglobinopathies': 'HHL',
  'L8 — Nutritional Anemia': 'HHL',
  'L9 — Hemolytic Anemia': 'HHL',
  'L10 — Pathology of Lymph Node & Lymphoma': 'HHL',
  'L11 — Drugs for Anemia & Iron Chelation': 'HHL',
  'L12 — Drugs Affecting Hemostasis': 'HHL',
  'L13 — Myeloproliferative Neoplasms, MM & CLL': 'HHL',
  'L14 — Platelet & Hemostatic Disorders': 'HHL',
  'L15 — Acute Leukemia': 'HHL',
  'L16 — Targeted Therapy for Leukemia': 'HHL',
  'L17 — ABO & Rh Blood Groups; HDN': 'HHL',
  'L18 — Molecular Basis in Hematology': 'HHL',
  'L19 — Blood Donation & Blood Products': 'HHL',
  'L20 — Blood Transfusion Reactions': 'HHL',
  'L21 — Lymphatic Filariasis': 'HHL',
  'L22 — Schistosomiasis': 'HHL',
  'L23 — Haemoflagellates': 'HHL',
  'L24 — Malaria: Biology & Clinical Disease': 'HHL',
  'L25 — Malaria: Laboratory Diagnosis': 'HHL',
  'L26 — Antimalarial Drugs': 'HHL',
  'L27 — EBV & Infectious Mononucleosis': 'HHL',

  // IFH — Intro to Family Health (Year 3, CMU 327301)
  'L1 — Patient Journey & Introduction to Family Health': 'IFH',
  'L2 — Patient-Centered Medicine & Communication': 'IFH',
  'L3 — Family Assessment Tools & Basic Health Data': 'IFH',
  'L4 — Family Influences on Health': 'IFH',
  'L5 — Psychosocial Influences on Health': 'IFH',
  'L6 — Health Screening & Prevention': 'IFH',
  'L7 — Counselling, Health Promotion & Motivational Interviewing': 'IFH',
  'L8 — Caring for Special Populations': 'IFH',
  'L9 — Addiction and Health': 'IFH',
  'L10 — Traditional & Complementary Medicine': 'IFH',
  'L11 — Health Data for Quality Improvement': 'IFH',

  // ICH — Intro to Community Health (Year 3, CMU 322316)
  'L1 — Health Promotion & Disease Prevention': 'ICH',
  'L2 — Demography': 'ICH',
  'L3 — Determinants of Health': 'ICH',
  'L4 — Health Care Systems & Health Policy in Thailand': 'ICH',
  'L5 — Environmental Health Determinants': 'ICH',
  'L6 — Occupational Medicine': 'ICH',
  'L9 — Health Economics in Thailand': 'ICH',
  'L10 — Epidemiological Principles': 'ICH',
  'L11 — Epidemiological Methods': 'ICH',
  'L12 — Practical Evidence-Based Medicine': 'ICH',

  // BEH — Behavioral Science (Year 3, CMU 305301)
  'L1 — Introduction to Behavioral Science': 'BEH',
  'L2 — Doctor-Patient Relationship & Communication': 'BEH',
  'L3 — Psychiatric Assessment & Psychological Testing': 'BEH',
  'L4 — Mental Disorders (DSM-5-TR)': 'BEH',
  'L5 — Genetics & Biology of Behavior': 'BEH',
  'L6 — Growth and Development': 'BEH',
  'L7 — Family & its Psychopathology': 'BEH',
  'L8 — Learning & Humanistic Theory': 'BEH',
  'L9 — Psychodynamic Theories & Defense Mechanisms': 'BEH',
  'L10 — Elderly Life Cycle & Successful Aging': 'BEH',
  'L11 — Personality & Trait Theory': 'BEH',
  'L12 — Stress & Resilience': 'BEH',
  'L13 — Death, Dying & Bereavement': 'BEH',
  'L14 — Abuse, Suicide & Violence': 'BEH',

  // FCP-1 — Fundamentals of Clinical Practice-1 (Year 3, CMU, approach to symptoms)
  'L1 — Medical History Taking': 'FCP-1',
  'L2 — Pediatric History Taking': 'FCP-1',
  'L3 — Growth & Development Assessment': 'FCP-1',
  'L4 — Nutritional Assessment': 'FCP-1',
  'L5 — OB-Gyne History Taking & Vaginal Bleeding': 'FCP-1',
  'L6 — Fever': 'FCP-1',
  'L7 — Obesity & Weight Loss': 'FCP-1',
  'L8 — Edema': 'FCP-1',
  'L9 — Shock & Syncope': 'FCP-1',
  'L10 — Approach to the Trauma Patient': 'FCP-1',
  'L11 — Chest Pain': 'FCP-1',
  'L12 — Dyspnea & Cyanosis': 'FCP-1',
  'L13 — Cough & Hemoptysis': 'FCP-1',
  'L14 — Abdominal Pain, Nausea & Vomiting': 'FCP-1',
  'L15 — Dyspepsia, Reflux & Dysphagia': 'FCP-1',
  'L16 — Change in Bowel Habit': 'FCP-1',
  'L17 — Gastrointestinal Hemorrhage': 'FCP-1',
  'L18 — Jaundice': 'FCP-1',
  'L19 — Abdominal Mass': 'FCP-1',
  'L20 — Common Pediatric GI Symptoms': 'FCP-1',
  'L21 — Approach to Anemia': 'FCP-1',
  'L22 — Lymphadenopathy & Splenomegaly': 'FCP-1',
  'L23 — Bleeding Tendency': 'FCP-1',
  'L24 — Headache, Dizziness & Vertigo': 'FCP-1',
  'L25 — Weakness & Numbness': 'FCP-1',
  'L26 — Seizures & Abnormal Movements': 'FCP-1',
  'L27 — Movement Disorders': 'FCP-1',
  'L28 — Cognitive Impairment & Disorders of Consciousness': 'FCP-1',
  'L29 — Approach to Thyroid Disease': 'FCP-1',
  'L30 — Approach to Arthritis': 'FCP-1',
  'L31 — Skin Signs (Adult & Pediatric)': 'FCP-1',
  'L32 — Common ENT Symptoms': 'FCP-1',
  'L33 — Common Eye Symptoms': 'FCP-1',
  'L34 — Urinary Symptoms': 'FCP-1',
  'L35 — Pelvic Mass & Pelvic Pain': 'FCP-1',
  'L36 — Sexual Assault': 'FCP-1',
  'L37 — Medical Ethics & Professionalism': 'FCP-1',
  'L38 — Medical Law for Physicians': 'FCP-1',

  // MBH — Molecular Basis of Human Body (Year 1)
  'L1 — Amino Acids & Proteins': 'MBH',
  'L2 — Enzymes & Cofactors': 'MBH',
  'L3 — Nucleic Acids': 'MBH',
  'L4 — Nucleotide Metabolism': 'MBH',
  'L5 — DNA Replication': 'MBH',
  'L6 — DNA Repair & Human Genome': 'MBH',
  'L7 — Transcription & RNA Processing': 'MBH',
  'L8 — Translation & Protein Processing': 'MBH',
  'L9 — Control of Gene Expression': 'MBH',
  'L10 — Molecular Techniques': 'MBH',
  'L11 — Carbohydrate Chemistry': 'MBH',
  'L12 — Lipid Chemistry': 'MBH',
};

// Optional sub-grouping of a subject's lectures into "Parts" (e.g. HGA, a very
// large subject, is taught as Part 1–5). Maps a lecture `source` → part label.
// Subjects without entries here just render their lectures flat (ungrouped).
export const partOfSource: Record<string, string> = {
  // HGA Part 1 — Upper Limb & Back
  'L1 — Pectoral Girdle, Superficial Back & Axilla': 'Part 1 · Upper Limb & Back',
  'L2 — Humerus, Shoulder Region & Cubital Fossa': 'Part 1 · Upper Limb & Back',
  'L3 — Forearm, Wrist Bones & Dorsum of Hand': 'Part 1 · Upper Limb & Back',
  'L4 — Palm of Hand & Joints of Upper Limb': 'Part 1 · Upper Limb & Back',
  'L5 — Deep Back & Joints of Vertebral Column': 'Part 1 · Upper Limb & Back',
  // HGA Part 2 — Head, Neck & Thorax
  'L6 — Face, Scalp, Parotid & Temporal Regions': 'Part 2 · Head, Neck & Thorax',
  'L7 — Triangles & Root of the Neck': 'Part 2 · Head, Neck & Thorax',
  'L8 — Thorax, Pleura, Trachea & Lungs': 'Part 2 · Head, Neck & Thorax',
  'L9 — Mediastinum & Heart': 'Part 2 · Head, Neck & Thorax',
  // HGA Part 3 — Skull & Deep Head Regions
  'L10 — Infratemporal & Pterygopalatine Fossae': 'Part 3 · Skull & Deep Head Regions',
  'L11 — Skull & Cranial Fossae': 'Part 3 · Skull & Deep Head Regions',
  'L12 — Orbit, Eye & Ear': 'Part 3 · Skull & Deep Head Regions',
  'L13 — Nasal Cavity & Paranasal Sinuses': 'Part 3 · Skull & Deep Head Regions',
  'L14 — Pharynx & Larynx': 'Part 3 · Skull & Deep Head Regions',
  // HGA Part 4 — Oral Cavity & Abdomen
  'L15 — Mouth & Oral Cavity': 'Part 4 · Oral Cavity & Abdomen',
  'L16 — Anterior Abdominal Wall & Stomach': 'Part 4 · Oral Cavity & Abdomen',
  'L17 — Posterior Abdominal Wall & Urinary System': 'Part 4 · Oral Cavity & Abdomen',
  'L18 — Intestines, Liver & Biliary System': 'Part 4 · Oral Cavity & Abdomen',
  // HGA Part 5 — Lower Limb
  'L19 — Lower Limb Bones & Anterior/Medial Thigh': 'Part 5 · Lower Limb',
  'L20 — Gluteal Region, Posterior Thigh & Popliteal Fossa': 'Part 5 · Lower Limb',
  'L21 — Leg & Foot': 'Part 5 · Lower Limb',
};

export function subjectSlug(code: string): string {
  return code.toLowerCase();
}

export const subjectByCode: Record<string, Subject & { year: number }> = Object.fromEntries(
  curriculum.flatMap((y) => y.subjects.map((s) => [s.code, { ...s, year: y.year }])),
);

export const subjectBySlug: Record<string, Subject & { year: number }> = Object.fromEntries(
  Object.values(subjectByCode).map((s) => [subjectSlug(s.code), s]),
);
