/**
 * OPTIONAL offline enrichment for Active Integration.
 *
 * Regenerates `content/integrations.generated.ts` — a curated override map — using
 * the AI service layer (or the deterministic placeholder when no key is set).
 * This is a build-TIME authoring tool: the running app never calls it and stays
 * fully static / zero-backend.
 *
 *     npm run integrations:generate
 *
 * The key is read from `.env.local` (gitignored) or the environment:
 *     OPENAI_API_KEY=sk-...
 *     OPENAI_MODEL=gpt-4o-mini   # optional (default)
 *
 * Without a key it uses the deterministic LocalIntegrationGenerator, so it is
 * always safe to run. After a successful run, `content/integrations.ts` is wired
 * to re-export the generated map (see the header it writes).
 */

import { writeFileSync, readFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { lectures } from '../content';
import { resolveGenerator, collectCandidates } from '../lib/integrations/aiService';
import type { CuratedIntegrationOverride } from '../lib/integrations/types';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');

// --- minimal .env loader (no dependency) -------------------------------------
function loadEnv(file: string) {
  if (!existsSync(file)) return;
  for (const line of readFileSync(file, 'utf8').split('\n')) {
    const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*)\s*$/i);
    if (!m) continue;
    const key = m[1];
    let val = m[2].trim();
    if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) {
      val = val.slice(1, -1);
    }
    if (!process.env[key]) process.env[key] = val;
  }
}
loadEnv(join(ROOT, '.env.local'));
loadEnv(join(ROOT, '.env'));

const CONCURRENCY = Number(process.env.INTEGRATIONS_CONCURRENCY ?? 5);

async function main() {
  const generator = resolveGenerator();
  const total = lectures.length;
  console.log(
    `[integrations] generator=${generator.name} model=${process.env.OPENAI_MODEL ?? 'gpt-4o-mini'} ` +
      `modules=${total} concurrency=${CONCURRENCY}`,
  );
  if (generator.name === 'local') {
    console.warn('[integrations] No OPENAI_API_KEY found → deterministic output (set it in .env.local to use AI).');
  }

  const overrides: Record<string, CuratedIntegrationOverride> = {};
  let done = 0;
  let aiCount = 0;
  let next = 0;

  async function worker() {
    while (next < total) {
      const l = lectures[next++];
      const candidates = collectCandidates(l.id);
      const bundle = await generator.generate(l, candidates);
      if (bundle.generatedBy === 'openai') aiCount++;
      overrides[l.id] = {
        moduleId: l.id,
        prerequisite: bundle.prerequisite,
        forward: bundle.forward,
        horizontal: bundle.horizontal,
        vertical: bundle.vertical,
        traps: bundle.traps,
        repair: bundle.repair,
      };
      if (++done % 50 === 0 || done === total) {
        console.log(`[integrations] ${done}/${total} (AI: ${aiCount})`);
      }
    }
  }

  await Promise.all(Array.from({ length: Math.min(CONCURRENCY, total) }, worker));

  // A keyless run reproduces the live deterministic output — no point baking it.
  if (aiCount === 0) {
    console.log('[integrations] 0 modules via AI — leaving content/integrations.ts on the live deterministic graph.');
    return;
  }

  const header =
    '// AUTO-GENERATED by scripts/generate-integrations.ts — do not edit by hand.\n' +
    `// generator=${generator.name}  modules=${total}  ai=${aiCount}  generated=${new Date().toISOString()}\n` +
    "import type { CuratedIntegrationOverride } from '../lib/integrations/types';\n\n" +
    'export const curatedIntegrations: Record<string, CuratedIntegrationOverride> = ';
  writeFileSync(join(ROOT, 'content', 'integrations.generated.ts'), `${header}${JSON.stringify(overrides, null, 2)};\n`);

  // Wire content/integrations.ts to use the generated map.
  const activate =
    "// Active-Integration overrides. Regenerate with `npm run integrations:generate`.\n" +
    "// This re-exports the AI/deterministic map baked into integrations.generated.ts.\n" +
    "export { curatedIntegrations } from './integrations.generated';\n";
  writeFileSync(join(ROOT, 'content', 'integrations.ts'), activate);

  console.log(`[integrations] wrote content/integrations.generated.ts (${aiCount}/${total} via AI) and activated it.`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
